import type { InstructorQuestion } from "./instructor-question-bank";

const b = (zh: string, en: string) => ({ zh, en });

const teach = (zh: string, en: string) =>
  b(
    `${zh}\n\n迁移练习｜合上解析，保留同一物理关系但改变一个数值、一个参考方向或一个连接条件，重新写出条件、推导和检查。若只能复述本题答案，还没有达到掌握。`,
    `${en}\n\nTransfer | Close the explanation. Keep the same physical relationship but change one value, reference direction or connection condition, then restate the conditions, derivation and check. Repeating this answer alone is not mastery.`,
  );

/**
 * New assessment-style questions calibrated to the multi-step structure of
 * "Questions with work solutions 1.pdf". The source is used only as a
 * difficulty reference: every scenario, value and wording below is original.
 */
export const eeeDifficultyQuestionBank: InstructorQuestion[] = [
  {
    id: "eee-0-difficulty-01",
    courseId: "eee",
    topicId: "eee-0",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion", "diagram-board"],
    question: b(
      "某导体中通过参考截面的电荷为 q(t)=0.4t³-1.2t²+2t mC（0≤t≤3 s），正电流方向与正电荷通过截面的方向一致。哪一项同时正确给出 t=2 s 时的电流，以及 t=1 s 到 t=3 s 之间的净通过电荷？",
      "The charge that has crossed a reference surface is q(t)=0.4t³-1.2t²+2t mC for 0≤t≤3 s. Positive current follows positive charge crossing the surface. Which option gives both the current at t=2 s and the net charge transferred from t=1 s to t=3 s?",
    ),
    options: [
      b("i(2)=2.0 mA；Δq=4.8 mC", "i(2)=2.0 mA; Δq=4.8 mC"),
      b("i(2)=1.2 mA；Δq=6.0 mC", "i(2)=1.2 mA; Δq=6.0 mC"),
      b("i(2)=4.8 mA；Δq=2.0 mC", "i(2)=4.8 mA; Δq=2.0 mC"),
      b("i(2)=2.0 A；Δq=4.8 C", "i(2)=2.0 A; Δq=4.8 C"),
    ],
    answer: 0,
    visual: {
      kind: "table",
      title: b("电荷函数与求值时刻", "Charge function and evaluation times"),
      columns: [b("量", "Quantity"), b("表达式或区间", "Expression or interval")],
      rows: [
        ["q(t)", "0.4t^3 - 1.2t^2 + 2t mC"],
        ["instant", "t = 2 s"],
        ["transfer interval", "1 s to 3 s"],
      ],
    },
    explanation: teach(
      "第 1 步｜区分瞬时量与区间量\n瞬时电流来自电荷函数的导数；一段时间内的净电荷来自端点电荷之差。两者不能用同一次代值替代。\n\n第 2 步｜对 q(t) 求导\n因为 mC/s=mA，所以 i(t)=dq/dt=1.2t²-2.4t+2 mA。\n\n第 3 步｜求瞬时电流\ni(2)=1.2(2²)-2.4(2)+2=4.8-4.8+2=2.0 mA。正号表示实际方向与题设参考方向一致。\n\n第 4 步｜求净通过电荷\nq(3)=0.4(27)-1.2(9)+6=6.0 mC；q(1)=0.4-1.2+2=1.2 mC。因此 Δq=q(3)-q(1)=4.8 mC。\n\n第 5 步｜单位与积分检查\n对电流从 1 s 积分到 3 s 应回到 4.8 mC；同时 mA·s=mC，量纲吻合。\n\n结论\n选 A。导数回答某一时刻的流率，端点差回答整个区间的净转移量。",
      "Step 1 | Separate an instantaneous quantity from an interval quantity\nInstantaneous current is the derivative of charge. Net charge over an interval is the difference between endpoint values; one substitution cannot answer both.\n\nStep 2 | Differentiate q(t)\nSince mC/s=mA, i(t)=dq/dt=1.2t²-2.4t+2 mA.\n\nStep 3 | Evaluate the instantaneous current\ni(2)=1.2(2²)-2.4(2)+2=2.0 mA. Its positive sign means the physical direction agrees with the stated reference.\n\nStep 4 | Calculate the transferred charge\nq(3)=6.0 mC and q(1)=1.2 mC, hence Δq=q(3)-q(1)=4.8 mC.\n\nStep 5 | Check units and the integral relation\nIntegrating current from 1 s to 3 s must recover 4.8 mC, and mA·s=mC.\n\nConclusion\nChoose A. A derivative gives the rate at one instant; an endpoint difference gives net transfer over the interval.",
    ),
    rubric: {
      zh: ["1 分：写出 i=dq/dt", "2 分：正确求导并代入 t=2", "2 分：分别求 q(3)、q(1)", "1 分：给出净电荷", "1 分：说明符号和单位"],
      en: ["1: state i=dq/dt", "2: differentiate and evaluate at t=2", "2: evaluate q(3) and q(1)", "1: net charge", "1: interpret sign and units"],
    },
  },
  {
    id: "eee-0-difficulty-02",
    courseId: "eee",
    topicId: "eee-0",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "unit-conversion", "diagram-board"],
    question: b(
      "某二端元件采用被动符号约定，电流始终进入标有“+”的端子。0-2 s 内 v=6 V、i=2 A；2-5 s 内 v=-4 V、i=1.5 A。该元件在 0-5 s 的净能量变化是什么？",
      "A two-terminal element uses the passive sign convention, with current always referenced into the terminal marked '+'. For 0-2 s, v=6 V and i=2 A; for 2-5 s, v=-4 V and i=1.5 A. What is the element's net energy change over 0-5 s?",
    ),
    options: [
      b("净吸收 42 J", "Net absorption of 42 J"),
      b("净吸收 6 J", "Net absorption of 6 J"),
      b("净供给 6 J", "Net delivery of 6 J"),
      b("净供给 18 J", "Net delivery of 18 J"),
    ],
    answer: 1,
    visual: {
      kind: "table",
      title: b("分段电压与电流", "Piecewise voltage and current"),
      columns: [b("时间段", "Interval"), b("v", "v"), b("i", "i"), b("持续时间", "Duration")],
      rows: [
        ["0-2 s", "6 V", "2 A", "2 s"],
        ["2-5 s", "-4 V", "1.5 A", "3 s"],
      ],
    },
    explanation: teach(
      "第 1 步｜先固定功率符号\n题目明确采用被动符号约定，所以 p=vi。p>0 表示元件吸收能量，p<0 表示元件向外供给能量。\n\n第 2 步｜计算第一段能量\n0-2 s 内 p₁=6×2=12 W，因此 w₁=p₁Δt=12×2=24 J，为吸收。\n\n第 3 步｜计算第二段能量\n2-5 s 内 p₂=(-4)(1.5)=-6 W，因此 w₂=-6×3=-18 J。负号表示这段时间元件供给 18 J。\n\n第 4 步｜按代数值相加\nw=w₁+w₂=24+(-18)=6 J。不能把两段能量的绝对值相加，因为方向不同。\n\n第 5 步｜物理检查\n元件先吸收 24 J、后返还 18 J，最后仍保留净吸收 6 J；因此答案不可能是净供给。\n\n结论\n选 B：净吸收 6 J。",
      "Step 1 | Fix the power sign convention\nThe passive sign convention gives p=vi. Positive p means absorption; negative p means delivery to the rest of the circuit.\n\nStep 2 | Energy in the first interval\nFor 0-2 s, p₁=6×2=12 W, so w₁=12×2=24 J absorbed.\n\nStep 3 | Energy in the second interval\nFor 2-5 s, p₂=(-4)(1.5)=-6 W, so w₂=-6×3=-18 J. The element delivers 18 J in this interval.\n\nStep 4 | Add algebraically\nw=24+(-18)=6 J. Absolute values must not be added because the transfers have opposite directions.\n\nStep 5 | Physical check\nThe element absorbs 24 J and returns 18 J, leaving 6 J of net absorption.\n\nConclusion\nChoose B: net absorption of 6 J.",
    ),
    rubric: {
      zh: ["1 分：说明被动符号约定", "2 分：第一段功率与能量", "2 分：第二段功率与能量", "1 分：代数相加", "1 分：解释净吸收"],
      en: ["1: passive-sign interpretation", "2: first-interval power and energy", "2: second-interval power and energy", "1: algebraic sum", "1: interpret net absorption"],
    },
  },
  {
    id: "eee-0-difficulty-03",
    courseId: "eee",
    topicId: "eee-0",
    kind: "multiple",
    difficulty: "instructor",
    responseMode: "multi-select",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个 8 Ω 电阻的电压标注为左端“+”、右端“-”，测得 v=+16 V；参考电流 i_r 的箭头却从右向左。多选：哪些结论正确？",
      "An 8 Ω resistor is labelled '+' on the left and '-' on the right, with measured voltage v=+16 V. The reference-current arrow i_r points from right to left. Select every correct conclusion.",
    ),
    options: [
      b("i_r=+2 A，电阻向外供给 32 W", "i_r=+2 A and the resistor delivers 32 W"),
      b("因为电流箭头不符合被动符号约定，所以不能使用欧姆定律", "Ohm's law cannot be used because the current arrow is not passive"),
      b("i_r=-2 A，实际电流从左向右", "i_r=-2 A and the physical current flows left to right"),
      b("电阻吸收 32 W", "The resistor absorbs 32 W"),
    ],
    answer: [2, 3],
    visual: {
      kind: "table",
      title: b("参考标注", "Reference labels"),
      columns: [b("量", "Quantity"), b("参考定义", "Reference definition"), b("已知值", "Given")],
      rows: [
        ["v", "left (+) to right (-)", "+16 V"],
        ["i_r", "right to left", "?"],
        ["R", "resistor", "8 ohm"],
      ],
    },
    explanation: teach(
      "第 1 步｜识别参考方向冲突\n正电压端在左侧，但 i_r 的正方向从右向左，也就是进入负端。若定义进入正端的电流为 i_p，则 i_p=-i_r。\n\n第 2 步｜用一致的欧姆定律\n电阻在被动参考下满足 v=Ri_p。因此 i_p=v/R=16/8=2 A。\n\n第 3 步｜转换回题目所问的参考电流\n因为 i_r=-i_p，所以 i_r=-2 A。负值不代表错误，只表示实际电流方向与 i_r 箭头相反，即从左向右。\n\n第 4 步｜判断功率方向\n使用被动电流 i_p 计算 p=vi_p=16×2=32 W>0，所以电阻吸收 32 W。也可用 i_p²R=4×8=32 W 复核。\n\n第 5 步｜逐项筛选\nA 的电流符号和功率方向都错；B 错在把参考选择当成物理限制；C、D 正确。\n\n结论\n选择 C、D。关键不是强迫所有箭头都符合被动约定，而是在公式中正确转换参考方向。",
      "Step 1 | Identify the reference mismatch\nThe positive voltage terminal is on the left, while positive i_r enters the negative terminal. If i_p denotes current entering the positive terminal, then i_p=-i_r.\n\nStep 2 | Apply Ohm's law with consistent references\nFor the resistor, v=Ri_p, so i_p=16/8=2 A.\n\nStep 3 | Convert to the requested reference\nSince i_r=-i_p, i_r=-2 A. A negative result is meaningful: physical current flows opposite the i_r arrow, from left to right.\n\nStep 4 | Determine power direction\nUsing passive current, p=vi_p=16×2=32 W>0, so the resistor absorbs 32 W. The check i_p²R=32 W agrees.\n\nStep 5 | Test the choices\nA has both sign and power direction wrong. B mistakes a reference choice for a physical restriction. C and D are correct.\n\nConclusion\nSelect C and D. The skill is converting references consistently, not forcing every arrow into the passive convention.",
    ),
    rubric: {
      zh: ["1 分：定义被动电流", "1 分：写出 i_p=-i_r", "2 分：求两个参考下的电流", "2 分：计算并解释功率", "1 分：选出 C、D"],
      en: ["1: define passive current", "1: state i_p=-i_r", "2: currents in both references", "2: calculate and interpret power", "1: select C and D"],
    },
  },
  {
    id: "eee-1-difficulty-01",
    courseId: "eee",
    topicId: "eee-1",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个 18 V 理想电压源连接两个并联支路：支路 A 是 6 Ω 电阻；支路 B 是 4 Ω 与 2 Ω 电阻串联。哪一项同时正确给出两个支路电流、源电流和负载等效电阻？",
      "An ideal 18 V source supplies two parallel branches. Branch A is a 6 Ω resistor; branch B contains 4 Ω and 2 Ω in series. Which option gives both branch currents, the source current and the load equivalent resistance?",
    ),
    options: [
      b("I_A=3 A，I_B=4.5 A，I_s=7.5 A，R_eq=2.4 Ω", "I_A=3 A, I_B=4.5 A, I_s=7.5 A, R_eq=2.4 Ω"),
      b("I_A=I_B=1.5 A，I_s=1.5 A，R_eq=12 Ω", "I_A=I_B=1.5 A, I_s=1.5 A, R_eq=12 Ω"),
      b("I_A=3 A，I_B=3 A，I_s=6 A，R_eq=3 Ω", "I_A=3 A, I_B=3 A, I_s=6 A, R_eq=3 Ω"),
      b("I_A=6 A，I_B=3 A，I_s=9 A，R_eq=2 Ω", "I_A=6 A, I_B=3 A, I_s=9 A, R_eq=2 Ω"),
    ],
    answer: 2,
    visual: {
      kind: "table",
      title: b("并联网络结构", "Parallel-network structure"),
      columns: [b("支路", "Branch"), b("支路元件", "Branch elements"), b("支路电压", "Branch voltage")],
      rows: [
        ["A", "6 ohm", "18 V"],
        ["B", "4 ohm + 2 ohm in series", "18 V"],
      ],
    },
    explanation: teach(
      "第 1 步｜先化简支路内部\n支路 B 中 4 Ω 与 2 Ω 串联，所以 R_B=4+2=6 Ω。支路 A 也为 6 Ω。\n\n第 2 步｜利用并联共同电压\n两个支路都直接跨接在 18 V 电源上，因此 I_A=18/6=3 A，I_B=18/6=3 A。\n\n第 3 步｜在分流节点使用 KCL\n源电流等于两个支路电流之和：I_s=I_A+I_B=3+3=6 A。\n\n第 4 步｜求等效电阻\nR_eq=V/I_s=18/6=3 Ω。也可用 6||6=(6×6)/(6+6)=3 Ω 复核。\n\n第 5 步｜物理检查\n并联等效电阻必须小于任一 6 Ω 支路，3 Ω 合理；两个相同支路的电流也应相等。\n\n结论\n选 C。",
      "Step 1 | Reduce each branch internally\nThe 4 Ω and 2 Ω resistors in branch B are series, so R_B=6 Ω. Branch A is also 6 Ω.\n\nStep 2 | Use the common parallel voltage\nEach branch is directly across 18 V, hence I_A=18/6=3 A and I_B=18/6=3 A.\n\nStep 3 | Apply KCL at the split\nThe source current is I_s=I_A+I_B=6 A.\n\nStep 4 | Find equivalent resistance\nR_eq=V/I_s=18/6=3 Ω. The parallel formula 6||6=3 Ω confirms it.\n\nStep 5 | Physical check\nA parallel equivalent must be below either 6 Ω branch, and identical branches should carry equal currents.\n\nConclusion\nChoose C.",
    ),
    rubric: {
      zh: ["1 分：化简串联支路", "2 分：两个支路电流", "1 分：KCL 求源电流", "1 分：等效电阻", "1 分：并联范围检查"],
      en: ["1: reduce series branch", "2: branch currents", "1: source current by KCL", "1: equivalent resistance", "1: parallel-range check"],
    },
  },
  {
    id: "eee-1-difficulty-02",
    courseId: "eee",
    topicId: "eee-1",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "single-choice",
    cognitiveRole: "transfer",
    estimatedMinutes: 6,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个 24 V 电源与 3 Ω、5 Ω 两个电阻串联。判断三句话：① 回路电流为 3 A；② 5 Ω 电阻电压为 15 V；③ 理想电源向电路供给 72 W。哪一组正确？",
      "A 24 V source is in series with 3 Ω and 5 Ω resistors. Judge the claims: ① loop current is 3 A; ② voltage across the 5 Ω resistor is 15 V; ③ the ideal source delivers 72 W. Which combination is correct?",
    ),
    options: [
      b("只有①②", "① and ② only"),
      b("只有①③", "① and ③ only"),
      b("只有②③", "② and ③ only"),
      b("①②③全部", "All of ①, ② and ③"),
    ],
    answer: 3,
    visual: {
      kind: "table",
      title: b("单回路数据", "Single-loop data"),
      columns: [b("元件", "Element"), b("数值", "Value")],
      rows: [["source", "24 V"], ["R1", "3 ohm"], ["R2", "5 ohm"]],
    },
    explanation: teach(
      "第 1 步｜先独立判断，不猜组合\n串联回路中电流相同，总电阻 R_T=3+5=8 Ω。\n\n第 2 步｜判断①\nI=24/8=3 A，所以①正确。\n\n第 3 步｜判断②并做 KVL 检查\n5 Ω 电阻压降 V_5=IR=3×5=15 V；3 Ω 电阻压降为 9 V，9+15=24 V，满足 KVL，因此②正确。\n\n第 4 步｜判断③并做功率守恒\n源供给功率 P_s=VI=24×3=72 W。电阻吸收功率为 3²×3+3²×5=27+45=72 W，所以③正确。\n\n第 5 步｜匹配组合\n三句话均由独立计算和守恒检查支持。\n\n结论\n选 D：①②③全部正确。",
      "Step 1 | Judge the statements before viewing combinations\nSeries current is common and total resistance is 3+5=8 Ω.\n\nStep 2 | Test ①\nI=24/8=3 A, so ① is correct.\n\nStep 3 | Test ② and check KVL\nThe 5 Ω drop is 3×5=15 V. The other drop is 9 V, and 9+15=24 V, so ② is correct.\n\nStep 4 | Test ③ and check power balance\nThe source delivers P_s=24×3=72 W. The resistors absorb 3²×3+3²×5=27+45=72 W, so ③ is correct.\n\nStep 5 | Match the combination\nAll three statements survive independent calculations and conservation checks.\n\nConclusion\nChoose D: all of ①, ② and ③.",
    ),
    rubric: {
      zh: ["1 分：总电阻", "1 分：回路电流", "1 分：5 Ω 压降", "1 分：KVL 检查", "2 分：源功率与负载功率平衡"],
      en: ["1: total resistance", "1: loop current", "1: 5 Ω voltage", "1: KVL check", "2: source/load power balance"],
    },
  },
  {
    id: "eee-1-difficulty-03",
    courseId: "eee",
    topicId: "eee-1",
    kind: "multiple",
    difficulty: "instructor",
    responseMode: "multi-select",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "circuit-sketch"],
    question: b(
      "在一个节点，I₁=4 A 与 I₂=-1 A 的参考箭头都指向节点；I₃=2.5 A 与 I_x 的参考箭头都离开节点。多选：哪些结论正确？",
      "At a node, the reference arrows for I₁=4 A and I₂=-1 A point into the node; the reference arrows for I₃=2.5 A and I_x point away. Select every correct conclusion.",
    ),
    options: [
      b("按参考方向写 KCL 可得 4+(-1)=2.5+I_x", "Using the stated references, KCL gives 4+(-1)=2.5+I_x"),
      b("I₂ 的实际方向是离开节点，大小为 1 A", "The physical I₂ leaves the node with magnitude 1 A"),
      b("I_x=2.5 A", "I_x=2.5 A"),
      b("I₂ 为负说明题目数据违反电荷守恒", "Negative I₂ means the data violate charge conservation"),
    ],
    answer: [0, 1],
    visual: {
      kind: "table",
      title: b("节点电流参考", "Node-current references"),
      columns: [b("电流", "Current"), b("参考箭头", "Reference arrow"), b("代数值", "Algebraic value")],
      rows: [
        ["I1", "into node", "4 A"],
        ["I2", "into node", "-1 A"],
        ["I3", "out of node", "2.5 A"],
        ["Ix", "out of node", "?"],
      ],
    },
    explanation: teach(
      "第 1 步｜保留题目给出的箭头\n先按“流入=流出”写方程，不要因为 I₂ 为负就悄悄重画箭头：4+(-1)=2.5+I_x，所以 A 正确。\n\n第 2 步｜求未知电流\n左侧净参考流入为 3 A，因此 I_x=3-2.5=0.5 A。C 的 2.5 A 错误。\n\n第 3 步｜解释负电流\nI₂ 的参考箭头指向节点，但数值为 -1 A，故实际电流与箭头相反，即以 1 A 离开节点，所以 B 正确。\n\n第 4 步｜用实际方向复核守恒\n实际流入只有 I₁=4 A；实际流出为 1+2.5+0.5=4 A，完全满足 KCL。\n\n第 5 步｜排除概念错误\n负值只是方向信息，不是自动表示数据错误，因此 D 错。\n\n结论\n选择 A、B；I_x=0.5 A。",
      "Step 1 | Keep the given arrows\nWrite entering=leaving using the references without silently redrawing I₂: 4+(-1)=2.5+I_x. Thus A is correct.\n\nStep 2 | Solve the unknown\nNet referenced inflow is 3 A, so I_x=3-2.5=0.5 A. Choice C is false.\n\nStep 3 | Interpret the negative current\nI₂ is referenced into the node but equals -1 A, so its physical current is 1 A leaving. B is correct.\n\nStep 4 | Check KCL with physical directions\nActual inflow is 4 A; actual outflow is 1+2.5+0.5=4 A.\n\nStep 5 | Reject the misconception\nA negative result communicates direction; it does not automatically signal inconsistent data. D is false.\n\nConclusion\nSelect A and B; I_x=0.5 A.",
    ),
    rubric: {
      zh: ["1 分：按参考方向写 KCL", "1 分：求 I_x", "2 分：解释 I₂ 负号", "1 分：用实际方向复核", "1 分：选出 A、B"],
      en: ["1: KCL with stated references", "1: solve I_x", "2: interpret negative I₂", "1: physical-direction check", "1: select A and B"],
    },
  },
  {
    id: "eee-2-difficulty-01",
    courseId: "eee",
    topicId: "eee-2",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "节点 V_a 通过 3 Ω 接到 12 V 节点、通过 6 Ω 接地，并通过 2 Ω 接到节点 V_b。节点 V_b 还通过 4 Ω 接地，并有一个 2 A 电流源从地注入 V_b。哪一项给出 V_a、V_b 以及从 V_a 经 2 Ω 流向 V_b 的电流？",
      "Node V_a connects to a 12 V node through 3 Ω, to ground through 6 Ω, and to node V_b through 2 Ω. Node V_b also connects to ground through 4 Ω, and a 2 A source injects current from ground into V_b. Which option gives V_a, V_b and the current from V_a to V_b through 2 Ω?",
    ),
    options: [
      b("V_a=8 V，V_b=8 V，I_ab=0 A", "V_a=8 V, V_b=8 V, I_ab=0 A"),
      b("V_a=6 V，V_b=10 V，I_ab=-2 A", "V_a=6 V, V_b=10 V, I_ab=-2 A"),
      b("V_a=10 V，V_b=6 V，I_ab=2 A", "V_a=10 V, V_b=6 V, I_ab=2 A"),
      b("V_a=12 V，V_b=8 V，I_ab=2 A", "V_a=12 V, V_b=8 V, I_ab=2 A"),
    ],
    answer: 0,
    visual: {
      kind: "table",
      title: b("节点连接表", "Node-connection table"),
      columns: [b("节点", "Node"), b("连接", "Connection"), b("支路电流表达式", "Branch-current expression")],
      rows: [
        ["Va", "to 12 V through 3 ohm", "(Va-12)/3"],
        ["Va", "to ground through 6 ohm", "Va/6"],
        ["Va to Vb", "through 2 ohm", "(Va-Vb)/2"],
        ["Vb", "to ground through 4 ohm", "Vb/4"],
        ["source", "ground to Vb", "2 A entering"],
      ],
    },
    explanation: teach(
      "第 1 步｜确定未知量与电流方向\n以 V_a、V_b 为未知节点电压，并把每条电阻电流暂定为“从所写节点流出”。\n\n第 2 步｜在 V_a 写 KCL\n(V_a-12)/3+V_a/6+(V_a-V_b)/2=0。乘以 6 并整理得 2V_a-V_b=8。\n\n第 3 步｜在 V_b 写 KCL\n流出电阻的电流等于注入的 2 A：V_b/4+(V_b-V_a)/2=2。乘以 4 得 -2V_a+3V_b=8。\n\n第 4 步｜联立求解\n由第一式 V_b=2V_a-8。代入第二式：-2V_a+3(2V_a-8)=8，得 V_a=8 V，继而 V_b=8 V。\n\n第 5 步｜求支路电流并复核\nI_ab=(V_a-V_b)/2=0 A。检查 V_a：从 12 V 节点流入 (12-8)/3=4/3 A，向地流出 8/6=4/3 A；检查 V_b：2 A 注入并经 4 Ω 流出 8/4=2 A。两节点均守恒。\n\n结论\n选 A。两个节点电压相等并不表示电路无电流，只表示连接它们的 2 Ω 支路无电流。",
      "Step 1 | Define unknowns and branch references\nUse V_a and V_b as unknown node voltages, and reference every resistor current as leaving the node being analysed.\n\nStep 2 | KCL at V_a\n(V_a-12)/3+V_a/6+(V_a-V_b)/2=0. Multiplying by 6 gives 2V_a-V_b=8.\n\nStep 3 | KCL at V_b\nResistor currents leaving equal the 2 A injection: V_b/4+(V_b-V_a)/2=2. Multiplying by 4 gives -2V_a+3V_b=8.\n\nStep 4 | Solve simultaneously\nFrom the first equation V_b=2V_a-8. Substitution gives -2V_a+3(2V_a-8)=8, so V_a=8 V and V_b=8 V.\n\nStep 5 | Find the branch current and verify\nI_ab=(V_a-V_b)/2=0 A. At V_a, 4/3 A arrives from the 12 V node and 4/3 A leaves to ground. At V_b, the injected 2 A leaves through 4 Ω. Both KCL checks pass.\n\nConclusion\nChoose A. Equal node voltages eliminate current only in the branch between them, not everywhere in the circuit.",
    ),
    rubric: {
      zh: ["1 分：定义节点电压", "2 分：V_a 节点方程", "2 分：V_b 节点方程", "2 分：联立求解", "1 分：支路电流和双节点复核"],
      en: ["1: define node voltages", "2: V_a equation", "2: V_b equation", "2: simultaneous solution", "1: branch current and both-node checks"],
    },
  },
  {
    id: "eee-2-difficulty-02",
    courseId: "eee",
    topicId: "eee-2",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "两个顺时针网孔电流 I₁、I₂ 的方程由表中给出。共享支路电流参考方向取 I₁ 的方向，即 I_s=I₁-I₂。哪一项给出 I₁、I₂ 和 I_s？",
      "The table gives equations for two clockwise mesh currents I₁ and I₂. The shared-branch current is referenced in the I₁ direction, so I_s=I₁-I₂. Which option gives I₁, I₂ and I_s?",
    ),
    options: [
      b("I₁=2.00 A，I₂=0.67 A，I_s=1.33 A", "I₁=2.00 A, I₂=0.67 A, I_s=1.33 A"),
      b("I₁=16/7 A，I₂=2/21 A，I_s=46/21 A", "I₁=16/7 A, I₂=2/21 A, I_s=46/21 A"),
      b("I₁=18/8 A，I₂=-6/9 A，I_s=35/12 A", "I₁=18/8 A, I₂=-6/9 A, I_s=35/12 A"),
      b("I₁=16/7 A，I₂=2/21 A，I_s=50/21 A", "I₁=16/7 A, I₂=2/21 A, I_s=50/21 A"),
    ],
    answer: 1,
    visual: {
      kind: "table",
      title: b("网孔方程系数", "Mesh-equation coefficients"),
      columns: [b("方程", "Equation"), b("I₁ 系数", "I₁ coefficient"), b("I₂ 系数", "I₂ coefficient"), b("右端", "Right side")],
      rows: [
        ["mesh 1", "8", "-3", "18 V"],
        ["mesh 2", "-3", "9", "-6 V"],
      ],
    },
    explanation: teach(
      "第 1 步｜把表格写成联立方程\n8I₁-3I₂=18，-3I₁+9I₂=-6。负的互系数来自共享电阻中两个网孔电流方向相反。\n\n第 2 步｜消去 I₁\n把第一式乘 3、第二式乘 8：24I₁-9I₂=54；-24I₁+72I₂=-48。相加得 63I₂=6，所以 I₂=2/21 A。\n\n第 3 步｜回代求 I₁\n8I₁-3(2/21)=18，故 8I₁=18+2/7=128/7，I₁=16/7 A。\n\n第 4 步｜求共享支路电流\n题目指定 I_s=I₁-I₂，因此 I_s=16/7-2/21=48/21-2/21=46/21 A，约 2.19 A。\n\n第 5 步｜代回两式检查\n8(16/7)-3(2/21)=18；-3(16/7)+9(2/21)=-6。两个方程都成立，单位为安培。\n\n结论\n选 B。共享支路使用电流差，而不是看到两个网孔就机械相加。",
      "Step 1 | Convert the table into simultaneous equations\n8I₁-3I₂=18 and -3I₁+9I₂=-6. The negative mutual terms arise because the two mesh currents oppose in the shared resistor.\n\nStep 2 | Eliminate I₁\nMultiply the first equation by 3 and the second by 8: 24I₁-9I₂=54 and -24I₁+72I₂=-48. Adding gives 63I₂=6, so I₂=2/21 A.\n\nStep 3 | Back-substitute for I₁\n8I₁-3(2/21)=18, giving I₁=16/7 A.\n\nStep 4 | Find the shared-branch current\nThe stated reference gives I_s=I₁-I₂=16/7-2/21=46/21 A≈2.19 A.\n\nStep 5 | Substitute into both equations\nBoth original equations are satisfied, and every current carries amperes.\n\nConclusion\nChoose B. A shared branch uses an algebraic difference here, not an automatic sum.",
    ),
    rubric: {
      zh: ["1 分：正确抄写方程", "2 分：消元求 I₂", "2 分：回代求 I₁", "1 分：求共享支路电流", "1 分：代回检查"],
      en: ["1: transcribe equations", "2: eliminate for I₂", "2: back-substitute for I₁", "1: shared-branch current", "1: substitution check"],
    },
  },
  {
    id: "eee-2-difficulty-03",
    courseId: "eee",
    topicId: "eee-2",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "circuit-sketch"],
    question: b(
      "非参考节点 V₁ 与 V₂ 之间连接一个 5 V 理想电压源，极性使 V₁-V₂=5 V。V₁ 通过 5 Ω 接地，V₂ 通过 10 Ω 接地；一个 3 A 电流源从地向该超节点注入电流。哪一项正确？",
      "A 5 V ideal voltage source connects non-reference nodes V₁ and V₂ with polarity V₁-V₂=5 V. V₁ connects to ground through 5 Ω, V₂ through 10 Ω, and a 3 A source injects current from ground into the supernode. Which result is correct?",
    ),
    options: [
      b("V₁=10 V，V₂=5 V；电阻总流出 2.5 A", "V₁=10 V, V₂=5 V; total resistor outflow is 2.5 A"),
      b("V₁=5 V，V₂=0 V；电压源中没有电流", "V₁=5 V, V₂=0 V; no current flows through the voltage source"),
      b("V₁=35/3 V，V₂=20/3 V；电阻总流出 3 A", "V₁=35/3 V, V₂=20/3 V; total resistor outflow is 3 A"),
      b("V₁=20/3 V，V₂=35/3 V；满足 V₁-V₂=5 V", "V₁=20/3 V, V₂=35/3 V; this satisfies V₁-V₂=5 V"),
    ],
    answer: 2,
    visual: {
      kind: "table",
      title: b("超节点边界数据", "Supernode boundary data"),
      columns: [b("支路/约束", "Branch/constraint"), b("关系", "Relation")],
      rows: [
        ["V1 to ground", "V1 / 5"],
        ["V2 to ground", "V2 / 10"],
        ["current source", "3 A entering supernode"],
        ["voltage source", "V1 - V2 = 5 V"],
      ],
    },
    explanation: teach(
      "第 1 步｜识别超节点\n理想电压源位于两个未知节点之间，不能直接用电阻公式表示其电流，所以把 V₁、V₂ 和电压源整体包成超节点。\n\n第 2 步｜对超节点外边界写 KCL\n流向地的两条电阻电流之和等于注入的 3 A：V₁/5+V₂/10=3。乘以 10 得 2V₁+V₂=30。\n\n第 3 步｜加入电压源约束\n极性给出 V₁-V₂=5，即 V₁=V₂+5。这是第二个独立方程。\n\n第 4 步｜联立求解\n代入得 2(V₂+5)+V₂=30，故 3V₂=20，V₂=20/3 V；V₁=35/3 V。\n\n第 5 步｜电流与极性检查\nV₁/5=7/3 A，V₂/10=2/3 A，总流出 3 A；且 35/3-20/3=5 V。两项检查均通过。\n\n结论\n选 C。超节点法仍使用 KCL，只是把无法直接求电流的理想电压源留在边界内部。",
      "Step 1 | Identify the supernode\nAn ideal voltage source lies between two unknown nodes, so its current cannot be written with a resistance. Enclose V₁, V₂ and the source as one supernode.\n\nStep 2 | Write KCL around the outer boundary\nThe two resistor currents to ground equal the injected 3 A: V₁/5+V₂/10=3, or 2V₁+V₂=30.\n\nStep 3 | Add the source constraint\nThe polarity gives V₁-V₂=5, so V₁=V₂+5. This supplies the second independent equation.\n\nStep 4 | Solve\n2(V₂+5)+V₂=30 gives V₂=20/3 V and V₁=35/3 V.\n\nStep 5 | Check current and polarity\nV₁/5=7/3 A and V₂/10=2/3 A, totalling 3 A. Also 35/3-20/3=5 V.\n\nConclusion\nChoose C. Supernode analysis still applies KCL; it simply keeps the unknown ideal-source current inside the boundary.",
    ),
    rubric: {
      zh: ["1 分：识别超节点", "2 分：超节点 KCL", "1 分：电压约束", "2 分：联立求解", "1 分：电流和极性双重检查"],
      en: ["1: identify supernode", "2: supernode KCL", "1: voltage constraint", "2: simultaneous solution", "1: current and polarity checks"],
    },
  },
  {
    id: "eee-3-difficulty-01",
    courseId: "eee",
    topicId: "eee-3",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个网络由 18 V 理想源驱动 3 Ω 与 6 Ω 串联分压器，输出端口是 6 Ω 两端。现把 2 Ω 负载接到该端口。哪一项同时正确给出端口的 V_th、R_th、负载电流和负载功率？",
      "An 18 V ideal source drives a 3 Ω-6 Ω series divider, and the output port is across the 6 Ω resistor. A 2 Ω load is then connected to that port. Which option gives V_th, R_th, load current and load power?",
    ),
    options: [
      b("V_th=6 V，R_th=9 Ω，I_L=6/11 A，P_L≈0.60 W", "V_th=6 V, R_th=9 Ω, I_L=6/11 A, P_L≈0.60 W"),
      b("V_th=12 V，R_th=9 Ω，I_L=12/11 A，P_L≈2.38 W", "V_th=12 V, R_th=9 Ω, I_L=12/11 A, P_L≈2.38 W"),
      b("V_th=18 V，R_th=2 Ω，I_L=4.5 A，P_L=40.5 W", "V_th=18 V, R_th=2 Ω, I_L=4.5 A, P_L=40.5 W"),
      b("V_th=12 V，R_th=2 Ω，I_L=3 A，P_L=18 W", "V_th=12 V, R_th=2 Ω, I_L=3 A, P_L=18 W"),
    ],
    answer: 3,
    visual: {
      kind: "table",
      title: b("端口等效步骤", "Port-equivalent steps"),
      columns: [b("状态", "State"), b("网络", "Network")],
      rows: [
        ["open-circuit port", "18 V with 3 ohm and 6 ohm divider"],
        ["source zeroed", "3 ohm parallel 6 ohm seen at port"],
        ["loaded", "Thevenin model with RL=2 ohm"],
      ],
    },
    explanation: teach(
      "第 1 步｜开路求 V_th\n负载断开时，3 Ω 与 6 Ω 串联。端口跨在 6 Ω 上，所以 V_th=18×6/(3+6)=12 V。\n\n第 2 步｜独立源置零求 R_th\n理想电压源置零后用短路替代。从端口看，3 Ω 与 6 Ω 都接到地，因此 R_th=3||6=(3×6)/(3+6)=2 Ω。\n\n第 3 步｜接入负载\n戴维南模型中 R_th 与 R_L 串联：I_L=V_th/(R_th+R_L)=12/(2+2)=3 A。\n\n第 4 步｜求负载功率\nP_L=I_L²R_L=3²×2=18 W。也可由 V_L=I_LR_L=6 V 得 P_L=V_LI_L=18 W。\n\n第 5 步｜对原电路进行合理性检查\n接入 2 Ω 后，6 Ω 与 2 Ω 并联为 1.5 Ω，再与 3 Ω 串联；源电流 18/4.5=4 A，端口电压 4×1.5=6 V，与等效模型一致。\n\n结论\n选 D。",
      "Step 1 | Open-circuit voltage V_th\nWith the load removed, 3 Ω and 6 Ω form a divider. The port is across 6 Ω, so V_th=18×6/(3+6)=12 V.\n\nStep 2 | Zero the source for R_th\nReplace the ideal voltage source by a short. Looking into the port, 3 Ω and 6 Ω are parallel, hence R_th=3||6=2 Ω.\n\nStep 3 | Connect the load\nIn the Thevenin model, I_L=V_th/(R_th+R_L)=12/(2+2)=3 A.\n\nStep 4 | Load power\nP_L=I_L²R_L=3²×2=18 W. Equivalently, V_L=6 V and V_LI_L=18 W.\n\nStep 5 | Check against the original circuit\nWith the load present, 6||2=1.5 Ω in series with 3 Ω. Source current is 4 A and port voltage is 4×1.5=6 V, matching the equivalent.\n\nConclusion\nChoose D.",
    ),
    rubric: {
      zh: ["2 分：开路求 V_th", "2 分：置零源求 R_th", "1 分：负载电流", "1 分：负载功率", "1 分：原电路复核"],
      en: ["2: open-circuit V_th", "2: zero-source R_th", "1: load current", "1: load power", "1: original-circuit check"],
    },
  },
  {
    id: "eee-3-difficulty-02",
    courseId: "eee",
    topicId: "eee-3",
    kind: "multiple",
    difficulty: "instructor",
    responseMode: "multi-select",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "在线性电路中，以向右为负载电流正方向：仅保留电压源时贡献为 +1.8 A；仅保留电流源时贡献为 -0.6 A。负载是 5 Ω 电阻。多选：哪些结论正确？",
      "In a linear circuit, take rightward load current as positive. The voltage source alone contributes +1.8 A, and the current source alone contributes -0.6 A. The load is a 5 Ω resistor. Select every correct conclusion.",
    ),
    options: [
      b("总负载电流为 +1.2 A", "Total load current is +1.2 A"),
      b("总负载电流应把两个贡献的大小相加，得到 2.4 A", "The contribution magnitudes should be added, giving 2.4 A"),
      b("两个源同时作用时，负载功率为 7.2 W", "With both sources active, load power is 7.2 W"),
      b("可把两个源分别产生的负载功率直接相加得到总功率", "The load powers produced by the sources separately may be added directly"),
    ],
    answer: [0, 2],
    visual: {
      kind: "table",
      title: b("负载电流的带符号叠加", "Signed superposition of load current"),
      columns: [b("作用状态", "Active case"), b("相对向右参考", "Relative to rightward reference"), b("贡献", "Contribution")],
      rows: [
        ["voltage source alone", "same direction", "+1.8 A"],
        ["current source alone", "opposite direction", "-0.6 A"],
        ["both sources", "algebraic sum", "+1.2 A"],
      ],
    },
    explanation: teach(
      "第 1 步｜保留参考方向符号\n叠加的是带符号的电压或电流贡献，不是大小。故 I_L=+1.8+(-0.6)=+1.2 A，A 正确、B 错误。\n\n第 2 步｜解释结果方向\n总电流为正，表示实际电流仍向右；第二个源只是抵消了部分第一个源的贡献。\n\n第 3 步｜在全部源作用后求功率\n负载电阻的功率 P=I_L²R=(1.2)²×5=7.2 W，所以 C 正确。\n\n第 4 步｜说明功率不能叠加\n功率含有平方。若分开算会得到 (1.8)²×5=16.2 W 和 (0.6)²×5=1.8 W，相加为 18 W，并不等于实际 7.2 W。\n\n第 5 步｜回到叠加原理边界\n线性电路的响应量可以叠加，但功率不是线性响应量，因此 D 错。\n\n结论\n选择 A、C。",
      "Step 1 | Preserve reference signs\nSuperposition adds signed voltage or current contributions, not magnitudes. Thus I_L=1.8+(-0.6)=1.2 A. A is correct and B is false.\n\nStep 2 | Interpret direction\nThe positive total means physical current remains rightward; the second source partially opposes the first.\n\nStep 3 | Calculate power with all sources active\nP=I_L²R=(1.2)²×5=7.2 W, so C is correct.\n\nStep 4 | Show why powers do not superpose\nSeparate powers would be 16.2 W and 1.8 W, whose sum 18 W is not the actual 7.2 W because power contains a square.\n\nStep 5 | State the boundary of superposition\nLinear response variables can be superposed; power is not a linear response. D is false.\n\nConclusion\nSelect A and C.",
    ),
    rubric: {
      zh: ["2 分：带符号叠加电流", "1 分：解释方向", "2 分：计算总功率", "1 分：用分开功率展示矛盾", "1 分：说明叠加适用边界"],
      en: ["2: signed current superposition", "1: direction", "2: total power", "1: show separate-power contradiction", "1: state superposition boundary"],
    },
  },
  {
    id: "eee-3-difficulty-03",
    courseId: "eee",
    topicId: "eee-3",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "single-choice",
    cognitiveRole: "transfer",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个诺顿等效源为 I_N=4 A、R_N=3 Ω。判断：① 等效戴维南电压为 12 V；② 纯电阻负载在 R_L=3 Ω 时获得最大功率；③ 最大负载功率为 48 W。哪一组正确？",
      "A Norton equivalent has I_N=4 A and R_N=3 Ω. Judge: ① the equivalent Thevenin voltage is 12 V; ② a resistive load receives maximum power at R_L=3 Ω; ③ the maximum load power is 48 W. Which combination is correct?",
    ),
    options: [
      b("只有①②", "① and ② only"),
      b("只有①③", "① and ③ only"),
      b("只有②③", "② and ③ only"),
      b("①②③全部", "All of ①, ② and ③"),
    ],
    answer: 0,
    visual: {
      kind: "table",
      title: b("诺顿参数", "Norton parameters"),
      columns: [b("参数", "Parameter"), b("值", "Value")],
      rows: [["I_N", "4 A"], ["R_N", "3 ohm"], ["load", "variable R_L"]],
    },
    explanation: teach(
      "第 1 步｜完成源变换\nV_th=I_NR_N=4×3=12 V，且 R_th=R_N=3 Ω，所以①正确。\n\n第 2 步｜应用最大功率条件\n对纯电阻直流网络，最大功率传输发生在 R_L=R_th=3 Ω，因此②正确。\n\n第 3 步｜计算最大功率\nP_max=V_th²/(4R_th)=12²/(4×3)=144/12=12 W。也可算 I_L=12/(3+3)=2 A，再得 I_L²R_L=4×3=12 W。\n\n第 4 步｜判断③\n48 W 是把诺顿源的 4 A 全部错误地送入 3 Ω 负载所得；实际上电流会在 R_N 与 R_L 之间分流。故③错误。\n\n第 5 步｜范围检查\n最大负载功率 12 W 小于诺顿模型在短路/开路边界下所暗示的无限错误值，且电阻吸收为正。\n\n结论\n选 A：只有①②正确。",
      "Step 1 | Convert sources\nV_th=I_NR_N=4×3=12 V and R_th=R_N=3 Ω, so ① is correct.\n\nStep 2 | Apply the maximum-power condition\nFor a resistive DC network, maximum transfer occurs at R_L=R_th=3 Ω. Statement ② is correct.\n\nStep 3 | Calculate maximum power\nP_max=V_th²/(4R_th)=12²/(4×3)=12 W. Equivalently, I_L=12/(3+3)=2 A and I_L²R_L=12 W.\n\nStep 4 | Judge ③\nThe 48 W result incorrectly sends the full 4 A through the 3 Ω load; current actually divides between R_N and R_L. Thus ③ is false.\n\nStep 5 | Physical check\nThe result is positive absorption and agrees through both Thevenin and Norton representations.\n\nConclusion\nChoose A: only ① and ② are correct.",
    ),
    rubric: {
      zh: ["1 分：诺顿转戴维南", "1 分：等效电阻", "1 分：最大功率条件", "2 分：计算 P_max", "1 分：解释 48 W 错因"],
      en: ["1: Norton-to-Thevenin conversion", "1: equivalent resistance", "1: maximum-power condition", "2: calculate P_max", "1: explain why 48 W is wrong"],
    },
  },
  {
    id: "eee-4-difficulty-01",
    courseId: "eee",
    topicId: "eee-4",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个 250 μF 电容通过 4.0 kΩ 电阻接到 12 V 直流源。开关动作前 v_C(0⁻)=3 V，电容上端定义为正，电流进入正端。开关在 t=0 闭合。哪一项给出 t=2.0 s 时的 v_C 和 i_C？",
      "A 250 μF capacitor is connected through 4.0 kΩ to a 12 V DC source. Before switching, v_C(0⁻)=3 V, with the upper capacitor terminal positive and current referenced into it. The switch closes at t=0. Which option gives v_C and i_C at t=2.0 s?",
    ),
    options: [
      b("v_C=7.31 V，i_C=1.17 mA", "v_C=7.31 V, i_C=1.17 mA"),
      b("v_C≈10.78 V，i_C≈0.305 mA", "v_C≈10.78 V, i_C≈0.305 mA"),
      b("v_C=12.00 V，i_C=3.00 mA", "v_C=12.00 V, i_C=3.00 mA"),
      b("v_C≈4.22 V，i_C≈-0.305 mA", "v_C≈4.22 V, i_C≈-0.305 mA"),
    ],
    answer: 1,
    visual: {
      kind: "table",
      title: b("RC 切换条件", "RC switching data"),
      columns: [b("量", "Quantity"), b("值", "Value")],
      rows: [
        ["V_s", "12 V"],
        ["R", "4.0 kohm"],
        ["C", "250 microF"],
        ["v_C(0-)", "3 V"],
        ["evaluation time", "2.0 s"],
      ],
    },
    explanation: teach(
      "第 1 步｜确定初值、终值和时间常数\n电容电压连续，所以 v_C(0⁺)=3 V。直流稳态时电容开路，因此 v_C(∞)=12 V。τ=RC=(4.0×10³)(250×10⁻⁶)=1.0 s。\n\n第 2 步｜写完整响应\nv_C(t)=v_C(∞)+[v_C(0⁺)-v_C(∞)]e^(-t/τ)=12-9e^(-t)。\n\n第 3 步｜在 t=2 s 求电压\nv_C(2)=12-9e⁻²≈12-1.218=10.782 V。\n\n第 4 步｜由电阻或导数求电流\ni_C=(12-v_C)/R=1.218/4000≈0.0003045 A=0.305 mA。电流为正，符合充电时进入电容正端。\n\n第 5 步｜边界检查\n3 V<v_C(2)<12 V，且电流从初始 (12-3)/4 kΩ=2.25 mA 衰减到接近 0；结果合理。\n\n结论\n选 B。",
      "Step 1 | Identify initial value, final value and time constant\nCapacitor voltage is continuous, so v_C(0⁺)=3 V. At DC steady state the capacitor is open, hence v_C(∞)=12 V. τ=RC=(4.0×10³)(250×10⁻⁶)=1.0 s.\n\nStep 2 | Write the complete response\nv_C(t)=v_C(∞)+[v_C(0⁺)-v_C(∞)]e^(-t/τ)=12-9e^(-t).\n\nStep 3 | Evaluate at t=2 s\nv_C(2)=12-9e⁻²≈10.782 V.\n\nStep 4 | Find current from the resistor or derivative\ni_C=(12-v_C)/R=1.218/4000≈0.305 mA. It is positive, consistent with charging current entering the positive plate.\n\nStep 5 | Boundary check\n3 V<v_C(2)<12 V, while current decays from 2.25 mA toward zero.\n\nConclusion\nChoose B.",
    ),
    rubric: {
      zh: ["1 分：电压连续与初值", "1 分：终值", "1 分：时间常数", "2 分：完整响应和电压", "2 分：电流及方向检查"],
      en: ["1: voltage continuity and initial value", "1: final value", "1: time constant", "2: complete response and voltage", "2: current and direction check"],
    },
  },
  {
    id: "eee-4-difficulty-02",
    courseId: "eee",
    topicId: "eee-4",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion", "diagram-board"],
    question: b(
      "一个 200 μF 电容的电压按表中数据分段线性变化，电流参考方向进入电压正端。哪一项同时给出 0-1 s 的电流，以及 0-2 s 电容储能的变化？",
      "The voltage of a 200 μF capacitor changes piecewise linearly according to the table. Current is referenced into the positive-voltage terminal. Which option gives the current over 0-1 s and the change in stored energy over 0-2 s?",
    ),
    options: [
      b("i=+0.60 mA；储能增加 6.0 mJ", "i=+0.60 mA; stored energy increases by 6.0 mJ"),
      b("i=-3.0 mA；储能减少 12.0 mJ", "i=-3.0 mA; stored energy decreases by 12.0 mJ"),
      b("i=-0.60 mA；储能减少 6.0 mJ", "i=-0.60 mA; stored energy decreases by 6.0 mJ"),
      b("i=-0.60 A；储能减少 0.60 J", "i=-0.60 A; stored energy decreases by 0.60 J"),
    ],
    answer: 2,
    visual: {
      kind: "table",
      title: b("电容电压采样", "Capacitor-voltage samples"),
      columns: [b("t", "t"), b("v_C", "v_C"), b("相邻点之间", "Between adjacent samples")],
      rows: [
        ["0 s", "8 V", "linear to next point"],
        ["1 s", "5 V", "linear to next point"],
        ["2 s", "2 V", "end"],
      ],
    },
    explanation: teach(
      "第 1 步｜从表格读取斜率\n0-1 s 内电压由 8 V 线性降到 5 V，所以 dv/dt=(5-8)/(1-0)=-3 V/s。\n\n第 2 步｜由 i=C dv/dt 求电流\nC=200 μF=200×10⁻⁶ F，因此 i=(200×10⁻⁶)(-3)=-600×10⁻⁶ A=-0.60 mA。负号表示实际电流离开正端，电容在放能。\n\n第 3 步｜计算初始与最终储能\nw(0)=½Cv²=0.5(200×10⁻⁶)(8²)=6.4 mJ；w(2)=0.5(200×10⁻⁶)(2²)=0.4 mJ。\n\n第 4 步｜求储能变化\nΔw=w(2)-w(0)=0.4-6.4=-6.0 mJ，即储能减少 6.0 mJ。\n\n第 5 步｜功率方向检查\n在 0-2 s 内 v_C 为正而 i 为负，因此 p=vi<0，电容应向外供能；这与储能减少一致。\n\n结论\n选 C。",
      "Step 1 | Read the slope from the table\nOver 0-1 s, voltage falls linearly from 8 V to 5 V, so dv/dt=(5-8)/(1-0)=-3 V/s.\n\nStep 2 | Use i=C dv/dt\nC=200×10⁻⁶ F, giving i=(200×10⁻⁶)(-3)=-0.60 mA. The negative sign means physical current leaves the positive terminal, so the capacitor releases energy.\n\nStep 3 | Calculate initial and final stored energy\nw(0)=½Cv²=6.4 mJ and w(2)=0.4 mJ.\n\nStep 4 | Find the energy change\nΔw=w(2)-w(0)=0.4-6.4=-6.0 mJ: stored energy decreases by 6.0 mJ.\n\nStep 5 | Check power direction\nThroughout the interval v_C is positive while i is negative, so p=vi<0. Delivery of energy agrees with falling stored energy.\n\nConclusion\nChoose C.",
    ),
    rubric: {
      zh: ["1 分：由数据求 dv/dt", "2 分：单位换算与电流", "2 分：两端储能", "1 分：储能变化", "1 分：功率方向检查"],
      en: ["1: slope from data", "2: unit conversion and current", "2: endpoint energies", "1: energy change", "1: power-direction check"],
    },
  },
  {
    id: "eee-4-difficulty-03",
    courseId: "eee",
    topicId: "eee-4",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "error-analysis",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "circuit-sketch", "diagram-board"],
    question: b(
      "一个 100 μF 电容初始为 10 V，随后通过 2.0 kΩ 电阻放电到 0 V。电压正端在上方，i_C 参考方向进入正端。一位同学写成 v_C=10(1-e^(-t/0.2)) V、i_C=+5e^(-t/0.2) mA。哪一项是正确修正？",
      "A 100 μF capacitor initially at 10 V discharges through 2.0 kΩ toward 0 V. Its upper terminal is positive and i_C is referenced into that terminal. A student writes v_C=10(1-e^(-t/0.2)) V and i_C=+5e^(-t/0.2) mA. Which correction is valid?",
    ),
    options: [
      b("只需把时间常数改为 20 s，其余正确", "Only the time constant should be changed to 20 s"),
      b("电压式正确，但电流应为 -5e^(-t/0.2) A", "The voltage is correct, but current should be -5e^(-t/0.2) A"),
      b("v_C=10e^(-5t) V，i_C=+5e^(-5t) mA", "v_C=10e^(-5t) V, i_C=+5e^(-5t) mA"),
      b("v_C=10e^(-t/0.2) V，i_C=-5e^(-t/0.2) mA", "v_C=10e^(-t/0.2) V, i_C=-5e^(-t/0.2) mA"),
    ],
    answer: 3,
    visual: {
      kind: "table",
      title: b("放电边界条件", "Discharge boundary conditions"),
      columns: [b("检查点", "Checkpoint"), b("必须满足", "Required")],
      rows: [
        ["t=0+", "v_C=10 V"],
        ["t to infinity", "v_C to 0 V"],
        ["passive current", "i_C=C dv_C/dt"],
        ["time constant", "RC"],
      ],
    },
    explanation: teach(
      "第 1 步｜检查时间常数\nτ=RC=(2.0×10³)(100×10⁻⁶)=0.20 s，所以原时间常数数值正确。\n\n第 2 步｜用边界条件检查电压式\n放电响应必须满足 v_C(0⁺)=10 V、v_C(∞)=0。原式在 t=0 给出 0 V，立即失败。正确形式为 v_C=10e^(-t/0.2) V。\n\n第 3 步｜由导数求被动参考电流\ni_C=C dv_C/dt=(100×10⁻⁶)[-(10/0.2)e^(-t/0.2)]=-5×10⁻³e^(-t/0.2) A。\n\n第 4 步｜解释电流负号\n所以 i_C=-5e^(-t/0.2) mA。负号表示实际放电电流离开电容正端，符合储能元件向电阻供能。\n\n第 5 步｜初始值和终值复核\n在 t=0，电阻电流大小应为 10 V/2 kΩ=5 mA；随时间趋于无穷，电压和电流都趋于 0。\n\n结论\n选 D。原解同时混淆了充电波形和放电时的电流参考符号。",
      "Step 1 | Check the time constant\nτ=RC=(2.0×10³)(100×10⁻⁶)=0.20 s, so the numerical time constant is correct.\n\nStep 2 | Test the voltage against boundary conditions\nA discharge must satisfy v_C(0⁺)=10 V and v_C(∞)=0. The student's expression gives 0 V at t=0, so it fails immediately. The correct voltage is 10e^(-t/0.2) V.\n\nStep 3 | Differentiate for passive-reference current\ni_C=C dv_C/dt=(100×10⁻⁶)[-(10/0.2)e^(-t/0.2)]=-5×10⁻³e^(-t/0.2) A.\n\nStep 4 | Interpret the negative sign\nThus i_C=-5e^(-t/0.2) mA. Physical discharge current leaves the positive terminal, consistent with the capacitor delivering energy.\n\nStep 5 | Check endpoints\nInitially, resistor current magnitude is 10 V/2 kΩ=5 mA. Both voltage and current approach zero at long time.\n\nConclusion\nChoose D. The attempted solution confuses a charging waveform with discharge and misses the current-reference sign.",
    ),
    rubric: {
      zh: ["1 分：时间常数", "2 分：用初终值否定错误电压式", "2 分：求导得到电流", "1 分：解释负号", "1 分：初始电流复核"],
      en: ["1: time constant", "2: reject voltage using endpoints", "2: derivative for current", "1: interpret negative sign", "1: initial-current check"],
    },
  },
  {
    id: "eee-5-difficulty-01",
    courseId: "eee",
    topicId: "eee-5",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "18 V 直流源在 t=0 接到 6 Ω 电阻与 1.5 H 电感的串联支路。电流参考方向沿电源驱动方向，但 i_L(0⁻)=-1 A。哪一项给出 t=0.25 s 时的 i_L 与 v_L（被动符号约定）？",
      "At t=0, an 18 V DC source is connected to a series branch containing 6 Ω and 1.5 H. Current is referenced in the source-driven direction, but i_L(0⁻)=-1 A. Which option gives i_L and v_L at t=0.25 s using the passive sign convention?",
    ),
    options: [
      b("i_L≈1.53 A，v_L≈8.83 V", "i_L≈1.53 A, v_L≈8.83 V"),
      b("i_L≈1.90 A，v_L≈6.60 V", "i_L≈1.90 A, v_L≈6.60 V"),
      b("i_L≈2.63 A，v_L≈2.21 V", "i_L≈2.63 A, v_L≈2.21 V"),
      b("i_L≈-0.37 A，v_L≈20.21 V", "i_L≈-0.37 A, v_L≈20.21 V"),
    ],
    answer: 0,
    visual: {
      kind: "table",
      title: b("RL 切换条件", "RL switching data"),
      columns: [b("量", "Quantity"), b("值", "Value")],
      rows: [
        ["V_s", "18 V"],
        ["R", "6 ohm"],
        ["L", "1.5 H"],
        ["i_L(0-)", "-1 A"],
        ["evaluation time", "0.25 s"],
      ],
    },
    explanation: teach(
      "第 1 步｜确定连续初值、终值和时间常数\n电感电流连续，所以 i_L(0⁺)=-1 A。直流稳态时电感为短路，i_L(∞)=18/6=3 A。τ=L/R=1.5/6=0.25 s。\n\n第 2 步｜写完整电流响应\ni_L(t)=i(∞)+[i(0⁺)-i(∞)]e^(-t/τ)=3+(-1-3)e^(-t/0.25)=3-4e^(-4t)。\n\n第 3 步｜求 t=τ 时的电流\ni_L(0.25)=3-4e⁻¹≈3-1.4715=1.5285 A。\n\n第 4 步｜由 KVL 求电感电压\nv_L=V_s-Ri_L=18-6(1.5285)≈8.829 V。也可由 L di/dt=1.5(16e⁻¹)≈8.83 V 复核。\n\n第 5 步｜物理检查\n电流从 -1 A 连续地朝 3 A 上升；此时 di/dt>0，所以被动参考的 v_L 应为正，并最终衰减到 0。\n\n结论\n选 A。",
      "Step 1 | Establish continuous initial value, final value and time constant\nInductor current is continuous, so i_L(0⁺)=-1 A. At DC steady state the inductor is a short, giving i_L(∞)=18/6=3 A. τ=L/R=1.5/6=0.25 s.\n\nStep 2 | Write the complete current response\ni_L(t)=3+(-1-3)e^(-t/0.25)=3-4e^(-4t).\n\nStep 3 | Evaluate at t=τ\ni_L(0.25)=3-4e⁻¹≈1.5285 A.\n\nStep 4 | Use KVL for inductor voltage\nv_L=V_s-Ri_L=18-6(1.5285)≈8.829 V. The derivative check L di/dt=1.5(16e⁻¹) gives the same value.\n\nStep 5 | Physical check\nCurrent rises continuously from -1 A toward 3 A. Since di/dt>0, passive-reference v_L is positive and eventually decays to zero.\n\nConclusion\nChoose A.",
    ),
    rubric: {
      zh: ["1 分：电流连续初值", "1 分：终值和时间常数", "2 分：完整响应", "1 分：时刻电流", "2 分：电压与导数复核"],
      en: ["1: continuous current initial value", "1: final value and time constant", "2: complete response", "1: current at time", "2: voltage and derivative check"],
    },
  },
  {
    id: "eee-5-difficulty-02",
    courseId: "eee",
    topicId: "eee-5",
    kind: "multiple",
    difficulty: "instructor",
    responseMode: "multi-select",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion", "diagram-board"],
    question: b(
      "一个 0.5 H 电感初始电流为 0。按被动符号约定，0-1 s 加 v_L=+4 V，1-3 s 加 v_L=-2 V。多选：哪些结论正确？",
      "A 0.5 H inductor starts with zero current. Under the passive sign convention, v_L=+4 V for 0-1 s and v_L=-2 V for 1-3 s. Select every correct conclusion.",
    ),
    options: [
      b("i_L(1 s)=2 A", "i_L(1 s)=2 A"),
      b("i_L(1 s)=8 A", "i_L(1 s)=8 A"),
      b("i_L(3 s)=4 A", "i_L(3 s)=4 A"),
      b("该过程中最大储能为 16 J", "The maximum stored energy during the process is 16 J"),
    ],
    answer: [1, 3],
    visual: {
      kind: "table",
      title: b("分段电感电压", "Piecewise inductor voltage"),
      columns: [b("时间段", "Interval"), b("v_L", "v_L"), b("di/dt=v_L/L", "di/dt=v_L/L")],
      rows: [
        ["0-1 s", "+4 V", "+8 A/s"],
        ["1-3 s", "-2 V", "-4 A/s"],
      ],
    },
    explanation: teach(
      "第 1 步｜把电压转换为电流斜率\nv_L=L di/dt，因此 0-1 s 的斜率为 4/0.5=8 A/s，1-3 s 的斜率为 -2/0.5=-4 A/s。\n\n第 2 步｜积累第一段电流\n从 0 A 开始，经过 1 s：i_L(1)=0+8×1=8 A，所以 B 正确、A 错误。\n\n第 3 步｜积累第二段电流\n第二段持续 2 s，电流变化为 (-4)(2)=-8 A，所以 i_L(3)=8-8=0 A，C 错误。\n\n第 4 步｜求最大储能\n电流在 t=1 s 达到最大 8 A。w_max=½Li²=0.5(0.5)(8²)=16 J，因此 D 正确。\n\n第 5 步｜能量方向检查\n第一段 v、i 同号，电感吸能；第二段 v<0 而 i 在大部分时间仍 >0，电感返还能量，最终回到零储能。\n\n结论\n选择 B、D。",
      "Step 1 | Convert voltage to current slope\nFrom v_L=L di/dt, the slopes are 4/0.5=8 A/s over 0-1 s and -2/0.5=-4 A/s over 1-3 s.\n\nStep 2 | Accumulate current over the first interval\nStarting from 0 A, i_L(1)=0+8×1=8 A. B is correct and A is false.\n\nStep 3 | Accumulate over the second interval\nThe 2 s interval changes current by (-4)(2)=-8 A, so i_L(3)=0 A. C is false.\n\nStep 4 | Find maximum stored energy\nCurrent peaks at 8 A at t=1 s. w_max=½Li²=0.5(0.5)(8²)=16 J, so D is correct.\n\nStep 5 | Check energy direction\nIn the first interval v and i share sign and the inductor absorbs energy. In the second, v<0 while i is mostly positive, so energy is returned until storage reaches zero.\n\nConclusion\nSelect B and D.",
    ),
    rubric: {
      zh: ["1 分：两段 di/dt", "2 分：求 i(1)", "1 分：求 i(3)", "2 分：最大储能", "1 分：吸能/放能检查"],
      en: ["1: both di/dt values", "2: find i(1)", "1: find i(3)", "2: maximum energy", "1: absorption/delivery check"],
    },
  },
  {
    id: "eee-5-difficulty-03",
    courseId: "eee",
    topicId: "eee-5",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion", "diagram-board"],
    question: b(
      "一个 0.20 H 电感的初始电流 i_L(0)=1 A，电压按表中分段恒定，参考方向采用被动符号约定。哪一项给出 i_L(0.30 s) 与此时储能？",
      "A 0.20 H inductor has initial current i_L(0)=1 A. Its voltage is piecewise constant as shown, using the passive sign convention. Which option gives i_L(0.30 s) and its stored energy then?",
    ),
    options: [
      b("i_L=4 A，w=1.6 J", "i_L=4 A, w=1.6 J"),
      b("i_L=2 A，w=0.40 J", "i_L=2 A, w=0.40 J"),
      b("i_L=0 A，w=0 J", "i_L=0 A, w=0 J"),
      b("i_L=-2 A，w=-0.40 J", "i_L=-2 A, w=-0.40 J"),
    ],
    answer: 1,
    visual: {
      kind: "table",
      title: b("电感电压区间", "Inductor-voltage intervals"),
      columns: [b("时间段", "Interval"), b("v_L", "v_L"), b("持续时间", "Duration")],
      rows: [
        ["0-0.10 s", "+6 V", "0.10 s"],
        ["0.10-0.30 s", "-2 V", "0.20 s"],
      ],
    },
    explanation: teach(
      "第 1 步｜写电流增量公式\n对每个恒压区间，Δi=(v_L/L)Δt。必须逐段把前一段终值作为下一段初值。\n\n第 2 步｜第一段\nΔi₁=(6/0.20)(0.10)=3 A，所以 i(0.10)=1+3=4 A。\n\n第 3 步｜第二段\nΔi₂=(-2/0.20)(0.20)=-2 A，所以 i(0.30)=4-2=2 A。\n\n第 4 步｜计算储能\nw=½Li²=0.5(0.20)(2²)=0.40 J。电流可能带正负号，但储能由平方决定，不能为负。\n\n第 5 步｜电压-时间面积检查\n总电流变化也可由 (1/L)∫vdt=[6(0.10)-2(0.20)]/0.20=(0.6-0.4)/0.20=1 A；从初始 1 A 到最终 2 A，吻合。\n\n结论\n选 B。",
      "Step 1 | Use the current-increment relation\nFor each constant-voltage interval, Δi=(v_L/L)Δt. Carry the endpoint of one interval into the next.\n\nStep 2 | First interval\nΔi₁=(6/0.20)(0.10)=3 A, so i(0.10)=1+3=4 A.\n\nStep 3 | Second interval\nΔi₂=(-2/0.20)(0.20)=-2 A, so i(0.30)=4-2=2 A.\n\nStep 4 | Stored energy\nw=½Li²=0.5(0.20)(2²)=0.40 J. Current can have either sign, but stored energy cannot be negative because it depends on i².\n\nStep 5 | Voltage-time area check\nOverall Δi=(1/L)∫vdt=[6(0.10)-2(0.20)]/0.20=1 A. Starting from 1 A gives 2 A, matching the piecewise calculation.\n\nConclusion\nChoose B.",
    ),
    rubric: {
      zh: ["1 分：分段增量公式", "1 分：第一段终值", "1 分：第二段终值", "2 分：储能", "2 分：电压时间面积复核"],
      en: ["1: piecewise increment formula", "1: first endpoint", "1: second endpoint", "2: stored energy", "2: voltage-time area check"],
    },
  },
  {
    id: "eee-6-difficulty-01",
    courseId: "eee",
    topicId: "eee-6",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "10 V 电源通过 1.8 kΩ 电阻接到节点 v_o。一个硅二极管的阳极接 v_o、阴极接理想 2 V 参考源，采用 0.7 V 恒压降模型。哪一项给出自洽的二极管状态、v_o 和二极管电流？",
      "A 10 V source connects through 1.8 kΩ to node v_o. A silicon diode has its anode at v_o and cathode at an ideal 2 V reference, using the 0.7 V constant-drop model. Which option gives a self-consistent diode state, v_o and diode current?",
    ),
    options: [
      b("截止；v_o=10 V；i_D=0", "OFF; v_o=10 V; i_D=0"),
      b("导通；v_o=0.7 V；i_D≈5.17 mA", "ON; v_o=0.7 V; i_D≈5.17 mA"),
      b("导通；v_o=2.7 V；i_D≈4.06 mA", "ON; v_o=2.7 V; i_D≈4.06 mA"),
      b("导通；v_o=1.3 V；i_D≈4.83 mA", "ON; v_o=1.3 V; i_D≈4.83 mA"),
    ],
    answer: 2,
    visual: {
      kind: "table",
      title: b("二极管连接与模型", "Diode connection and model"),
      columns: [b("项目", "Item"), b("连接/数值", "Connection/value")],
      rows: [
        ["source through resistor", "10 V through 1.8 kohm to v_o"],
        ["diode anode", "v_o"],
        ["diode cathode", "2 V reference"],
        ["ON model", "v_A - v_K = 0.7 V"],
      ],
    },
    explanation: teach(
      "第 1 步｜明确模型与导通条件\n恒压降模型中，若二极管导通，则 v_A-v_K≈0.7 V 且正向电流 i_D≥0；若截止，则 i_D=0 且正向电压不能达到导通条件。\n\n第 2 步｜先假设导通\n阳极为 v_o、阴极固定为 2 V，所以 v_o-2=0.7，得到 v_o=2.7 V。不能把节点直接钳位到 0.7 V，因为阴极并不接地。\n\n第 3 步｜由电阻求电流\ni_D=(10-2.7)/1.8 kΩ=7.3/1800≈4.06 mA，方向从 10 V 源经电阻流入阳极。\n\n第 4 步｜验证假设\n计算得到 i_D>0，支持“导通”假设。若假设截止，则 v_o=10 V，会使 v_A-v_K=8 V，远超 0.7 V，与截止矛盾。\n\n第 5 步｜检查电压与单位\n电阻压降 10-2.7=7.3 V，7.3 V/1.8 kΩ 的确是 mA 量级；KVL 为 7.3+0.7+2=10 V。\n\n结论\n选 C。",
      "Step 1 | State the model and conduction conditions\nIn the constant-drop model, an ON diode has v_A-v_K≈0.7 V with forward current i_D≥0. An OFF diode has i_D=0 and must not be sufficiently forward biased.\n\nStep 2 | Assume ON\nThe anode is v_o and the cathode is fixed at 2 V, so v_o-2=0.7 and v_o=2.7 V. The node is not clamped to 0.7 V because the cathode is not grounded.\n\nStep 3 | Find resistor and diode current\ni_D=(10-2.7)/1.8 kΩ≈4.06 mA, flowing from the 10 V source through the resistor into the anode.\n\nStep 4 | Verify the assumption\nThe calculated i_D>0 supports ON. Assuming OFF would give v_o=10 V and v_A-v_K=8 V, contradicting OFF.\n\nStep 5 | Check voltage and units\nThe resistor drop is 7.3 V and 7.3 V/1.8 kΩ is correctly in milliamperes. KVL gives 7.3+0.7+2=10 V.\n\nConclusion\nChoose C.",
    ),
    rubric: {
      zh: ["1 分：写出导通/截止条件", "2 分：导通假设求节点电压", "1 分：求电流", "2 分：反证截止不自洽", "1 分：KVL 与单位检查"],
      en: ["1: ON/OFF conditions", "2: node voltage under ON assumption", "1: current", "2: disprove OFF assumption", "1: KVL and unit check"],
    },
  },
  {
    id: "eee-6-difficulty-02",
    courseId: "eee",
    topicId: "eee-6",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个桥式整流器由 12 V RMS 正弦源驱动，负载为 100 Ω，不接滤波电容。每个导通硅二极管按 0.7 V 压降计算。忽略源内阻，负载峰值电压和峰值电流约为多少？",
      "A bridge rectifier is driven by a 12 V RMS sinusoidal source and feeds a 100 Ω load with no filter capacitor. Model each conducting silicon diode as a 0.7 V drop and neglect source resistance. What are the approximate peak load voltage and peak load current?",
    ),
    options: [
      b("V_L,pk≈12.0 V；I_L,pk≈120 mA", "V_L,pk≈12.0 V; I_L,pk≈120 mA"),
      b("V_L,pk≈16.27 V；I_L,pk≈162.7 mA", "V_L,pk≈16.27 V; I_L,pk≈162.7 mA"),
      b("V_L,pk≈11.3 V；I_L,pk≈113 mA", "V_L,pk≈11.3 V; I_L,pk≈113 mA"),
      b("V_L,pk≈15.57 V；I_L,pk≈155.7 mA", "V_L,pk≈15.57 V; I_L,pk≈155.7 mA"),
    ],
    answer: 3,
    visual: {
      kind: "table",
      title: b("桥式整流峰值路径", "Bridge-rectifier peak path"),
      columns: [b("量", "Quantity"), b("关系", "Relation")],
      rows: [
        ["source", "12 V RMS sine"],
        ["source peak", "sqrt(2) times RMS"],
        ["conducting path", "2 diodes"],
        ["load", "100 ohm"],
      ],
    },
    explanation: teach(
      "第 1 步｜把 RMS 转为正弦峰值\nV_s,pk=√2V_rms=√2×12≈16.97 V。12 V 不是波形峰值。\n\n第 2 步｜识别桥式导通路径\n每个半周都有两个二极管串联导通，因此总近似压降为 2×0.7=1.4 V。\n\n第 3 步｜求负载峰值电压\nV_L,pk≈V_s,pk-1.4=16.97-1.4=15.57 V。\n\n第 4 步｜由欧姆定律求峰值电流\nI_L,pk=V_L,pk/R_L=15.57/100=0.1557 A=155.7 mA。\n\n第 5 步｜物理检查\n输出峰值必须低于源峰值，且 100 Ω 上约 16 V 应产生约 0.16 A；数量级和压降方向都合理。\n\n结论\n选 D。若只减去一个 0.7 V，会漏掉桥式路径中的第二个导通二极管。",
      "Step 1 | Convert RMS to sinusoidal peak\nV_s,pk=√2V_rms=√2×12≈16.97 V. The 12 V rating is not the waveform peak.\n\nStep 2 | Identify the bridge conduction path\nTwo diodes conduct in series on each half-cycle, giving an approximate total drop of 1.4 V.\n\nStep 3 | Peak load voltage\nV_L,pk≈16.97-1.4=15.57 V.\n\nStep 4 | Peak load current\nI_L,pk=V_L,pk/R_L=15.57/100=0.1557 A=155.7 mA.\n\nStep 5 | Physical check\nOutput peak must be below source peak, and about 16 V across 100 Ω should produce about 0.16 A.\n\nConclusion\nChoose D. Subtracting only one 0.7 V drop misses the second conducting diode in the bridge path.",
    ),
    rubric: {
      zh: ["1 分：RMS 转峰值", "1 分：识别两个导通二极管", "2 分：负载峰值电压", "1 分：峰值电流", "1 分：数量级检查"],
      en: ["1: RMS-to-peak conversion", "1: identify two conducting diodes", "2: peak load voltage", "1: peak current", "1: magnitude check"],
    },
  },
  {
    id: "eee-6-difficulty-03",
    courseId: "eee",
    topicId: "eee-6",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "single-choice",
    cognitiveRole: "transfer",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个限幅电路中，v_in 通过 2.0 kΩ 电阻接到 v_out；二极管阳极接地、阴极接 v_out，采用 0.7 V 模型，输出无其他负载。判断：① 当 v_in=-5 V 时二极管导通且 v_out≈-0.7 V；② 此时电阻电流大小约 2.15 mA；③ 当 v_in=+5 V 时二极管导通并把 v_out 钳位在 +0.7 V。哪一组正确？",
      "In a limiter, v_in connects through 2.0 kΩ to v_out. A diode has its anode grounded and cathode at v_out, using the 0.7 V model; there is no other load. Judge: ① at v_in=-5 V the diode is ON and v_out≈-0.7 V; ② resistor-current magnitude is about 2.15 mA; ③ at v_in=+5 V the diode is ON and clamps v_out to +0.7 V. Which combination is correct?",
    ),
    options: [
      b("只有①②", "① and ② only"),
      b("只有①③", "① and ③ only"),
      b("只有②③", "② and ③ only"),
      b("①②③全部", "All of ①, ② and ③"),
    ],
    answer: 0,
    visual: {
      kind: "table",
      title: b("限幅器的两个输入状态", "Two limiter input states"),
      columns: [b("输入", "Input"), b("二极管阳极", "Diode anode"), b("二极管阴极", "Diode cathode")],
      rows: [
        ["v_in=-5 V", "0 V", "v_out tends negative"],
        ["v_in=+5 V", "0 V", "v_out tends positive"],
      ],
    },
    explanation: teach(
      "第 1 步｜写正向导通条件\n二极管阳极为 0 V、阴极为 v_out。导通时 v_A-v_K≈0.7 V，即 0-v_out≈0.7，所以钳位电平是 v_out≈-0.7 V。\n\n第 2 步｜判断负输入\n当 v_in=-5 V 时，若二极管截止，v_out 会趋近 -5 V，使 v_A-v_K≈5 V，强烈正向偏置，因此截止不自洽，二极管导通。①正确。\n\n第 3 步｜计算负输入时电流\n电阻两端电压大小为 |-5-(-0.7)|=4.3 V，电流大小 4.3/2.0 kΩ=2.15 mA。实际电流由地经二极管流向输出，再经电阻流向输入源。②正确。\n\n第 4 步｜判断正输入\n当 v_in=+5 V 时，输出趋向正值，阳极 0 V 低于阴极，二极管反向偏置并截止；无负载时 v_out≈+5 V，不会钳在 +0.7 V。③错误。\n\n第 5 步｜迁移符号检查\n改变二极管方向会改变被钳位的半周；当前阳极接地的方向限制负向，而不是正向。\n\n结论\n选 A：只有①②正确。",
      "Step 1 | Write the forward-conduction condition\nThe anode is 0 V and cathode is v_out. When ON, v_A-v_K≈0.7 V, so the clamp level is v_out≈-0.7 V.\n\nStep 2 | Test negative input\nAt v_in=-5 V, assuming OFF would pull v_out toward -5 V and produce v_A-v_K≈5 V, a contradiction. The diode is ON, so ① is correct.\n\nStep 3 | Calculate current for negative input\nResistor-voltage magnitude is |-5-(-0.7)|=4.3 V, giving 4.3/2.0 kΩ=2.15 mA. Physical current flows from ground through the diode and resistor toward the input source. Statement ② is correct.\n\nStep 4 | Test positive input\nAt +5 V, the cathode is positive relative to the grounded anode, so the diode is reverse biased and OFF. With no load, v_out≈+5 V, not +0.7 V. Statement ③ is false.\n\nStep 5 | Transfer the sign logic\nReversing the diode would reverse the clipped half-cycle. This orientation limits negative output, not positive output.\n\nConclusion\nChoose A: only ① and ② are correct.",
    ),
    rubric: {
      zh: ["1 分：写导通条件", "1 分：负输入状态验证", "2 分：电流大小和方向", "1 分：正输入截止分析", "1 分：说明二极管反向后的迁移"],
      en: ["1: conduction condition", "1: verify negative-input state", "2: current magnitude and direction", "1: positive-input OFF analysis", "1: transfer to reversed diode"],
    },
  },
  {
    id: "eee-7-difficulty-01",
    courseId: "eee",
    topicId: "eee-7",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion", "diagram-board"],
    question: b(
      "120 V RMS、50 Hz 电源驱动串联 RLC：R=20 Ω、L=0.10 H、C=200 μF。以电源电压相位为 0°。哪一项给出总阻抗和电流相量？",
      "A 120 V RMS, 50 Hz source drives a series RLC circuit with R=20 Ω, L=0.10 H and C=200 μF. Take the source-voltage phase as 0°. Which option gives total impedance and current phasor?",
    ),
    options: [
      b("Z=20-j15.5 Ω=25.3∠-37.8° Ω；I=4.74∠+37.8° A", "Z=20-j15.5 Ω=25.3∠-37.8° Ω; I=4.74∠+37.8° A"),
      b("Z≈20+j15.5 Ω=25.3∠37.8° Ω；I≈4.74∠-37.8° A", "Z≈20+j15.5 Ω=25.3∠37.8° Ω; I≈4.74∠-37.8° A"),
      b("Z=20+j47.3 Ω=51.4∠67.1° Ω；I=2.33∠-67.1° A", "Z=20+j47.3 Ω=51.4∠67.1° Ω; I=2.33∠-67.1° A"),
      b("Z=35.5 Ω；I=3.38∠0° A", "Z=35.5 Ω; I=3.38∠0° A"),
    ],
    answer: 1,
    visual: {
      kind: "table",
      title: b("串联 RLC 参数", "Series-RLC data"),
      columns: [b("量", "Quantity"), b("值", "Value"), b("阻抗关系", "Impedance relation")],
      rows: [
        ["f", "50 Hz", "omega=2 pi f"],
        ["R", "20 ohm", "Z_R=R"],
        ["L", "0.10 H", "Z_L=j omega L"],
        ["C", "200 microF", "Z_C=-j/(omega C)"],
        ["V", "120 angle 0 deg V RMS", "I=V/Z"],
      ],
    },
    explanation: teach(
      "第 1 步｜把频率转换为角频率\nω=2πf=2π(50)≈314.16 rad/s。\n\n第 2 步｜分别求电抗\nX_L=ωL=314.16(0.10)=31.42 Ω；X_C=1/(ωC)=1/[314.16(200×10⁻⁶)]≈15.92 Ω。\n\n第 3 步｜组合总阻抗\nZ=R+j(X_L-X_C)=20+j(31.42-15.92)=20+j15.50 Ω。虚部为正，网络整体呈感性。\n\n第 4 步｜转为极坐标并求电流\n|Z|=√(20²+15.50²)≈25.3 Ω，∠Z=tan⁻¹(15.50/20)≈37.8°。I=V/Z=(120∠0°)/(25.3∠37.8°)≈4.74∠-37.8° A。\n\n第 5 步｜相位与数量级检查\n感性网络的电流应滞后电压，因此负相角正确；120/25≈4.8 A，与计算数量级一致。\n\n结论\n选 B。",
      "Step 1 | Convert frequency to angular frequency\nω=2πf=2π(50)≈314.16 rad/s.\n\nStep 2 | Calculate reactances\nX_L=ωL=31.42 Ω and X_C=1/(ωC)≈15.92 Ω.\n\nStep 3 | Form total impedance\nZ=R+j(X_L-X_C)=20+j15.50 Ω. Its positive imaginary part means the circuit is net inductive.\n\nStep 4 | Convert to polar form and find current\n|Z|≈25.3 Ω and ∠Z≈37.8°. Therefore I=V/Z=(120∠0°)/(25.3∠37.8°)≈4.74∠-37.8° A.\n\nStep 5 | Check phase and magnitude\nCurrent must lag voltage in a net-inductive circuit, so the negative current angle is correct. Also 120/25≈4.8 A.\n\nConclusion\nChoose B.",
    ),
    rubric: {
      zh: ["1 分：角频率", "2 分：两种电抗", "1 分：直角坐标阻抗", "2 分：极坐标与相量除法", "1 分：相位和数量级检查"],
      en: ["1: angular frequency", "2: both reactances", "1: rectangular impedance", "2: polar form and phasor division", "1: phase and magnitude checks"],
    },
  },
  {
    id: "eee-7-difficulty-02",
    courseId: "eee",
    topicId: "eee-7",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion", "diagram-board"],
    question: b(
      "某单相负载的 RMS 相量为 V=230∠0° V、I=8∠-30° A，电流方向进入负载正端。哪一项给出复功率 S=P+jQ 及功率因数？",
      "A single-phase load has RMS phasors V=230∠0° V and I=8∠-30° A, with current entering the load's positive terminal. Which option gives complex power S=P+jQ and power factor?",
    ),
    options: [
      b("S=1840-j920 VA；功率因数 0.50 超前", "S=1840-j920 VA; power factor 0.50 leading"),
      b("S=920+j1594 VA；功率因数 0.866 滞后", "S=920+j1594 VA; power factor 0.866 lagging"),
      b("S≈1594+j920 VA；功率因数 0.866 滞后", "S≈1594+j920 VA; power factor 0.866 lagging"),
      b("S=1594-j920 VA；功率因数 0.866 超前", "S=1594-j920 VA; power factor 0.866 leading"),
    ],
    answer: 2,
    visual: {
      kind: "table",
      title: b("RMS 相量数据", "RMS phasor data"),
      columns: [b("相量", "Phasor"), b("幅值", "Magnitude"), b("相角", "Angle")],
      rows: [["V", "230 V", "0 deg"], ["I", "8 A", "-30 deg"]],
    },
    explanation: teach(
      "第 1 步｜选择正确的复功率定义\n使用 RMS 相量且采用被动符号约定时，S=VI*，必须对电流取共轭，而不是直接计算 VI。\n\n第 2 步｜在极坐标中计算\nI*=8∠+30° A，所以 S=(230∠0°)(8∠+30°)=1840∠30° VA。\n\n第 3 步｜转为 P+jQ\nP=1840cos30°≈1593.5 W；Q=1840sin30°=920 var。因此 S≈1594+j920 VA。\n\n第 4 步｜判断功率因数类型\n功率因数 PF=P/|S|=cos30°≈0.866。电流相位 -30°，即电流滞后电压，所以是 0.866 滞后。\n\n第 5 步｜物理检查\nQ>0 对应感性、滞后负载；视在功率 |S|=VI=1840 VA，且 √(P²+Q²) 应回到约 1840 VA。\n\n结论\n选 C。",
      "Step 1 | Choose the correct complex-power definition\nWith RMS phasors under the passive convention, S=VI*. The current must be conjugated; using VI directly reverses reactive-power sign.\n\nStep 2 | Calculate in polar form\nI*=8∠+30° A, so S=(230∠0°)(8∠+30°)=1840∠30° VA.\n\nStep 3 | Convert to P+jQ\nP=1840cos30°≈1593.5 W and Q=1840sin30°=920 var. Thus S≈1594+j920 VA.\n\nStep 4 | Determine power factor type\nPF=P/|S|=cos30°≈0.866. Current is at -30°, so it lags voltage: 0.866 lagging.\n\nStep 5 | Physical check\nPositive Q corresponds to an inductive lagging load. Also |S|=VI=1840 VA and √(P²+Q²) returns the same value.\n\nConclusion\nChoose C.",
    ),
    rubric: {
      zh: ["1 分：写 S=VI*", "1 分：电流共轭", "2 分：P、Q", "1 分：功率因数", "1 分：滞后与 Q 符号检查"],
      en: ["1: state S=VI*", "1: conjugate current", "2: P and Q", "1: power factor", "1: lagging and Q-sign check"],
    },
  },
  {
    id: "eee-7-difficulty-03",
    courseId: "eee",
    topicId: "eee-7",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    question: b(
      "一个 230 V RMS、50 Hz 的单相负载吸收 4.0 kW，初始功率因数为 0.80 滞后。要用并联理想电容把功率因数提高到 0.95 滞后，所需电容约为多少？假设负载有功功率不变。",
      "A 230 V RMS, 50 Hz single-phase load absorbs 4.0 kW at an initial power factor of 0.80 lagging. An ideal shunt capacitor is added to improve the power factor to 0.95 lagging, with real load power unchanged. Approximately what capacitance is required?",
    ),
    options: [
      b("约 32 μF", "About 32 μF"),
      b("约 64 μF", "About 64 μF"),
      b("约 169 μF", "About 169 μF"),
      b("约 101 μF", "About 101 μF"),
    ],
    answer: 3,
    visual: {
      kind: "table",
      title: b("功率因数校正数据", "Power-factor-correction data"),
      columns: [b("量", "Quantity"), b("值", "Value")],
      rows: [
        ["P", "4.0 kW"],
        ["V", "230 V RMS"],
        ["f", "50 Hz"],
        ["initial PF", "0.80 lagging"],
        ["target PF", "0.95 lagging"],
      ],
    },
    explanation: teach(
      "第 1 步｜把功率因数转换为无功功率\n对滞后负载，Q=P tanφ 且 φ=cos⁻¹(PF)。初始 tanφ₁=0.75，所以 Q₁=4000(0.75)=3000 var。\n\n第 2 步｜求目标无功功率\nφ₂=cos⁻¹(0.95)，tanφ₂≈0.3287。因此目标净无功 Q₂=4000(0.3287)≈1315 var，仍为正，表示仍略微滞后。\n\n第 3 步｜求电容需要补偿的无功\n电容提供负无功，所以所需大小 |Q_C|=Q₁-Q₂≈3000-1315=1685 var。\n\n第 4 步｜由电容无功求 C\n并联电容 |Q_C|=ωCV²，其中 ω=2π(50)。故 C=1685/[2π(50)(230²)]≈1.014×10⁻⁴ F≈101 μF。\n\n第 5 步｜方向和数量级检查\n电容必须提供超前无功来抵消感性滞后无功；C 若增大，无功补偿增大。约 100 μF 在 230 V、50 Hz 下产生约 1.66 kvar，与所需 1.685 kvar 同量级。\n\n结论\n选 D。",
      "Step 1 | Convert power factor to reactive power\nFor a lagging load, Q=P tanφ with φ=cos⁻¹(PF). Initially tanφ₁=0.75, so Q₁=4000(0.75)=3000 var.\n\nStep 2 | Find target reactive power\nφ₂=cos⁻¹(0.95) and tanφ₂≈0.3287. Thus target net reactive power is Q₂≈4000(0.3287)=1315 var, still positive because the target remains lagging.\n\nStep 3 | Required capacitor compensation\nA capacitor supplies negative reactive power, so |Q_C|=Q₁-Q₂≈1685 var.\n\nStep 4 | Calculate capacitance\nFor a shunt capacitor, |Q_C|=ωCV² and ω=2π(50). Therefore C=1685/[2π(50)(230²)]≈1.014×10⁻⁴ F≈101 μF.\n\nStep 5 | Check direction and magnitude\nCapacitive leading var must cancel part of the inductive lagging var. About 100 μF at 230 V and 50 Hz produces roughly 1.66 kvar, close to the required 1.685 kvar.\n\nConclusion\nChoose D.",
    ),
    rubric: {
      zh: ["2 分：初始无功功率", "1 分：目标无功功率", "1 分：补偿无功", "2 分：由 Q_C 求 C", "1 分：方向和数量级检查"],
      en: ["2: initial reactive power", "1: target reactive power", "1: compensating var", "2: capacitance from Q_C", "1: direction and magnitude check"],
    },
  },
];
