import type { InstructorQuestion } from "./instructor-question-bank";

const b = (zh: string, en: string) => ({ zh, en });
const teach = (zh: string, en: string) => ({
  zh: `${zh}\n\n迁移自测｜改变题目中的一个关键条件（数据、符号、参数或区间），先预测答案会怎样变化，再按“检查条件 → 建立关系 → 推导 → 验证”独立重做一次。`,
  en: `${en}\n\nTransfer check | Change one key condition (a datum, sign, parameter or interval). Predict how the answer should change, then solve again using “check conditions → model the relationship → derive → verify.”`,
});

/**
 * Newly authored Mathematics 1 questions calibrated to the dependency depth,
 * representation switching and distractor quality of the teacher worksheet.
 * No wording or numerical data is copied from that worksheet.
 */
export const mathDifficultyQuestionBank: InstructorQuestion[] = [
  {
    id: "math-0-difficulty-01",
    courseId: "math",
    topicId: "math-0",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "geometric-reasoning",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "三点 A=(2,-3,4)、B=(-1,5,0)、C=(5,1,8) 构成三角形。哪一项同时正确给出三角形的分类和面积？",
      "The points A=(2,-3,4), B=(-1,5,0) and C=(5,1,8) form a triangle. Which option gives both its correct classification and area?",
    ),
    options: [
      b("等腰直角三角形，面积 30", "Isosceles right triangle, area 30"),
      b("钝角不等边三角形，面积 60", "Obtuse scalene triangle, area 60"),
      b("锐角不等边三角形，面积 30", "Acute scalene triangle, area 30"),
      b("锐角等腰三角形，面积 15", "Acute isosceles triangle, area 15"),
    ],
    answer: 2,
    visual: {
      kind: "table",
      title: b("三点坐标", "Point coordinates"),
      columns: [b("点", "Point"), b("x", "x"), b("y", "y"), b("z", "z")],
      rows: [
        ["A", "2", "-3", "4"],
        ["B", "-1", "5", "0"],
        ["C", "5", "1", "8"],
      ],
    },
    explanation: teach(
      "第 1 步｜从同一顶点建立两条边向量\nAB=B-A=(-3,8,-4)，AC=C-A=(3,4,4)，而 BC=C-B=(6,-4,8)。三角形的边长必须由这些差向量求得，不能直接使用点坐标的长度。\n\n第 2 步｜比较三边以判断是否等腰\n|AB|²=89，|AC|²=41，|BC|²=116。三个平方长度均不同，所以三角形是不等边三角形。\n\n第 3 步｜判断角的类型\n在 A 点，AB·AC=7>0；在 B 点，BA·BC=82>0；在 C 点，CA·CB=34>0。每个顶点的两条出边点积都为正，因此三个内角都小于 90°，是锐角三角形。\n\n第 4 步｜只用点积求夹角对应的面积量\n由 cosθ=(AB·AC)/(|AB||AC|) 和 sin²θ=1-cos²θ，可得 (|AB||AC|sinθ)²=|AB|²|AC|²-(AB·AC)²=89×41-7²=3600。因此以 AB、AC 为邻边的平行四边形面积为 60。\n\n第 5 步｜转成三角形面积\n三角形面积是对应平行四边形的一半，即 30。面积必须取正值，且换用其他两边计算应相同。\n\n结论\n三角形为锐角不等边三角形，面积为 30，选择 C。",
      "Step 1 | Build two side vectors from the same vertex\nAB=B-A=(-3,8,-4), AC=C-A=(3,4,4), and BC=C-B=(6,-4,8). Side lengths come from these difference vectors, not from the magnitudes of the point coordinates.\n\nStep 2 | Compare the three sides\n|AB|²=89, |AC|²=41 and |BC|²=116. Since all three squared lengths differ, the triangle is scalene.\n\nStep 3 | Classify its angles\nAt A, AB·AC=7>0; at B, BA·BC=82>0; at C, CA·CB=34>0. The two outgoing sides at every vertex have a positive dot product, so every interior angle is below 90° and the triangle is acute.\n\nStep 4 | Use only the dot product to obtain the area quantity\nFrom cosθ=(AB·AC)/(|AB||AC|) and sin²θ=1-cos²θ, (|AB||AC|sinθ)²=|AB|²|AC|²-(AB·AC)²=89×41-7²=3600. Thus the parallelogram on AB and AC has area 60.\n\nStep 5 | Convert to triangle area\nThe triangle is half of that parallelogram, so its area is 30. Area is positive and would be unchanged if another pair of sides were used.\n\nConclusion\nIt is an acute scalene triangle with area 30, so choose C.",
    ),
    rubric: {
      zh: ["2 分：三条边向量或平方长度", "2 分：不等边判断", "2 分：三个角的符号检验", "2 分：点积与面积关系", "1 分：面积与结论"],
      en: ["2: side vectors or squared lengths", "2: scalene classification", "2: sign checks at all vertices", "2: dot-product area relation", "1: area and conclusion"],
    },
  },
  {
    id: "math-0-difficulty-02",
    courseId: "math",
    topicId: "math-0",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "球面 (x-2)²+(y+1)²+(z-3)²=25 被平面 z=7 截得一个圆。该圆的圆心、半径和面积依次是什么？",
      "The sphere (x-2)²+(y+1)²+(z-3)²=25 is cut by the plane z=7. What are the centre, radius and area of the resulting circle?",
    ),
    options: [
      b("圆心 (2,-1,7)，半径 3，面积 9π", "Centre (2,-1,7), radius 3, area 9π"),
      b("圆心 (2,-1,3)，半径 4，面积 16π", "Centre (2,-1,3), radius 4, area 16π"),
      b("圆心 (2,-1,7)，半径 5，面积 25π", "Centre (2,-1,7), radius 5, area 25π"),
      b("平面与球面不相交", "The plane and sphere do not intersect"),
    ],
    answer: 0,
    explanation: teach(
      "第 1 步｜读出球心与球半径\n标准式给出球心 O=(2,-1,3)，球半径 R=5。球心不是截面圆心，因为球心不在 z=7 平面上。\n\n第 2 步｜求球心到截平面的垂直距离\n平面是水平面 z=7，所以距离 d=|7-3|=4。由于 d<R，平面确实截出一个圆，而不是相切或不相交。\n\n第 3 步｜定位截面圆心\n截面圆心是 O 在平面上的正交投影，只改变 z 坐标，因此 C=(2,-1,7)。\n\n第 4 步｜在轴截面中使用勾股定理\n球半径、截面半径 r 和距离 d 构成直角三角形：r²+d²=R²，所以 r=√(25-16)=3。\n\n第 5 步｜计算面积并检查\n圆面积为 πr²=9π。截面不经过球心，所以半径必须小于 5；结果 3 符合。\n\n结论\n圆心 (2,-1,7)、半径 3、面积 9π，选择 A。",
      "Step 1 | Read the sphere's centre and radius\nThe standard form gives O=(2,-1,3) and R=5. O is not the cross-section centre because it does not lie in z=7.\n\nStep 2 | Find the perpendicular distance to the plane\nSince z=7 is horizontal, d=|7-3|=4. Because d<R, the plane cuts a circle rather than being tangent or missing the sphere.\n\nStep 3 | Locate the cross-section centre\nThe circle centre is the orthogonal projection of O onto the plane. Only z changes, so C=(2,-1,7).\n\nStep 4 | Apply Pythagoras in an axial cross-section\nR, the section radius r and distance d form a right triangle: r²+d²=R². Thus r=√(25-16)=3.\n\nStep 5 | Find and check the area\nArea=πr²=9π. Because the cutting plane does not pass through the sphere centre, its radius must be below 5; 3 is consistent.\n\nConclusion\nThe centre is (2,-1,7), radius 3 and area 9π, so choose A.",
    ),
    rubric: {
      zh: ["1 分：球心与半径", "1 分：平面距离", "1 分：相交条件", "2 分：截面圆心与半径", "1 分：面积和检查"],
      en: ["1: sphere centre and radius", "1: plane distance", "1: intersection condition", "2: section centre and radius", "1: area and check"],
    },
  },
  {
    id: "math-0-difficulty-03",
    courseId: "math",
    topicId: "math-0",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "设 a=(t,2,-1)、b=(1,t,2)。若 a 与 b 正交，再求两向量终点间的距离 |a-b|。哪一组结果正确？",
      "Let a=(t,2,-1) and b=(1,t,2). If a is orthogonal to b, also find the distance |a-b| between their endpoints. Which pair is correct?",
    ),
    options: [
      b("t=-2/3，|a-b|=7√2/3", "t=-2/3, |a-b|=7√2/3"),
      b("t=2/3，|a-b|=√82/3", "t=2/3, |a-b|=√82/3"),
      b("t=2，|a-b|=3", "t=2, |a-b|=3"),
      b("t=2/3，|a-b|=7√2/3", "t=2/3, |a-b|=7√2/3"),
    ],
    answer: 3,
    explanation: teach(
      "第 1 步｜把正交条件翻译成点积方程\n两个非零向量正交意味着 a·b=0。这里 a·b=t×1+2t+(-1)×2=3t-2。\n\n第 2 步｜解参数并检查向量非零\n3t-2=0 给出 t=2/3。此时 a、b 显然都不是零向量，所以正交判据适用。\n\n第 3 步｜先求终点之间的差向量\na-b=(2/3-1,2-2/3,-1-2)=(-1/3,4/3,-3)。距离不是 |a|-|b|，而是差向量的长度。\n\n第 4 步｜计算三维长度\n|a-b|²=1/9+16/9+9=17/9+81/9=98/9，因此 |a-b|=√98/3=7√2/3。\n\n第 5 步｜用正交关系交叉检查\n正交时 |a-b|²=|a|²+|b|²。代 t=2/3 可得 |a|²=49/9、|b|²=49/9，总和 98/9，与上一步一致。\n\n结论\nt=2/3 且 |a-b|=7√2/3，选择 D。",
      "Step 1 | Translate orthogonality into an equation\nTwo non-zero vectors are orthogonal when a·b=0. Here a·b=t+2t-2=3t-2.\n\nStep 2 | Solve the parameter and check the condition\n3t-2=0 gives t=2/3. Both vectors are non-zero at this value, so the orthogonality test applies.\n\nStep 3 | Form the endpoint difference first\na-b=(2/3-1,2-2/3,-1-2)=(-1/3,4/3,-3). The distance is not |a|-|b|; it is the magnitude of the difference vector.\n\nStep 4 | Calculate the 3D magnitude\n|a-b|²=1/9+16/9+9=98/9, so |a-b|=√98/3=7√2/3.\n\nStep 5 | Cross-check with orthogonality\nWhen a·b=0, |a-b|²=|a|²+|b|². At t=2/3, both squared magnitudes are 49/9, giving 98/9 again.\n\nConclusion\nt=2/3 and |a-b|=7√2/3, so choose D.",
    ),
    rubric: {
      zh: ["2 分：正交方程", "1 分：参数与非零检查", "2 分：差向量", "2 分：长度化简", "1 分：正交交叉检查"],
      en: ["2: orthogonality equation", "1: parameter and non-zero check", "2: difference vector", "2: magnitude simplification", "1: orthogonal cross-check"],
    },
  },
  {
    id: "math-1-difficulty-01",
    courseId: "math",
    topicId: "math-1",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "线性系统 A(k)x=b，其中 A(k)=[[1,k,0],[0,1,k],[k,0,1]]，b=(2,-5,3)ᵀ。关于解的个数，哪项完整正确？",
      "For the linear system A(k)x=b, let A(k)=[[1,k,0],[0,1,k],[k,0,1]] and b=(2,-5,3)ᵀ. Which statement completely describes the number of solutions?",
    ),
    options: [
      b("所有实数 k 都有唯一解", "There is a unique solution for every real k"),
      b("k=-1 时无解；其余 k 有唯一解", "There is no solution at k=-1 and a unique solution otherwise"),
      b("k=-1 时有唯一解；其余 k 有无穷多解", "There is a unique solution at k=-1 and infinitely many otherwise"),
      b("k≠-1 时有唯一解；k=-1 时有无穷多解", "There is a unique solution for k≠-1 and infinitely many solutions at k=-1"),
    ],
    answer: 3,
    explanation: teach(
      "第 1 步｜先用行列式定位可能改变解数的位置\n沿第一行展开可得 det A=1+k³=(k+1)(k²-k+1)。二次因子的判别式为 -3，所以对实数 k，只有 k=-1 使行列式为零。\n\n第 2 步｜处理非奇异情形\n当 k≠-1 时 det A≠0，A 可逆，因此无论右端 b 是什么，系统都有且仅有一个解。\n\n第 3 步｜不能仅凭 det=0 就断言无解\n代 k=-1，方程为 x-y=2、y-z=-5、-x+z=3。前三个方程的左端相加为 0，右端也有 2-5+3=0，所以依赖关系相容。\n\n第 4 步｜判断自由变量个数\n在 k=-1 时，第三个方程等于前两个方程之和的相反数，只有两个独立方程、三个未知量，至少有一个自由变量，因此有无穷多解。\n\n第 5 步｜区分“奇异”与“不相容”\n奇异矩阵只说明唯一解不可能；究竟无解还是无穷多解，还必须把 b 一并检查。\n\n结论\nk≠-1 时唯一解，k=-1 时无穷多解，选择 D。",
      "Step 1 | Use the determinant to locate where the solution count may change\nExpanding gives det A=1+k³=(k+1)(k²-k+1). The quadratic has discriminant -3, so the only real singular value is k=-1.\n\nStep 2 | Handle the nonsingular case\nFor k≠-1, det A≠0 and A is invertible. Therefore the system has exactly one solution for any right-hand side b.\n\nStep 3 | Do not infer inconsistency from det=0 alone\nAt k=-1 the equations are x-y=2, y-z=-5 and -x+z=3. The left sides sum to 0 and the right sides also satisfy 2-5+3=0, so the dependency is consistent.\n\nStep 4 | Count free variables\nThe third equation is the negative of the sum of the first two. There are only two independent equations for three unknowns, leaving a free variable and therefore infinitely many solutions.\n\nStep 5 | Separate singularity from inconsistency\nA singular matrix only rules out a unique solution. The augmented right-hand side determines whether the result is no solution or infinitely many.\n\nConclusion\nThere is one solution for k≠-1 and infinitely many at k=-1, so choose D.",
    ),
    rubric: {
      zh: ["2 分：行列式因式分解", "1 分：非奇异情形", "2 分：代入 k=-1", "2 分：相容性", "1 分：自由变量与结论"],
      en: ["2: determinant factorisation", "1: nonsingular case", "2: substitute k=-1", "2: consistency", "1: free variable and conclusion"],
    },
  },
  {
    id: "math-1-difficulty-02",
    courseId: "math",
    topicId: "math-1",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "先对平面向量施加剪切 S=[[1,2],[0,1]]，再逆时针旋转 90°，R=[[0,-1],[1,0]]。点 p=(2,-1) 的最终像及复合变换对有向面积的影响是什么？",
      "A planar vector is first sheared by S=[[1,2],[0,1]], then rotated 90° counter-clockwise by R=[[0,-1],[1,0]]. What is the final image of p=(2,-1), and what happens to oriented area?",
    ),
    options: [
      b("像为 (-1,0)；面积不变但方向翻转", "Image (-1,0); area unchanged but orientation reversed"),
      b("像为 (1,0)；有向面积保持不变", "Image (1,0); oriented area is preserved"),
      b("像为 (0,1)；面积扩大 2 倍", "Image (0,1); area doubles"),
      b("像为 (4,2)；面积缩小为一半", "Image (4,2); area halves"),
    ],
    answer: 1,
    explanation: teach(
      "第 1 步｜把语言顺序翻译成矩阵顺序\n先 S 后 R 意味着最终向量是 R(Sp)，所以复合矩阵是 RS，而不是 SR。矩阵乘法的书写顺序与执行顺序相反。\n\n第 2 步｜先做剪切\nSp=(1×2+2×(-1),0×2+1×(-1))=(0,-1)。剪切改变位置，但 det S=1。\n\n第 3 步｜再做旋转\nR(0,-1)=(1,0)，所以最终像是 (1,0)。若错误计算 SRp，会得到不同结果。\n\n第 4 步｜分析面积缩放\n复合变换的行列式 det(RS)=det R·det S=1×1=1。绝对值 1 表示面积不变。\n\n第 5 步｜分析方向\n行列式为正，所以有向面积的符号也保持，坐标方向没有翻转。旋转和这个剪切都保持方向。\n\n结论\n最终像为 (1,0)，有向面积保持不变，选择 B。",
      "Step 1 | Translate the verbal order into matrix order\nFirst S and then R means R(Sp), so the composite matrix is RS, not SR. Written matrix order is opposite to execution order.\n\nStep 2 | Apply the shear\nSp=(1×2+2×(-1),0×2+1×(-1))=(0,-1). The shear changes the point, while det S=1.\n\nStep 3 | Apply the rotation\nR(0,-1)=(1,0), so the final image is (1,0). Computing SRp would produce a different result.\n\nStep 4 | Analyse area scaling\ndet(RS)=det R·det S=1×1=1. Its absolute value is 1, so area is unchanged.\n\nStep 5 | Analyse orientation\nThe determinant is positive, so oriented area also keeps its sign and orientation is not reversed. Both the rotation and this shear preserve orientation.\n\nConclusion\nThe image is (1,0) and oriented area is preserved, so choose B.",
    ),
    rubric: {
      zh: ["2 分：复合顺序 RS", "2 分：两次矩阵乘法", "1 分：最终像", "2 分：行列式乘法", "1 分：方向解释"],
      en: ["2: composite order RS", "2: both matrix multiplications", "1: final image", "2: determinant product", "1: orientation explanation"],
    },
  },
  {
    id: "math-1-difficulty-03",
    courseId: "math",
    topicId: "math-1",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "error-analysis",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "学生解 [[2,1],[5,3]]x=(4,7)ᵀ 时，把矩阵每个元素分别取倒数当作逆矩阵。哪项既指出错误又给出正确解？",
      "While solving [[2,1],[5,3]]x=(4,7)ᵀ, a student takes the reciprocal of each matrix entry as the inverse. Which option diagnoses the error and gives the correct solution?",
    ),
    options: [
      b("矩阵求逆不是逐元素取倒数；A⁻¹=[[3,-1],[-5,2]]，所以 x=(5,-6)ᵀ", "Matrix inversion is not entrywise reciprocation; A⁻¹=[[3,-1],[-5,2]], so x=(5,-6)ᵀ"),
      b("只需交换两行；解为 x=(-6,5)ᵀ", "Only swap the two rows; the solution is x=(-6,5)ᵀ"),
      b("det A=0，所以系统无解", "det A=0, so the system has no solution"),
      b("逐元素取倒数是正确的，但还应把 b 也逐元素取倒数", "Entrywise reciprocation is correct, but b must also be reciprocated"),
    ],
    answer: 0,
    explanation: teach(
      "第 1 步｜说明概念错误\n矩阵 A⁻¹ 必须满足 AA⁻¹=I；逐元素倒数通常不满足这个乘法条件。矩阵逆反转的是线性变换，不是单独反转每个数字。\n\n第 2 步｜检查是否可逆\nA=[[2,1],[5,3]] 的行列式为 2×3-1×5=1≠0，因此逆矩阵存在且系统有唯一解。\n\n第 3 步｜使用 2×2 逆矩阵公式\nA⁻¹=(1/1)[[3,-1],[-5,2]]=[[3,-1],[-5,2]]。对角元素交换，非对角元素变号，再除以行列式。\n\n第 4 步｜乘右端向量\nx=A⁻¹b=(3×4-1×7,-5×4+2×7)ᵀ=(5,-6)ᵀ。\n\n第 5 步｜代回原系统验证\n2(5)+(-6)=4，5(5)+3(-6)=7，两式均成立。这个验证同时排除了选项中的次序错误。\n\n结论\n错误在于把求逆当作逐元素运算；正确解是 (5,-6)ᵀ，选择 A。",
      "Step 1 | State the conceptual error\nA matrix inverse must satisfy AA⁻¹=I. Entrywise reciprocals generally do not satisfy this multiplication condition. The inverse reverses a linear transformation, not each number separately.\n\nStep 2 | Check invertibility\ndet A=2×3-1×5=1≠0, so an inverse exists and the system has a unique solution.\n\nStep 3 | Apply the 2×2 inverse formula\nA⁻¹=(1/1)[[3,-1],[-5,2]]=[[3,-1],[-5,2]]. Swap the diagonal entries, negate the off-diagonal entries, then divide by the determinant.\n\nStep 4 | Multiply by the right-hand side\nx=A⁻¹b=(3×4-1×7,-5×4+2×7)ᵀ=(5,-6)ᵀ.\n\nStep 5 | Substitute into the original equations\n2(5)+(-6)=4 and 5(5)+3(-6)=7. Both equations hold, also ruling out a reversed coordinate order.\n\nConclusion\nThe error is treating inversion as entrywise; the correct solution is (5,-6)ᵀ, so choose A.",
    ),
    rubric: {
      zh: ["2 分：逆矩阵定义", "1 分：行列式", "2 分：正确逆矩阵", "2 分：矩阵乘法", "1 分：代回验证"],
      en: ["2: inverse definition", "1: determinant", "2: correct inverse", "2: matrix multiplication", "1: substitution check"],
    },
  },
  {
    id: "math-2-difficulty-01",
    courseId: "math",
    topicId: "math-2",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "某设计指标为 C(q)=q²e^(-q/2)，定义域 q>0。该指标在何处取得全局最大值，最大值是多少？",
      "A design score is C(q)=q²e^(-q/2) for q>0. Where does it attain its global maximum, and what is that maximum?",
    ),
    options: [
      b("q=2，最大值 4/e", "q=2, maximum 4/e"),
      b("q=4，最大值 16/e²", "q=4, maximum 16/e²"),
      b("q=4，取得全局最小值 16/e²", "q=4, global minimum 16/e²"),
      b("函数在 q>0 上一直递增，没有最大值", "The function is increasing on q>0 and has no maximum"),
    ],
    answer: 1,
    explanation: teach(
      "第 1 步｜识别乘积与复合结构\nC 是 q² 与 e^(-q/2) 的乘积，求导时同时使用乘积法则和链式法则；指数项的内部导数是 -1/2。\n\n第 2 步｜正确求导并因式分解\nC'(q)=2qe^(-q/2)-q²e^(-q/2)/2=(q e^(-q/2)/2)(4-q)。\n\n第 3 步｜在定义域内求临界点\nq>0 且指数永远为正，所以 C'(q)=0 的定义域内解只有 q=4。因子 q=0 不在给定定义域内。\n\n第 4 步｜用符号变化分类\n当 0<q<4 时，4-q>0，C'>0；当 q>4 时，C'<0。函数先增后减，所以 q=4 是局部最大值。\n\n第 5 步｜确认是全局最大并求值\n当 q→0⁺ 时 C→0，当 q→∞ 时指数衰减压过多项式增长，也有 C→0。因此唯一的局部最大就是全局最大，C(4)=16e^-2=16/e²。\n\n结论\nq=4，最大值 16/e²，选择 B。",
      "Step 1 | Identify product and composite structure\nC is the product of q² and e^(-q/2), so use both product and chain rules. The inner derivative of the exponent is -1/2.\n\nStep 2 | Differentiate and factor\nC'(q)=2qe^(-q/2)-q²e^(-q/2)/2=(q e^(-q/2)/2)(4-q).\n\nStep 3 | Find critical points in the domain\nFor q>0 the exponential is always positive, so the only domain solution of C'=0 is q=4. The factor q=0 lies outside the stated domain.\n\nStep 4 | Classify by sign change\nFor 0<q<4, C'>0; for q>4, C'<0. The function rises then falls, making q=4 a local maximum.\n\nStep 5 | Establish globality and evaluate\nAs q→0⁺, C→0. As q→∞, exponential decay dominates polynomial growth and C→0 again. Thus the only local maximum is global, with C(4)=16e^-2=16/e².\n\nConclusion\nq=4 and the maximum is 16/e², so choose B.",
    ),
    rubric: {
      zh: ["2 分：乘积与链式法则", "2 分：导数因式分解", "1 分：定义域", "2 分：符号表", "2 分：端点极限与最大值"],
      en: ["2: product and chain rules", "2: factored derivative", "1: domain", "2: sign chart", "2: endpoint limits and maximum"],
    },
  },
  {
    id: "math-2-difficulty-02",
    courseId: "math",
    topicId: "math-2",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "表格给出等间距数据。用中心差分估计 f'(2.0) 和 f''(2.0)，并据此判断 x=2.0 附近的形状。哪项正确？",
      "The table gives equally spaced data. Use centred differences to estimate f'(2.0) and f''(2.0), then classify the shape near x=2.0. Which option is correct?",
    ),
    options: [
      b("f'≈0.1，f''≈2，是局部最小", "f'≈0.1, f''≈2, a local minimum"),
      b("f'≈-0.1，f''≈-2，是递减拐点", "f'≈-0.1, f''≈-2, a decreasing inflection point"),
      b("f'≈0，f''≈0，无法分类", "f'≈0, f''≈0, cannot classify"),
      b("f'≈0，f''≈-2，是局部最大", "f'≈0, f''≈-2, a local maximum"),
    ],
    answer: 3,
    visual: {
      kind: "table",
      title: b("函数测量值", "Measured function values"),
      columns: [b("x", "x"), b("1.8", "1.8"), b("1.9", "1.9"), b("2.0", "2.0"), b("2.1", "2.1"), b("2.2", "2.2")],
      rows: [["f(x)", "4.96", "4.99", "5.00", "4.99", "4.96"]],
    },
    explanation: teach(
      "第 1 步｜确认步长和应使用的数据\n数据等间距，h=0.1。估计 x=2.0 的导数应优先使用两侧对称的 x=1.9 与 x=2.1，而不是只用一侧。\n\n第 2 步｜中心差分估计一阶导数\nf'(2)≈[f(2.1)-f(1.9)]/(2h)=(4.99-4.99)/0.2=0。\n\n第 3 步｜中心二阶差分\nf''(2)≈[f(2.1)-2f(2.0)+f(1.9)]/h²=(4.99-10+4.99)/0.01=-0.02/0.01=-2。\n\n第 4 步｜把数值翻译成图形信息\n一阶导数约为 0 表示切线近似水平；二阶导数为负表示图形向下凹。因此该点附近是局部最大，而不是拐点。\n\n第 5 步｜用原始数据检查\n中心值 5.00 高于两侧的 4.99，且更远处降至 4.96，与局部最大和负曲率一致。\n\n结论\nf'≈0、f''≈-2，x=2.0 附近是局部最大，选择 D。",
      "Step 1 | Identify the step and relevant data\nThe spacing is h=0.1. For a derivative at x=2.0, use the symmetric values at 1.9 and 2.1 rather than a one-sided pair.\n\nStep 2 | Estimate the first derivative\nf'(2)≈[f(2.1)-f(1.9)]/(2h)=(4.99-4.99)/0.2=0.\n\nStep 3 | Estimate the second derivative\nf''(2)≈[f(2.1)-2f(2.0)+f(1.9)]/h²=(4.99-10+4.99)/0.01=-2.\n\nStep 4 | Translate the numbers into shape\nA near-zero first derivative means a nearly horizontal tangent. A negative second derivative means concave down. Together they indicate a local maximum, not an inflection point.\n\nStep 5 | Check against the raw data\nThe centre value 5.00 exceeds the neighbouring 4.99 values, and values fall further to 4.96, consistent with a local maximum and negative curvature.\n\nConclusion\nf'≈0 and f''≈-2, so x=2.0 is near a local maximum; choose D.",
    ),
    rubric: {
      zh: ["1 分：识别 h=0.1", "2 分：一阶中心差分", "2 分：二阶中心差分", "2 分：曲率分类", "1 分：数据检查"],
      en: ["1: identify h=0.1", "2: centred first difference", "2: centred second difference", "2: curvature classification", "1: data check"],
    },
  },
  {
    id: "math-2-difficulty-03",
    courseId: "math",
    topicId: "math-2",
    kind: "multiple",
    difficulty: "instructor",
    responseMode: "multi-select",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 7,
    answerTools: ["diagram-board"],
    question: b(
      "设 f(x)=|x-1|(x+2)。多选：关于 x=1 的哪些陈述正确？",
      "Let f(x)=|x-1|(x+2). Select every correct statement about x=1.",
    ),
    options: [
      b("f 在 x=1 连续", "f is continuous at x=1"),
      b("左导数 f'₋(1)=3", "The left derivative f'₋(1)=3"),
      b("右导数 f'₊(1)=3", "The right derivative f'₊(1)=3"),
      b("左右导数绝对值相同，所以 f 在 x=1 可导", "The one-sided derivatives have equal magnitudes, so f is differentiable at x=1"),
    ],
    answer: [0, 2],
    explanation: teach(
      "第 1 步｜先检查连续性\n绝对值函数和多项式都连续，乘积也连续；直接代入 f(1)=0。因此 A 正确，但连续本身不保证可导。\n\n第 2 步｜写出左侧分段表达式\n当 x<1 时，|x-1|=1-x，所以 f=(1-x)(x+2)=-x²-x+2，导数为 -2x-1。于是 f'₋(1)=-3，B 错误。\n\n第 3 步｜写出右侧分段表达式\n当 x>1 时，|x-1|=x-1，所以 f=(x-1)(x+2)=x²+x-2，导数为 2x+1。于是 f'₊(1)=3，C 正确。\n\n第 4 步｜使用可导的真正条件\n可导要求左右导数作为带符号的数相等，而不是绝对值相等。这里 -3≠3，所以 x=1 处不可导，D 错误。\n\n第 5 步｜几何解释\n图像在 x=1 连续相接，但斜率从 -3 跳到 3，形成尖角。这正是“连续但不可导”的典型边界情形。\n\n结论\n选择 A、C。",
      "Step 1 | Check continuity first\nBoth the absolute-value function and polynomial are continuous, so their product is continuous, with f(1)=0. A is correct, but continuity alone does not imply differentiability.\n\nStep 2 | Write the left-hand branch\nFor x<1, |x-1|=1-x, so f=(1-x)(x+2)=-x²-x+2 and f'=-2x-1. Thus f'₋(1)=-3, making B false.\n\nStep 3 | Write the right-hand branch\nFor x>1, |x-1|=x-1, so f=(x-1)(x+2)=x²+x-2 and f'=2x+1. Hence f'₊(1)=3, so C is correct.\n\nStep 4 | Apply the actual differentiability condition\nDifferentiability requires the signed one-sided derivatives to be equal, not merely equal in magnitude. Since -3≠3, f is not differentiable at 1 and D is false.\n\nStep 5 | Interpret geometrically\nThe graph joins continuously at x=1, but the slope jumps from -3 to 3, creating a corner. This is a standard continuous-but-not-differentiable boundary case.\n\nConclusion\nSelect A and C.",
    ),
    rubric: {
      zh: ["1 分：连续性", "2 分：左侧分段与导数", "2 分：右侧分段与导数", "2 分：可导条件", "1 分：尖角解释"],
      en: ["1: continuity", "2: left branch and derivative", "2: right branch and derivative", "2: differentiability condition", "1: corner interpretation"],
    },
  },
  {
    id: "math-3-difficulty-01",
    courseId: "math",
    topicId: "math-3",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "曲线 x²+xy+2y²=8 经过点 (2,1)。该点的切线和法线方程分别是什么？",
      "The curve x²+xy+2y²=8 passes through (2,1). What are the tangent and normal equations there?",
    ),
    options: [
      b("切线 5x+6y=16；法线 6x-5y=7", "Tangent 5x+6y=16; normal 6x-5y=7"),
      b("切线 6x-5y=7；法线 5x+6y=16", "Tangent 6x-5y=7; normal 5x+6y=16"),
      b("切线 5x-6y=4；法线 6x+5y=17", "Tangent 5x-6y=4; normal 6x+5y=17"),
      b("切线 y-1=(5/6)(x-2)；法线 y-1=(-6/5)(x-2)", "Tangent y-1=(5/6)(x-2); normal y-1=(-6/5)(x-2)"),
    ],
    answer: 0,
    explanation: teach(
      "第 1 步｜确认给定点确实在曲线上\n2²+2×1+2×1²=4+2+2=8。若点不满足原方程，就不能在那里求这条曲线的切线。\n\n第 2 步｜逐项隐式求导\n2x+d(xy)/dx+4y y'=0。乘积法则给 d(xy)/dx=y+xy'，所以 2x+y+(x+4y)y'=0。\n\n第 3 步｜求切线斜率\n整理得 y'=-(2x+y)/(x+4y)。在 (2,1) 处，m_t=-(4+1)/(2+4)=-5/6。\n\n第 4 步｜写切线方程\n点斜式 y-1=(-5/6)(x-2)。乘以 6 并整理，得到 5x+6y=16。\n\n第 5 步｜写法线并检查垂直关系\n法线斜率是切线斜率的负倒数 m_n=6/5。于是 y-1=(6/5)(x-2)，整理为 6x-5y=7；两斜率乘积为 -1。\n\n结论\n切线 5x+6y=16，法线 6x-5y=7，选择 A。",
      "Step 1 | Verify the point lies on the curve\n2²+2×1+2×1²=8. If the point failed the original equation, a tangent to this curve could not be found there.\n\nStep 2 | Differentiate implicitly term by term\n2x+d(xy)/dx+4yy'=0. The product rule gives d(xy)/dx=y+xy', so 2x+y+(x+4y)y'=0.\n\nStep 3 | Find the tangent slope\nRearrange to y'=-(2x+y)/(x+4y). At (2,1), m_t=-(4+1)/(2+4)=-5/6.\n\nStep 4 | Write the tangent\nUsing point-slope form, y-1=(-5/6)(x-2). Multiplying by 6 and rearranging gives 5x+6y=16.\n\nStep 5 | Write and check the normal\nThe normal slope is the negative reciprocal, m_n=6/5. Thus y-1=(6/5)(x-2), or 6x-5y=7. The two slopes multiply to -1.\n\nConclusion\nThe tangent is 5x+6y=16 and the normal is 6x-5y=7, so choose A.",
    ),
    rubric: {
      zh: ["1 分：验证点", "2 分：乘积与隐式求导", "1 分：切线斜率", "2 分：切线", "2 分：法线与检查"],
      en: ["1: verify point", "2: product and implicit differentiation", "1: tangent slope", "2: tangent", "2: normal and check"],
    },
  },
  {
    id: "math-3-difficulty-02",
    courseId: "math",
    topicId: "math-3",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board", "unit-conversion"],
    question: b(
      "一个点沿椭圆 x²/25+y²/9=1 的第一象限部分移动。当点位于 x=4 时，x 以 0.50 m/s 增加。此刻 y 的变化率是多少？",
      "A point moves along the first-quadrant part of x²/25+y²/9=1. When x=4, x is increasing at 0.50 m/s. What is the instantaneous rate of change of y?",
    ),
    options: [
      b("+0.40 m/s", "+0.40 m/s"),
      b("-0.50 m/s", "-0.50 m/s"),
      b("-0.40 m/s", "-0.40 m/s"),
      b("-0.80 m/s", "-0.80 m/s"),
    ],
    answer: 2,
    explanation: teach(
      "第 1 步｜先由位置约束求当前 y\n代 x=4：16/25+y²/9=1，所以 y²/9=9/25，y²=81/25。因为点在第一象限，取 y=9/5，而不是负根。\n\n第 2 步｜对时间求导\nx、y 都随时间变化，因此 (2x/25)(dx/dt)+(2y/9)(dy/dt)=0。这里不能把 y 当常数。\n\n第 3 步｜解出目标变化率\n整理得 dy/dt=-(9x/(25y))(dx/dt)。这一步也显示 x 增加时第一象限的 y 应减少。\n\n第 4 步｜代数值并保留单位\ndy/dt=-(9×4)/(25×(9/5))×0.50=-(36/45)×0.50=-0.40 m/s。\n\n第 5 步｜用几何方向检查符号\n在椭圆右上象限向右移动时必须向下，故 dy/dt 为负。若得到 +0.40，数值大小虽对但方向错误。\n\n结论\ny 以 0.40 m/s 的速率下降，即 dy/dt=-0.40 m/s，选择 C。",
      "Step 1 | Use the position constraint to find the current y\nAt x=4, 16/25+y²/9=1, so y²=81/25. The point is in the first quadrant, hence y=9/5 rather than the negative root.\n\nStep 2 | Differentiate with respect to time\nBoth x and y vary with time: (2x/25)(dx/dt)+(2y/9)(dy/dt)=0. Treating y as constant would be incorrect.\n\nStep 3 | Isolate the requested rate\ndy/dt=-(9x/(25y))(dx/dt). The minus sign already suggests that y decreases as x increases in the first quadrant.\n\nStep 4 | Substitute values and retain units\ndy/dt=-(9×4)/(25×(9/5))×0.50=-(36/45)×0.50=-0.40 m/s.\n\nStep 5 | Check the sign geometrically\nMoving rightward on the upper-right part of an ellipse requires moving downward, so dy/dt must be negative. +0.40 has the right magnitude but wrong direction.\n\nConclusion\ny decreases at 0.40 m/s, meaning dy/dt=-0.40 m/s; choose C.",
    ),
    rubric: {
      zh: ["2 分：当前 y 与象限", "2 分：对时间隐式求导", "1 分：重排", "2 分：代入与单位", "1 分：方向检查"],
      en: ["2: current y and quadrant", "2: implicit time derivative", "1: rearrangement", "2: substitution and units", "1: direction check"],
    },
  },
  {
    id: "math-3-difficulty-03",
    courseId: "math",
    topicId: "math-3",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "error-analysis",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "曲线 x²y+y³=10 经过 (1,2)。学生写出 y'=-2x/(x²+3y²)。哪项完整修正了错误并给出该点切线？",
      "The curve x²y+y³=10 passes through (1,2). A student writes y'=-2x/(x²+3y²). Which option fully corrects the error and gives the tangent there?",
    ),
    options: [
      b("学生漏掉 y³ 的链式因子；斜率 -4，切线 y-2=-4(x-1)", "The chain factor in y³ is missing; slope -4 and tangent y-2=-4(x-1)"),
      b("学生对 x²y 使用乘积法则时漏掉了因子 y；斜率 -4/13，切线 y-2=(-4/13)(x-1)", "The factor y was lost when applying the product rule to x²y; slope -4/13 and tangent y-2=(-4/13)(x-1)"),
      b("学生错误地使用乘积法则；正确斜率为 0，切线 y=2", "The product rule should not be used; the correct slope is 0 and tangent y=2"),
      b("公式正确；只需代入得到斜率 -2/13", "The formula is correct; substitution gives slope -2/13"),
    ],
    answer: 1,
    explanation: teach(
      "第 1 步｜确认点与原约束相容\n1²×2+2³=2+8=10，等于题目右端。先验证点在曲线上，才能讨论该点的切线。\n\n第 2 步｜辨认学生公式中的微分错误\n对 x²y 求导必须使用乘积法则：d(x²y)/dx=2xy+x²y'。学生把 2xy 错写成 2x，漏掉了因子 y；对 y³ 的导数 3y²y' 已体现在分母。\n\n第 3 步｜写出正确的一般导数\n2xy+x²y'+3y²y'=0，所以 y'=-2xy/(x²+3y²)。公式分母不为零时才能把 y' 解出来。\n\n第 4 步｜代点并写切线\n在 (1,2) 处，y'=-4/(1+12)=-4/13。点斜式为 y-2=(-4/13)(x-1)。\n\n第 5 步｜检查错误选项\n把 y 漏掉会给出 -2/13；把 3y²y' 漏掉会产生另一种错误。将斜率代回微分后的方程 4+13(-4/13)=0，验证正确。\n\n结论\n完整修正是 B。",
      "Step 1 | Verify the point against the original constraint\n1²×2+2³=10, equal to the right-hand side. A tangent at a stated point is meaningful only after confirming the point lies on the curve.\n\nStep 2 | Identify the student's differentiation error\nThe product rule gives d(x²y)/dx=2xy+x²y'. The student changed 2xy to 2x and lost the factor y. The term 3y²y' from y³ is already represented in the denominator.\n\nStep 3 | Derive the correct general formula\n2xy+x²y'+3y²y'=0, so y'=-2xy/(x²+3y²). Solving for y' requires the denominator to be non-zero.\n\nStep 4 | Substitute and write the tangent\nAt (1,2), y'=-4/(1+12)=-4/13. Point-slope form is y-2=(-4/13)(x-1).\n\nStep 5 | Check the distractors\nDropping y gives -2/13; dropping 3y²y' creates another wrong formula. Substitution into the differentiated equation gives 4+13(-4/13)=0, confirming the slope.\n\nConclusion\nOption B is the complete correction.",
    ),
    rubric: {
      zh: ["1 分：验证点", "2 分：定位乘积法则错误", "2 分：正确导数", "2 分：切线", "1 分：代回检查"],
      en: ["1: verify point", "2: locate product-rule error", "2: correct derivative", "2: tangent", "1: substitution check"],
    },
  },
  {
    id: "math-4-difficulty-01",
    courseId: "math",
    topicId: "math-4",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "粒子的速度为 v(t)=t²-4t+3（m/s），0≤t≤4。该时段的位移和行驶总距离分别是多少？",
      "A particle has velocity v(t)=t²-4t+3 m/s for 0≤t≤4. What are its displacement and total distance travelled?",
    ),
    options: [
      b("位移 4 m；总距离 4/3 m", "Displacement 4 m; total distance 4/3 m"),
      b("位移 0；总距离 4 m", "Displacement 0; total distance 4 m"),
      b("位移 4/3 m；总距离 4 m", "Displacement 4/3 m; total distance 4 m"),
      b("位移 4/3 m；总距离 4/3 m", "Displacement 4/3 m; total distance 4/3 m"),
    ],
    answer: 2,
    explanation: teach(
      "第 1 步｜区分两个目标\n位移是 ∫v(t)dt，允许正负抵消；总距离是 ∫|v(t)|dt，速度改变符号时必须分段。\n\n第 2 步｜找速度的零点和符号\nv=(t-1)(t-3)，在 t=1、3 处变号。速度在 [0,1] 为正，在 (1,3) 为负，在 (3,4] 又为正。\n\n第 3 步｜建立原函数并算位移\nF(t)=t³/3-2t²+3t。位移 F(4)-F(0)=4/3 m。\n\n第 4 步｜分段计算总距离\nF(1)=4/3，F(3)=0，F(4)=4/3。总距离=[F(1)-F(0)]-[F(3)-F(1)]+[F(4)-F(3)]=4/3+4/3+4/3=4 m。\n\n第 5 步｜合理性检查\n总距离必须不小于位移的绝对值；4≥4/3。两者不相等说明运动过程中确实发生了反向。\n\n结论\n位移 4/3 m，总距离 4 m，选择 C。",
      "Step 1 | Separate the two targets\nDisplacement is ∫v(t)dt and allows cancellation. Total distance is ∫|v(t)|dt, so intervals must be split wherever velocity changes sign.\n\nStep 2 | Find zeros and signs of velocity\nv=(t-1)(t-3), with sign changes at t=1 and 3. It is positive on [0,1], negative on (1,3), then positive on (3,4].\n\nStep 3 | Find an antiderivative and displacement\nF(t)=t³/3-2t²+3t. Displacement is F(4)-F(0)=4/3 m.\n\nStep 4 | Calculate total distance piecewise\nF(1)=4/3, F(3)=0 and F(4)=4/3. Distance=[F(1)-F(0)]-[F(3)-F(1)]+[F(4)-F(3)]=4 m.\n\nStep 5 | Check reasonableness\nTotal distance must be at least the magnitude of displacement: 4≥4/3. Their inequality confirms that the particle reversed direction.\n\nConclusion\nDisplacement is 4/3 m and total distance is 4 m, so choose C.",
    ),
    rubric: {
      zh: ["1 分：区分位移与距离", "2 分：零点与符号", "2 分：位移积分", "3 分：绝对值分段积分", "1 分：合理性检查"],
      en: ["1: distinguish displacement and distance", "2: zeros and signs", "2: displacement integral", "3: piecewise absolute-value integral", "1: reasonableness check"],
    },
  },
  {
    id: "math-4-difficulty-02",
    courseId: "math",
    topicId: "math-4",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion"],
    question: b(
      "流量 q(t)（L/min）按表格每 1 min 测量一次。用复合 Simpson 1/3 法估计 0≤t≤4 min 流入的体积。哪项正确？",
      "Flow q(t), in L/min, is measured every 1 min as shown. Use the composite Simpson 1/3 rule to estimate the volume entering over 0≤t≤4 min. Which option is correct?",
    ),
    options: [
      b("20 L", "20 L"),
      b("67/3 L≈22.33 L", "67/3 L≈22.33 L"),
      b("22.5 L", "22.5 L"),
      b("67/3 L/min", "67/3 L/min"),
    ],
    answer: 1,
    visual: {
      kind: "table",
      title: b("流量测量", "Flow measurements"),
      columns: [b("t (min)", "t (min)"), b("0", "0"), b("1", "1"), b("2", "2"), b("3", "3"), b("4", "4")],
      rows: [["q(t) (L/min)", "2", "4", "9", "7", "3"]],
    },
    explanation: teach(
      "第 1 步｜检查 Simpson 法适用条件\n区间 [0,4] 被分成 4 个等宽子区间，h=1 min，子区间数为偶数，因此复合 Simpson 1/3 法适用。\n\n第 2 步｜写正确的权重模式\n五个数据点的权重依次是 1,4,2,4,1。端点只算一次，奇数编号内点乘 4，偶数编号内点乘 2。\n\n第 3 步｜代入数据\nV≈(h/3)[q₀+4q₁+2q₂+4q₃+q₄]=(1/3)[2+4(4)+2(9)+4(7)+3]。\n\n第 4 步｜计算\n括号内为 2+16+18+28+3=67，所以 V≈67/3 L≈22.33 L。\n\n第 5 步｜检查单位和干扰项\n(L/min)×min=L，所以结果是体积。22.5 L 是梯形法结果；67/3 L/min 保留了错误的流量单位。\n\n结论\n估计体积为 67/3 L，选择 B。",
      "Step 1 | Check that Simpson's rule applies\nThe interval [0,4] contains four equal subintervals of width h=1 min. The number of subintervals is even, so composite Simpson 1/3 is applicable.\n\nStep 2 | Write the correct weight pattern\nThe five weights are 1,4,2,4,1. Endpoints occur once, odd-indexed interior points receive 4, and the even-indexed interior point receives 2.\n\nStep 3 | Substitute the data\nV≈(h/3)[q₀+4q₁+2q₂+4q₃+q₄]=(1/3)[2+4(4)+2(9)+4(7)+3].\n\nStep 4 | Calculate\nThe bracket is 2+16+18+28+3=67, so V≈67/3 L≈22.33 L.\n\nStep 5 | Check units and distractors\n(L/min)×min=L, so the result is a volume. 22.5 L is the trapezoidal estimate, while 67/3 L/min incorrectly retains a flow unit.\n\nConclusion\nThe estimated volume is 67/3 L, so choose B.",
    ),
    rubric: {
      zh: ["1 分：适用条件", "2 分：Simpson 权重", "2 分：正确代入", "1 分：计算", "2 分：单位与方法辨别"],
      en: ["1: applicability", "2: Simpson weights", "2: correct substitution", "1: arithmetic", "2: units and method distinction"],
    },
  },
  {
    id: "math-4-difficulty-03",
    courseId: "math",
    topicId: "math-4",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "error-analysis",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "学生对 ∫₁ᵉ x ln(x) dx 令 u=ln(x)，却声称积分直接变成 ∫u du。哪项给出正确方法、结果和错误原因？",
      "For ∫₁ᵉ x ln(x) dx, a student sets u=ln(x) and claims the integral becomes ∫u du. Which option gives the correct method, result and diagnosis?",
    ),
    options: [
      b("换元正确，结果 1/2", "The substitution is valid and the result is 1/2"),
      b("应令 u=x²，结果 e²/2", "Set u=x²; the result is e²/2"),
      b("积分不存在，因为 ln(1)=0", "The integral does not exist because ln(1)=0"),
      b("用分部积分，结果 (e²+1)/4；错误是 du=dx/x 并不吸收因子 x dx", "Use integration by parts, giving (e²+1)/4; the error is that du=dx/x does not absorb x dx"),
    ],
    answer: 3,
    explanation: teach(
      "第 1 步｜检查换元是否匹配整个微分因子\n若 u=ln x，则 du=dx/x，而原积分含 x dx。不能把 x dx 无条件替换为 du；实际上 dx=x du 后还会留下 x²=e^(2u)。\n\n第 2 步｜识别更合适的结构\n被积函数是代数函数 x 与对数 ln x 的乘积。令 u=ln x、dv=x dx，求导后对数变简单，适合分部积分。\n\n第 3 步｜求 du 和 v\n有 du=dx/x，v=x²/2。于是 ∫x ln x dx=(x²/2)ln x-(1/2)∫x dx=(x²/2)ln x-x²/4。\n\n第 4 步｜代上下限\n在 x=e 时得到 e²/2-e²/4=e²/4；在 x=1 时得到 0-1/4=-1/4。上限减下限为 (e²+1)/4。\n\n第 5 步｜合理性检查\n在 [1,e] 上 x ln x≥0，所以积分应为正；(e²+1)/4>0。下限处函数为零并不会使定积分不存在。\n\n结论\n应使用分部积分，结果 (e²+1)/4，选择 D。",
      "Step 1 | Test whether the substitution matches the full differential factor\nIf u=ln x, then du=dx/x, while the integral contains x dx. One cannot replace x dx by du; using dx=x du would actually leave x²=e^(2u).\n\nStep 2 | Identify the better structure\nThe integrand is a product of the algebraic function x and logarithm ln x. Taking u=ln x and dv=x dx simplifies the logarithm on differentiation, suggesting integration by parts.\n\nStep 3 | Find du and v\ndu=dx/x and v=x²/2. Therefore ∫x ln x dx=(x²/2)ln x-(1/2)∫x dx=(x²/2)ln x-x²/4.\n\nStep 4 | Apply the limits\nAt x=e the value is e²/4. At x=1 it is -1/4. Upper minus lower gives (e²+1)/4.\n\nStep 5 | Check reasonableness\nOn [1,e], x ln x≥0, so the integral must be positive; (e²+1)/4 is positive. A zero integrand at the lower endpoint does not make the integral undefined.\n\nConclusion\nUse integration by parts to obtain (e²+1)/4, so choose D.",
    ),
    rubric: {
      zh: ["2 分：指出换元不匹配", "1 分：选择分部积分", "2 分：u、dv、du、v", "2 分：原函数与上下限", "1 分：符号检查"],
      en: ["2: diagnose substitution mismatch", "1: choose integration by parts", "2: u, dv, du and v", "2: antiderivative and limits", "1: sign check"],
    },
  },
  {
    id: "math-5-difficulty-01",
    courseId: "math",
    topicId: "math-5",
    kind: "calculation",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "将 (2-2i)⁵ 化为 a+bi 的形式。哪项正确？",
      "Express (2-2i)⁵ in the form a+bi. Which option is correct?",
    ),
    options: [
      b("-128+128i", "-128+128i"),
      b("128-128i", "128-128i"),
      b("-64+64i", "-64+64i"),
      b("128+128i", "128+128i"),
    ],
    answer: 0,
    explanation: teach(
      "第 1 步｜把底数写成极坐标形式\n记 cisθ=cosθ+i sinθ。2-2i 位于第四象限，模为 √(2²+(-2)²)=2√2，主辐角为 -π/4。\n\n第 2 步｜使用 De Moivre 定理\n(2-2i)⁵=(2√2)⁵[cis(-5π/4)]。幂运算使模取五次方、辐角乘 5。\n\n第 3 步｜化简模和等价角\n(2√2)⁵=128√2，且 -5π/4 与 3π/4 同终边。因此表达式是 128√2 cis(3π/4)。\n\n第 4 步｜转回直角坐标\ncos(3π/4)=-√2/2，sin(3π/4)=√2/2。实部和虚部分别为 -128 与 128。\n\n第 5 步｜用低成本代数检查\n(2-2i)²=-8i，四次方为 -64，再乘 (2-2i) 得 -128+128i，与极坐标结果一致。\n\n结论\n(2-2i)⁵=-128+128i，选择 A。",
      "Step 1 | Convert the base to polar form\nWrite cisθ=cosθ+i sinθ. The number 2-2i lies in quadrant IV, with modulus √(2²+(-2)²)=2√2 and principal argument -π/4.\n\nStep 2 | Apply De Moivre's theorem\n(2-2i)⁵=(2√2)⁵ cis(-5π/4). Raising to a power raises the modulus and multiplies the argument.\n\nStep 3 | Simplify modulus and angle\n(2√2)⁵=128√2, and -5π/4 is coterminal with 3π/4. The expression is 128√2 cis(3π/4).\n\nStep 4 | Convert back to Cartesian form\ncos(3π/4)=-√2/2 and sin(3π/4)=√2/2, giving real and imaginary parts -128 and 128.\n\nStep 5 | Perform a low-cost algebraic check\n(2-2i)²=-8i, its fourth power is -64, and multiplying once more by 2-2i gives -128+128i.\n\nConclusion\n(2-2i)⁵=-128+128i, so choose A.",
    ),
    rubric: {
      zh: ["2 分：模与辐角", "2 分：De Moivre", "1 分：模化简", "2 分：直角坐标", "1 分：代数复核"],
      en: ["2: modulus and argument", "2: De Moivre", "1: modulus simplification", "2: Cartesian conversion", "1: algebraic check"],
    },
  },
  {
    id: "math-5-difficulty-02",
    courseId: "math",
    topicId: "math-5",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "求方程 z³=8i 的全部复数根（cisθ=cosθ+i sinθ）。哪一组完整且无重复？",
      "Find every complex root of z³=8i, where cisθ=cosθ+i sinθ. Which set is complete and contains no duplicates?",
    ),
    options: [
      b("{2cis(π/6), 2cis(π/2), 2cis(5π/6)}", "{2cis(π/6), 2cis(π/2), 2cis(5π/6)}"),
      b("{8cis(π/6), 8cis(5π/6), 8cis(3π/2)}", "{8cis(π/6), 8cis(5π/6), 8cis(3π/2)}"),
      b("{2cis(π/6), 2cis(5π/6), 2cis(3π/2)}", "{2cis(π/6), 2cis(5π/6), 2cis(3π/2)}"),
      b("{2cis(π/6), 2cis(7π/6), 2cis(11π/6)}", "{2cis(π/6), 2cis(7π/6), 2cis(11π/6)}"),
    ],
    answer: 2,
    explanation: teach(
      "第 1 步｜写出右端的全部辐角\n8i=8cis(π/2+2πn)。若只使用 π/2 而忘记 2πn，就会漏掉立方根。\n\n第 2 步｜对模开三次方\n每个根的模为 ∛8=2，而不是 8。三个根都位于半径 2 的圆上。\n\n第 3 步｜对辐角除以 3\nθ_k=(π/2+2πk)/3=π/6+2πk/3，其中 k=0,1,2 即可给出一个完整周期。\n\n第 4 步｜列出三个不同根\nk=0 得 π/6；k=1 得 5π/6；k=2 得 3π/2。三角之间相差 2π/3，因此无重复。\n\n第 5 步｜验证一个容易检查的根\n2cis(3π/2)=-2i，而 (-2i)³=8i。三个根的角间隔和模也符合三次方程应有三个根的结构。\n\n结论\n完整根集为 {2cis(π/6),2cis(5π/6),2cis(3π/2)}，选择 C。",
      "Step 1 | Include all arguments of the right-hand side\n8i=8cis(π/2+2πn). Using only π/2 and forgetting 2πn would lose cube roots.\n\nStep 2 | Take the cube root of the modulus\nEvery root has modulus ∛8=2, not 8. All three lie on the circle of radius 2.\n\nStep 3 | Divide the arguments by 3\nθ_k=(π/2+2πk)/3=π/6+2πk/3, where k=0,1,2 covers one complete cycle.\n\nStep 4 | List the distinct roots\nThe angles are π/6, 5π/6 and 3π/2. They differ by 2π/3, so none is duplicated.\n\nStep 5 | Verify an easy root\n2cis(3π/2)=-2i and (-2i)³=8i. The common modulus and equal angular spacing also match the expected three-root structure.\n\nConclusion\nThe complete set is {2cis(π/6),2cis(5π/6),2cis(3π/2)}, so choose C.",
    ),
    rubric: {
      zh: ["2 分：右端一般辐角", "1 分：根的模", "2 分：辐角公式", "2 分：三个不同根", "1 分：验证完整性"],
      en: ["2: general right-side argument", "1: root modulus", "2: argument formula", "2: three distinct roots", "1: completeness check"],
    },
  },
  {
    id: "math-5-difficulty-03",
    courseId: "math",
    topicId: "math-5",
    kind: "multiple",
    difficulty: "instructor",
    responseMode: "multi-select",
    cognitiveRole: "geometric-reasoning",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    question: b(
      "设 z=-1+√3i，w=(1-i)z。多选：哪些陈述正确？",
      "Let z=-1+√3i and w=(1-i)z. Select every correct statement.",
    ),
    options: [
      b("|w|=2√2", "|w|=2√2"),
      b("w 的主辐角是 11π/12", "The principal argument of w is 11π/12"),
      b("w=(√3+1)+(√3-1)i", "w=(√3+1)+(√3-1)i"),
      b("从 z 到 w 的变换是把模放大 √2 倍并顺时针旋转 π/4", "The transformation from z to w scales magnitude by √2 and rotates clockwise by π/4"),
    ],
    answer: [0, 3],
    explanation: teach(
      "第 1 步｜分析乘数 1-i\n1-i 的模是 √2，主辐角是 -π/4。因此乘以 1-i 会把所有复数的模乘 √2，并把辐角减 π/4，D 正确。\n\n第 2 步｜求 z 的极坐标信息\n|z|=√(1+3)=2。z 位于第二象限，参考角 π/3，所以 arg z=2π/3。\n\n第 3 步｜得到 w 的模和辐角\n|w|=√2×2=2√2，因此 A 正确。arg w=2π/3-π/4=8π/12-3π/12=5π/12，不是 11π/12，所以 B 错。\n\n第 4 步｜用代数展开检查坐标\nw=(1-i)(-1+√3i)=(√3-1)+(√3+1)i。C 把实部和虚部的 ±1 放反了。\n\n第 5 步｜象限交叉检查\n5π/12=75°，所以 w 应在第一象限，且虚部大于实部。展开结果两个分量都正，且 √3+1>√3-1，吻合。\n\n结论\n选择 A、D。",
      "Step 1 | Analyse the multiplier 1-i\nIt has modulus √2 and principal argument -π/4. Multiplication by 1-i scales every modulus by √2 and subtracts π/4 from every argument, so D is correct.\n\nStep 2 | Find the polar data for z\n|z|=√(1+3)=2. Since z is in quadrant II with reference angle π/3, arg z=2π/3.\n\nStep 3 | Obtain the modulus and argument of w\n|w|=√2×2=2√2, so A is correct. arg w=2π/3-π/4=5π/12, not 11π/12, so B is false.\n\nStep 4 | Check coordinates algebraically\nw=(1-i)(-1+√3i)=(√3-1)+(√3+1)i. Option C swaps where the +1 and -1 belong.\n\nStep 5 | Cross-check the quadrant\n5π/12=75°, so w should lie in quadrant I with imaginary part larger than real part. The expanded form satisfies both conditions.\n\nConclusion\nSelect A and D.",
    ),
    rubric: {
      zh: ["2 分：乘数的模与角", "1 分：z 的极坐标", "2 分：w 的模与角", "2 分：代数展开", "1 分：象限检查"],
      en: ["2: multiplier modulus and angle", "1: polar form of z", "2: modulus and angle of w", "2: algebraic expansion", "1: quadrant check"],
    },
  },
  {
    id: "math-6-difficulty-01",
    courseId: "math",
    topicId: "math-6",
    kind: "scenario",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "数量 y 满足 logistic 方程 dy/dt=y(6-y)，且 y(0)=2。它第一次达到 y=4 的时间是多少？",
      "A quantity y satisfies the logistic equation dy/dt=y(6-y) with y(0)=2. When does it first reach y=4?",
    ),
    options: [
      b("t=ln(2)/6", "t=ln(2)/6"),
      b("t=ln(4)/6", "t=ln(4)/6"),
      b("t=ln(4)", "t=ln(4)"),
      b("永远不会达到 4，因为 y<6", "It never reaches 4 because y<6"),
    ],
    answer: 1,
    explanation: teach(
      "第 1 步｜识别模型参数与解的形状\n方程可写为 y'=6y(1-y/6)，承载量 K=6、增长率 r=6。初值 2 介于 0 与 6 之间，所以解单调增加并趋近 6，必会经过 4。\n\n第 2 步｜写 logistic 通解\n形如 y=K/[1+Ae^(-rt)]，因此 y(t)=6/[1+Ae^(-6t)]。\n\n第 3 步｜用初始条件确定 A\n2=6/(1+A)，所以 1+A=3，A=2。于是 y=6/[1+2e^(-6t)]。\n\n第 4 步｜代入目标值并解时间\n4=6/[1+2e^(-6t)]，故 1+2e^(-6t)=3/2，2e^(-6t)=1/2，e^(-6t)=1/4。\n\n第 5 步｜取对数并检查首次性\n-6t=ln(1/4)=-ln4，所以 t=ln4/6。由于解在 0<y<6 时严格递增，这个时刻唯一，也就是第一次达到 4。\n\n结论\nt=ln(4)/6，选择 B。",
      "Step 1 | Identify the model parameters and solution shape\nWrite y'=6y(1-y/6), so carrying capacity K=6 and growth rate r=6. Since y(0)=2 lies between 0 and 6, the solution increases toward 6 and must pass through 4.\n\nStep 2 | Write the logistic solution form\ny=K/[1+Ae^(-rt)], hence y(t)=6/[1+Ae^(-6t)].\n\nStep 3 | Use the initial condition\n2=6/(1+A), so A=2. Therefore y=6/[1+2e^(-6t)].\n\nStep 4 | Substitute the target value\n4=6/[1+2e^(-6t)] gives 1+2e^(-6t)=3/2, then e^(-6t)=1/4.\n\nStep 5 | Take logarithms and check first occurrence\n-6t=ln(1/4)=-ln4, so t=ln4/6. The solution is strictly increasing while 0<y<6, making this time unique and therefore the first occurrence.\n\nConclusion\nt=ln(4)/6, so choose B.",
    ),
    rubric: {
      zh: ["2 分：模型参数与单调性", "2 分：通解形式", "1 分：初值常数", "2 分：目标方程", "2 分：对数与首次性"],
      en: ["2: model parameters and monotonicity", "2: solution form", "1: initial constant", "2: target equation", "2: logarithm and first occurrence"],
    },
  },
  {
    id: "math-6-difficulty-02",
    courseId: "math",
    topicId: "math-6",
    kind: "data",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "用显式 Euler 法、步长 h=0.5，近似求解 y'=y-x²，y(0)=1。完成两步后得到的 y(1) 是多少？",
      "Use explicit Euler with step h=0.5 for y'=y-x², y(0)=1. What approximation to y(1) is obtained after two steps?",
    ),
    options: [
      b("1.625", "1.625"),
      b("1.875", "1.875"),
      b("2.000", "2.000"),
      b("2.125", "2.125"),
    ],
    answer: 3,
    explanation: teach(
      "第 1 步｜写出 Euler 更新规则\n令 f(x,y)=y-x²。显式 Euler 法使用当前点的斜率：y_{n+1}=y_n+h f(x_n,y_n)，而不是使用下一点的未知斜率。\n\n第 2 步｜计算第一步斜率\n在 (x₀,y₀)=(0,1)，f=1-0²=1。因此 y₁=1+0.5×1=1.5，x₁=0.5。\n\n第 3 步｜重新计算第二步斜率\n在新点 (0.5,1.5)，f=1.5-(0.5)²=1.25。不能继续沿用第一步斜率 1。\n\n第 4 步｜完成第二次更新\ny₂=1.5+0.5×1.25=1.5+0.625=2.125，且 x₂=1.0。\n\n第 5 步｜解释近似的来源\nEuler 法用两段切线近似真实曲线；每一步都在区间左端取斜率。答案是数值近似，不代表精确解等于 2.125。\n\n结论\ny(1)≈2.125，选择 D。",
      "Step 1 | State the Euler update\nLet f(x,y)=y-x². Explicit Euler uses the current slope: y_{n+1}=y_n+h f(x_n,y_n), not the unknown slope at the next point.\n\nStep 2 | Compute the first slope\nAt (x₀,y₀)=(0,1), f=1. Hence y₁=1+0.5×1=1.5 and x₁=0.5.\n\nStep 3 | Recompute the second slope\nAt the new point (0.5,1.5), f=1.5-(0.5)²=1.25. Reusing the first slope would be incorrect.\n\nStep 4 | Complete the second update\ny₂=1.5+0.5×1.25=2.125, with x₂=1.0.\n\nStep 5 | Interpret the approximation\nEuler's method uses two tangent-line segments to approximate the true curve, sampling slope at each interval's left endpoint. The result is an approximation, not an exact solution claim.\n\nConclusion\ny(1)≈2.125, so choose D.",
    ),
    rubric: {
      zh: ["1 分：Euler 公式", "2 分：第一步", "2 分：第二步斜率", "2 分：第二次更新", "1 分：近似含义"],
      en: ["1: Euler formula", "2: first step", "2: second-step slope", "2: second update", "1: approximation meaning"],
    },
  },
  {
    id: "math-6-difficulty-03",
    courseId: "math",
    topicId: "math-6",
    kind: "combination",
    difficulty: "instructor",
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "diagram-board"],
    question: b(
      "初值问题 y''+4y=0，y(0)=3，y'(0)=-4。哪项同时给出正确特解和恒定量 E=y'²+4y²？",
      "For y''+4y=0 with y(0)=3 and y'(0)=-4, which option gives both the correct solution and the constant value of E=y'²+4y²?",
    ),
    options: [
      b("y=3cos(2t)-4sin(2t)，E=100", "y=3cos(2t)-4sin(2t), E=100"),
      b("y=3cos(4t)-sin(4t)，E=52", "y=3cos(4t)-sin(4t), E=52"),
      b("y=3cos(2t)-2sin(2t)，E=52", "y=3cos(2t)-2sin(2t), E=52"),
      b("y=3e^(-2t)-2e^(2t)，E=52", "y=3e^(-2t)-2e^(2t), E=52"),
    ],
    answer: 2,
    explanation: teach(
      "第 1 步｜由特征方程确定解的类型\nr²+4=0 给出 r=±2i，所以通解是 y=Acos(2t)+Bsin(2t)，不是指数增长/衰减形式。\n\n第 2 步｜使用位移初值\n代 t=0，y(0)=A=3，因此 A=3。\n\n第 3 步｜对通解求导并使用速度初值\ny'=-2A sin(2t)+2B cos(2t)。于是 y'(0)=2B=-4，得到 B=-2。\n\n第 4 步｜写出特解并直接求 E 的初始值\n特解为 y=3cos(2t)-2sin(2t)。由于 E 若恒定，可在 t=0 最快计算：E=(-4)²+4(3)²=16+36=52。\n\n第 5 步｜验证 E 的确恒定\nE'=2y'y''+8yy'=2y'(y''+4y)=0，因为微分方程给出 y''+4y=0。因此使用初始值计算 E 是有依据的。\n\n结论\ny=3cos(2t)-2sin(2t)，E=52，选择 C。",
      "Step 1 | Use the characteristic equation to identify the solution type\nr²+4=0 gives r=±2i, so y=Acos(2t)+Bsin(2t), not a growing or decaying exponential form.\n\nStep 2 | Apply the displacement initial condition\nAt t=0, y(0)=A=3, hence A=3.\n\nStep 3 | Differentiate and apply the velocity condition\ny'=-2A sin(2t)+2B cos(2t). Therefore y'(0)=2B=-4, giving B=-2.\n\nStep 4 | State the solution and evaluate E efficiently\nThe solution is y=3cos(2t)-2sin(2t). If E is constant, evaluate it at t=0: E=(-4)²+4(3)²=52.\n\nStep 5 | Prove that E is constant\nE'=2y'y''+8yy'=2y'(y''+4y)=0 because the differential equation says y''+4y=0. Thus using the initial values to find E is justified.\n\nConclusion\ny=3cos(2t)-2sin(2t) and E=52, so choose C.",
    ),
    rubric: {
      zh: ["2 分：特征根与通解", "1 分：A", "2 分：B 与导数因子", "1 分：特解", "2 分：E 的值与恒定性证明"],
      en: ["2: characteristic roots and general solution", "1: A", "2: B and derivative factor", "1: particular solution", "2: value and constancy proof of E"],
    },
  },
];
