import type { InstructorQuestion } from "./instructor-question-bank";
import type { LocalizedText } from "./topic-questions";

const b = (zh: string, en: string): LocalizedText => ({ zh, en });

type PhysicsQuestionSeed = Omit<InstructorQuestion, "difficulty" | "explanation" | "rubric"> & {
  steps: [LocalizedText, LocalizedText, LocalizedText, LocalizedText, ...LocalizedText[]];
  conclusion: LocalizedText;
  transfer: LocalizedText;
  marking?: LocalizedText[];
};

const defaultPhysicsMarking = [
  b("列出已知量、目标量和模型适用条件。", "List the givens, target and model conditions."),
  b("画图或规定正方向，并写出所用物理关系。", "Draw the situation or set a direction, then state the physical relation."),
  b("分步计算或读图，保留关键中间量、符号和单位。", "Calculate or read the graph step by step, keeping key values, signs and units."),
  b("用量纲、守恒、极限或数量级检查结果。", "Check the result using dimensions, conservation, limits or scale."),
  b("给出最终答案并解释其物理意义。", "Give the final answer and explain its physical meaning."),
];

const buildQuestion = (seed: PhysicsQuestionSeed): InstructorQuestion => {
  const { steps, conclusion, transfer, marking, ...question } = seed;
  const rubricItems = marking ?? defaultPhysicsMarking;
  return {
    ...question,
    difficulty: "instructor",
    explanation: b(
      `${steps.map((step, index) => `第 ${index + 1} 步｜${step.zh}`).join("\n\n")}\n\n结论｜${conclusion.zh}\n\n迁移检查｜${transfer.zh}`,
      `${steps.map((step, index) => `Step ${index + 1} | ${step.en}`).join("\n\n")}\n\nConclusion | ${conclusion.en}\n\nTransfer check | ${transfer.en}`,
    ),
    rubric: {
      zh: rubricItems.map((item) => item.zh),
      en: rubricItems.map((item) => item.en),
    },
  };
};

/**
 * These are newly authored questions. Their difficulty is calibrated to the
 * observed instructor style: dependent steps, diagram/data reading, sign and
 * assumption traps, and a final physical check. They are not copied Canvas
 * questions and are intentionally separate from lesson-note organisation.
 */
export const physicsDifficultyProfile = {
  label: b("教师题型难度（原创）", "Instructor-style difficulty (original)"),
  traits: [
    b("一个选择项同时检验建模、计算和解释，而不是只认公式。", "One option tests modelling, calculation and interpretation rather than formula recall alone."),
    b("图表和实验数据属于题目条件，必须先读坐标、单位和参考方向。", "Graphs and experimental data are givens; axes, units and reference directions must be read first."),
    b("后一步依赖前一步结果，并要求用量纲、极限或守恒关系复核。", "Later steps depend on earlier results and must be checked by dimensions, limits or conservation."),
    b("干扰项来自真实错误：符号、总路程/位移、百分比、有效数字和失效假设。", "Distractors come from authentic errors: signs, distance/displacement, percentages, significant figures and failed assumptions."),
  ],
};

const seeds: PhysicsQuestionSeed[] = [
  {
    id: "physics-0-difficulty-01",
    courseId: "physics",
    topicId: "physics-0",
    kind: "calculation",
    question: b(
      "汽车的速度—时间图依次连接 (0 s,4 m/s)、(6 s,16 m/s)、(10 s,16 m/s)、(15 s,−4 m/s)。0–15 s 的位移与总路程分别是多少？",
      "A car's velocity–time graph joins (0 s,4 m/s), (6 s,16 m/s), (10 s,16 m/s) and (15 s,−4 m/s). What are its displacement and total distance over 0–15 s?",
    ),
    options: [
      b("154 m；154 m", "154 m; 154 m"),
      b("154 m；158 m", "154 m; 158 m"),
      b("158 m；154 m", "158 m; 154 m"),
      b("184 m；188 m", "184 m; 188 m"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "coordinate-board", "unit-conversion"],
    learningVisual: {
      id: "motion-graph",
      points: [[0, 4], [6, 16], [10, 16], [15, -4]],
      xLabel: "t (s)",
      yLabel: "v (m/s)",
      seriesLabel: "v(t)",
      shadeBetweenX: [0, 15],
      alt: b("速度从 4 m/s 线性升至 16 m/s，保持后再线性降至 −4 m/s。", "Velocity rises linearly from 4 to 16 m/s, stays constant, then falls linearly to −4 m/s."),
      caption: b("有符号面积给位移；跨过时间轴后要把负面积的绝对值计入路程。", "Signed area gives displacement; after crossing the time axis, use the negative area's magnitude for distance."),
    },
    steps: [
      b("先读图而不是套运动学公式。速度—时间图下的有符号面积是位移；总路程则把每一块面积取绝对值。", "Read the graph before choosing equations. Signed area under a velocity–time graph is displacement; distance uses the magnitude of every area."),
      b("0–6 s 是梯形：s₁=(4+16)×6/2=60 m；6–10 s 是矩形：s₂=16×4=64 m。", "From 0–6 s the trapezoid gives s₁=(4+16)×6/2=60 m; from 6–10 s the rectangle gives s₂=16×4=64 m."),
      b("10–15 s 的速度斜率为 (−4−16)/5=−4 m/s²，故 t=14 s 时过零。该段有符号面积为 (16−4)×5/2=30 m。", "From 10–15 s the slope is (−4−16)/5=−4 m/s², so velocity crosses zero at 14 s. The segment's signed area is (16−4)×5/2=30 m."),
      b("位移为 60+64+30=154 m。路程在最后一秒要把负三角形 ½×1×4=2 m 改为正，因此最后一段路程 32+2=34 m，总路程 60+64+34=158 m。", "Displacement is 60+64+30=154 m. For distance, the final negative triangle ½×1×4=2 m counts positively, so the last segment contributes 32+2=34 m and total distance is 158 m."),
      b("检查：只在 14–15 s 倒车，因此总路程应只比位移多两倍的 2 m，即多 4 m；158−154=4，吻合。", "Check: reversal occurs only from 14–15 s, so distance should exceed displacement by twice the 2 m backward travel, namely 4 m; 158−154=4."),
    ],
    conclusion: b("位移 154 m，总路程 158 m，选 B。", "Displacement is 154 m and distance is 158 m, so B is correct."),
    transfer: b("若终点速度改为 0，位移与路程还会不同吗？先判断速度是否曾为负。", "If the final velocity were 0, would displacement and distance still differ? First decide whether velocity ever became negative."),
  },
  {
    id: "physics-0-difficulty-02",
    courseId: "physics",
    topicId: "physics-0",
    kind: "scenario",
    question: b(
      "骑车人从 t=0 起的位置为 x=5+6t（m）。公交车在同一路线上从 x=0 静止等待，到 t=2 s 才以 3 m/s² 匀加速。公交车第一次在其运动模型有效时追上骑车人的时间和位置约为？",
      "A cyclist has position x=5+6t (m) from t=0. A bus waits at x=0 and, at t=2 s, starts from rest with constant acceleration 3 m/s². When and where does the bus first catch the cyclist while its motion model is valid?",
    ),
    options: [
      b("t=0.085 s，x=5.51 m", "t=0.085 s, x=5.51 m"),
      b("t=4.00 s，x=29.0 m", "t=4.00 s, x=29.0 m"),
      b("t=7.92 s，x=52.5 m", "t=7.92 s, x=52.5 m"),
      b("t=9.92 s，x=64.5 m", "t=9.92 s, x=64.5 m"),
    ],
    answer: 2,
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "coordinate-board"],
    visual: {
      kind: "table",
      title: b("两物体的分段模型", "Piecewise motion models"),
      columns: [b("对象", "Object"), b("有效时间", "Valid time"), b("位置模型", "Position model")],
      rows: [["Cyclist", "t ≥ 0", "x=5+6t"], ["Bus", "0≤t<2", "x=0"], ["Bus", "t≥2", "x=1.5(t−2)²"]],
    },
    steps: [
      b("“追上”表示同一时刻位置相同。公交车的时钟延迟 2 s，所以不能误写成 ½at²；其运动时间是 t−2。", "Catching means equal position at the same clock time. The bus starts 2 s late, so its elapsed motion time is t−2, not t."),
      b("对 t≥2，公交车位置 x_b=½×3×(t−2)²=1.5(t−2)²；骑车人位置 x_c=5+6t。令二者相等。", "For t≥2, x_b=½×3×(t−2)²=1.5(t−2)², while x_c=5+6t. Set them equal."),
      b("展开得 1.5t²−12t+1=0，因此 t=4±√138/3，数值约为 0.085 s 与 7.915 s。二次方程出现两个代数根并不代表两个都符合物理阶段。", "Expansion gives 1.5t²−12t+1=0, so t=4±√138/3, approximately 0.085 s and 7.915 s. Two algebraic roots need not both belong to the physical phase."),
      b("公交车加速模型只在 t≥2 有效，舍去 0.085 s。代入骑车人模型：x=5+6×7.915≈52.5 m。", "The accelerating-bus model is valid only for t≥2, so reject 0.085 s. Substitute into the cyclist model: x=5+6×7.915≈52.5 m."),
      b("检查公交车运动了约 5.915 s，位置 1.5×5.915²≈52.5 m，与骑车人一致；单位也分别是 s 和 m。", "Check: the bus has moved for about 5.915 s, giving 1.5×5.915²≈52.5 m, consistent with the cyclist; units are seconds and metres."),
    ],
    conclusion: b("有效追及发生在 t≈7.92 s、x≈52.5 m，选 C。", "The valid catch occurs at t≈7.92 s and x≈52.5 m, so C is correct."),
    transfer: b("若公交车 t=2 s 时已有初速度 2 m/s，位置模型中还要增加哪一项？", "If the bus already had speed 2 m/s at t=2 s, what term must be added to its position model?"),
  },
  {
    id: "physics-0-difficulty-03",
    courseId: "physics",
    topicId: "physics-0",
    kind: "multiple",
    question: b(
      "某物体的位置数据为：t/s = 0,2,5,9；x/m = 0,6,6,−2。假设各时间段内速度恒定。选出所有正确结论。",
      "An object's position data are t/s = 0,2,5,9 and x/m = 0,6,6,−2. Assume constant velocity within each interval. Select every correct conclusion.",
    ),
    options: [
      b("0–2 s 的速度为 +3 m/s", "Velocity from 0–2 s is +3 m/s"),
      b("2–5 s 的加速度为 0，因此物体一定没有静止", "Acceleration from 2–5 s is zero, so the object cannot be at rest"),
      b("全程平均速度为 −2/9 m/s", "Average velocity over the whole interval is −2/9 m/s"),
      b("全程平均速率为 14/9 m/s", "Average speed over the whole interval is 14/9 m/s"),
    ],
    answer: [0, 2, 3],
    responseMode: "multi-select",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    visual: {
      kind: "table",
      title: b("位置—时间数据", "Position–time data"),
      columns: [b("t (s)", "t (s)"), b("x (m)", "x (m)")],
      rows: [["0", "0"], ["2", "6"], ["5", "6"], ["9", "−2"]],
    },
    steps: [
      b("逐段速度是位置—时间图的斜率。0–2 s：v=(6−0)/(2−0)=+3 m/s，所以 A 正确。", "Interval velocity is the slope of the position–time graph. From 0–2 s, v=(6−0)/(2−0)=+3 m/s, so A is correct."),
      b("2–5 s 位置保持 6 m，速度为 0；恒定的零速度对应零加速度。B 把“零加速度”误解成“非零速度”，所以错误。", "From 2–5 s position remains 6 m, so velocity is zero; constant zero velocity also has zero acceleration. B wrongly treats zero acceleration as requiring non-zero velocity."),
      b("平均速度只看总位移：Δx=−2−0=−2 m，Δt=9 s，所以 v_avg=−2/9 m/s，C 正确。", "Average velocity uses net displacement only: Δx=−2−0=−2 m over 9 s, so v_avg=−2/9 m/s and C is correct."),
      b("总路程逐段相加：|6−0|+|6−6|+|−2−6|=6+0+8=14 m，平均速率为 14/9 m/s，D 正确。", "Distance adds interval magnitudes: |6−0|+|6−6|+|−2−6|=14 m, so average speed is 14/9 m/s and D is correct."),
      b("检查：物体最终在原点左侧，平均速度应为负；但路程与平均速率不能为负。", "Check: the object ends left of the origin, so average velocity is negative, while distance and average speed cannot be negative."),
    ],
    conclusion: b("正确选项是 A、C、D。", "The correct selections are A, C and D."),
    transfer: b("若只给起点和终点，能求平均速度，但为什么不能唯一求总路程？", "If only the initial and final positions are given, why can average velocity be found but not total distance?"),
  },
  {
    id: "physics-1-difficulty-01",
    courseId: "physics",
    topicId: "physics-1",
    kind: "calculation",
    question: b(
      "金属样品质量 m=(48.6±0.2) g，体积 V=(20.0±0.5) cm³。按课程的保守规则：商的百分不确定度相加。密度应报告为？",
      "A metal sample has mass m=(48.6±0.2) g and volume V=(20.0±0.5) cm³. Using the course's conservative rule that percentage uncertainties add for a quotient, how should density be reported?",
    ),
    options: [
      b("(2.430±0.029) g/cm³", "(2.430±0.029) g/cm³"),
      b("(2.43±0.07) g/cm³", "(2.43±0.07) g/cm³"),
      b("(2.4±0.7) g/cm³", "(2.4±0.7) g/cm³"),
      b("(0.412±0.012) g/cm³", "(0.412±0.012) g/cm³"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion"],
    steps: [
      b("先写被测量关系和单位：ρ=m/V，因此中心值 ρ=48.6/20.0=2.43 g/cm³。", "State the measured relationship and units first: ρ=m/V, so the central value is 48.6/20.0=2.43 g/cm³."),
      b("把两个绝对不确定度转为相对量：Δm/m=0.2/48.6≈0.00412；ΔV/V=0.5/20.0=0.025。", "Convert both absolute uncertainties to relative form: Δm/m≈0.00412 and ΔV/V=0.025."),
      b("按题目指定的保守规则相加：Δρ/ρ≈0.00412+0.025=0.02912，即约 2.91%。", "Under the stated conservative rule, add them: Δρ/ρ≈0.02912, or about 2.91%."),
      b("恢复绝对不确定度：Δρ=2.43×0.02912≈0.0708 g/cm³，保留一位有效数字为 0.07；中心值保留到同一小数位，得 2.43±0.07。", "Return to absolute uncertainty: Δρ=2.43×0.02912≈0.0708 g/cm³, rounded to 0.07; round the central value to the same decimal place, giving 2.43±0.07."),
      b("检查：体积的 2.5% 不确定度占主导，所以最终约 2.9% 合理；不确定度绝不能直接把 0.2 与 0.5 相加。", "Check: the 2.5% volume uncertainty dominates, so about 2.9% overall is sensible; the unlike absolute uncertainties must not be added directly."),
    ],
    conclusion: b("ρ=(2.43±0.07) g/cm³，选 B。", "ρ=(2.43±0.07) g/cm³, so B is correct."),
    transfer: b("若要显著降低密度不确定度，应优先改进质量还是体积测量？比较两项相对不确定度。", "To reduce density uncertainty most, should mass or volume measurement be improved first? Compare their relative contributions."),
  },
  {
    id: "physics-1-difficulty-02",
    courseId: "physics",
    topicId: "physics-1",
    kind: "combination",
    question: b(
      "游标卡尺分辨率 0.01 cm，重复读数为 12.42、12.38、12.41、12.40、12.89 cm。哪一套处理最科学？",
      "A vernier caliper has resolution 0.01 cm. Repeated readings are 12.42, 12.38, 12.41, 12.40 and 12.89 cm. Which treatment is most scientifically defensible?",
    ),
    options: [
      b("全部平均并报告 12.50 cm，因为样本越多越好", "Average all values and report 12.50 cm because more samples are always better"),
      b("直接删除 12.89，并把不确定度写成 0.005 cm", "Delete 12.89 immediately and quote uncertainty 0.005 cm"),
      b("先检查 12.89 的记录与操作并补测；若确认异常，用其余读数报告约 (12.40±0.02) cm，并说明剔除依据", "Investigate and repeat the 12.89 reading; if confirmed anomalous, report about (12.40±0.02) cm from the others and document the exclusion"),
      b("报告 12.89 cm，因为它的小数位最多", "Report 12.89 cm because it has the most decimal places"),
    ],
    answer: 2,
    responseMode: "error-analysis",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator"],
    visual: {
      kind: "table",
      title: b("重复长度读数", "Repeated length readings"),
      columns: [b("次数", "Trial"), b("长度 (cm)", "Length (cm)")],
      rows: [["1", "12.42"], ["2", "12.38"], ["3", "12.41"], ["4", "12.40"], ["5", "12.89"]],
    },
    steps: [
      b("先看数据结构：前四次集中在 12.38–12.42 cm，第五次偏离约 0.48 cm，远大于仪器 0.01 cm 的分辨率，属于需要调查的异常信号。", "Inspect the pattern first: four readings cluster from 12.38–12.42 cm, while the fifth differs by about 0.48 cm, far beyond 0.01 cm resolution, so it requires investigation."),
      b("异常值不能因为“不喜欢”就删除。应检查单位、抄录、小数点、卡尺归零与夹持位置，并再做重复测量，留下处理记录。", "An inconvenient value cannot simply be deleted. Check units, transcription, decimal point, zeroing and placement, then repeat the measurement and document the decision."),
      b("若补测支持前四次，平均值为 (12.42+12.38+12.41+12.40)/4=12.4025 cm，约 12.40 cm。", "If repeat work supports the first four, their mean is 12.4025 cm, approximately 12.40 cm."),
      b("前四次半极差为 (12.42−12.38)/2=0.02 cm，大于半分辨率 0.005 cm，可作为本组重复性不确定度的保守估计。", "The half-range of the four is (12.42−12.38)/2=0.02 cm, larger than half-resolution 0.005 cm, so it is a conservative repeatability estimate."),
      b("检查报告格式：不确定度 0.02 cm 与中心值 12.40 cm 对齐到百分位，并附带异常值处理理由，才能让结果可审计。", "Check reporting: uncertainty 0.02 cm and central value 12.40 cm align in decimal place, and the anomaly decision is documented for auditability."),
    ],
    conclusion: b("最合理的是先调查并补测，确认后报告约 (12.40±0.02) cm，选 C。", "The defensible treatment is to investigate and repeat, then report about (12.40±0.02) cm if confirmed, so C is correct."),
    transfer: b("若补测连续得到 12.87、12.90 cm，你会把问题归因于单个异常值，还是测量条件发生了变化？", "If repeats give 12.87 and 12.90 cm, would you still call it one outlier or suspect changed measurement conditions?"),
  },
  {
    id: "physics-1-difficulty-03",
    courseId: "physics",
    topicId: "physics-1",
    kind: "data",
    question: b(
      "单摆实验的 T²–L 拟合斜率为 (4.02±0.08) s²/m。由 T²=(4π²/g)L，忽略 π 的不确定度，g 应报告为？",
      "A pendulum experiment gives a T²–L fit slope (4.02±0.08) s²/m. From T²=(4π²/g)L and neglecting uncertainty in π, how should g be reported?",
    ),
    options: [
      b("(9.82±0.20) m/s²", "(9.82±0.20) m/s²"),
      b("(9.82±0.08) m/s²", "(9.82±0.08) m/s²"),
      b("(4.02±0.20) m/s²", "(4.02±0.20) m/s²"),
      b("(39.48±0.79) m/s²", "(39.48±0.79) m/s²"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "unit-conversion"],
    visual: {
      kind: "table",
      title: b("线性化结果", "Linearised fit"),
      columns: [b("关系", "Relation"), b("拟合量", "Fit quantity")],
      rows: [["T² = mL + c", "m=(4.02±0.08) s²/m"], ["Model", "m=4π²/g"]],
    },
    steps: [
      b("从模型认出斜率，不要把 4.02 直接当 g：m_fit=4π²/g，所以 g=4π²/m_fit。", "Identify the slope from the model rather than treating 4.02 as g: m_fit=4π²/g, hence g=4π²/m_fit."),
      b("中心值 g=4π²/4.02≈9.8205 m/s²。单位检查：(无量纲)/(s²/m)=m/s²。", "The central value is g=4π²/4.02≈9.8205 m/s². Unit check: dimensionless divided by s²/m gives m/s²."),
      b("g 与斜率成反比，因此小不确定度下相对不确定度大小相同：Δg/g≈Δm/m=0.08/4.02≈0.0199。", "Because g is inversely proportional to slope, the small relative uncertainties have equal magnitude: Δg/g≈0.08/4.02≈0.0199."),
      b("Δg≈9.8205×0.0199≈0.195 m/s²，取 0.20 m/s²；中心值对齐到百分位，写成 9.82±0.20 m/s²。", "Δg≈9.8205×0.0199≈0.195 m/s², rounded to 0.20 m/s²; align the central value to give 9.82±0.20 m/s²."),
      b("检查：斜率约 2% 的不确定度应给 g 约 2% 的不确定度；0.20/9.82≈2%，吻合。", "Check: a slope uncertainty near 2% should give g uncertainty near 2%; 0.20/9.82≈2%."),
    ],
    conclusion: b("g=(9.82±0.20) m/s²，选 A。", "g=(9.82±0.20) m/s², so A is correct."),
    transfer: b("若拟合有明显非零截距，除了随机不确定度，你还应调查哪类系统误差？", "If the fit has a clear non-zero intercept, what systematic effects should be investigated beyond random uncertainty?"),
  },
  {
    id: "physics-2-difficulty-01",
    courseId: "physics",
    topicId: "physics-2",
    kind: "scenario",
    question: b(
      "要用单摆测 g，并检验 T=2π√(L/g)。哪一个课前实验计划既能检验模型又能得到 g？",
      "To measure g with a pendulum and test T=2π√(L/g), which pre-lab plan can both test the model and estimate g?",
    ),
    options: [
      b("只测一个摆长的一次周期，再直接代公式", "Measure one period once at one length and substitute directly"),
      b("改变摆球质量，保持摆长不记录；画 T 对质量图", "Change bob mass without recording length; plot T against mass"),
      b("选多个摆长，每个长度测 10 个周期并重复；保持小角度和同一摆球，画 T² 对 L，斜率求 g", "Use several lengths, time 10 periods repeatedly at each, hold small angle and bob fixed, plot T² against L and obtain g from the slope"),
      b("同时改变摆长、初始角度和摆球质量，以覆盖更多情况", "Change length, release angle and bob mass together to cover more cases"),
    ],
    answer: 2,
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board"],
    steps: [
      b("把理论式平方：T²=(4π²/g)L。这样因变量 T² 与自变量 L 应呈直线，斜率含有待测参数 g。", "Square the theory: T²=(4π²/g)L. Then dependent variable T² should be linear in independent variable L, with g encoded in the slope."),
      b("要检验关系必须使用多个 L，而不是只测一点；每次计时 10 个周期再除以 10，可降低人手启动/停止的相对反应误差。", "Testing a relationship requires several L values, not one point. Timing 10 periods and dividing by 10 reduces the relative impact of manual reaction time."),
      b("控制变量包括小释放角、同一摆球、同一悬点与计时方法。一次只改变 L，才能把 T² 的变化归因于 L。", "Control small release angle, bob, pivot and timing method. Change only L so changes in T² can be attributed to L."),
      b("拟合 T²=mL+c 后，用 g=4π²/m。截距 c 也有诊断价值：明显非零可能提示有效摆长或计时的系统偏差。", "After fitting T²=mL+c, use g=4π²/m. The intercept is diagnostic: a clear non-zero c may indicate systematic error in effective length or timing."),
      b("检查计划是否同时回答三个问题：改变什么、测量什么、用什么图判断模型。只有 C 三项都明确。", "Check whether the plan states what changes, what is measured and which graph tests the model. Only C specifies all three."),
    ],
    conclusion: b("选 C：多摆长、重复多周期、控制条件并线性化。", "Choose C: multiple lengths, repeated multi-period timing, controlled conditions and linearisation."),
    transfer: b("若大角度数据偏离直线，你应删除它们，还是把“小角度近似”写成模型有效范围并单独分析？", "If large-angle data deviate, should they simply be deleted, or treated as evidence for the small-angle model's validity range?"),
  },
  {
    id: "physics-2-difficulty-02",
    courseId: "physics",
    topicId: "physics-2",
    kind: "multiple",
    question: b(
      "学生研究斜面角度 θ 对小车加速度 a 的影响，但每个角度换了不同质量的小车，只测一次，且用手推启动。选出所有必须优先改进的地方。",
      "A student studies how ramp angle θ affects cart acceleration a, but uses a different-mass cart at every angle, measures once and starts each run with a hand push. Select every priority improvement.",
    ),
    options: [
      b("每个角度使用同一辆小车并保持表面条件一致", "Use the same cart at each angle and keep surface conditions consistent"),
      b("每个角度重复测量并报告散布或不确定度", "Repeat at each angle and report spread or uncertainty"),
      b("用可重复的释放机构代替手推", "Replace the hand push with a repeatable release mechanism"),
      b("把横轴和纵轴都换成没有单位的编号", "Replace both axes with unitless trial numbers"),
    ],
    answer: [0, 1, 2],
    responseMode: "multi-select",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 7,
    answerTools: ["diagram-board"],
    steps: [
      b("实验问题把 θ 定义为自变量、a 定义为因变量。其他会影响 a 的因素应控制，否则因果归属不清。", "The question defines θ as independent and a as dependent. Other influences on a should be controlled or causation becomes ambiguous."),
      b("换不同小车会同时改变轮轴摩擦、转动惯量等条件，即使理想滑块模型中质量会约掉，现实装置也不能假定完全相同；A 必须。", "Changing carts also changes axle friction and rotational inertia. Even if mass cancels in an ideal sliding model, real carts cannot be assumed identical, so A is required."),
      b("每点只测一次无法估计随机散布，不能判断差异是否超过噪声；重复测量与不确定度使结论可检验，因此 B 必须。", "One reading per point cannot estimate random spread or show whether differences exceed noise. Repetition and uncertainty make the claim testable, so B is required."),
      b("手推带来不可控初速度和可能的额外旋转；统一释放能让初始条件可重复，因此 C 必须。D 会丢掉物理量和单位，反而破坏分析。", "A hand push introduces uncontrolled initial speed and possibly rotation; a repeatable release controls initial conditions, so C is required. D discards physical quantities and units."),
      b("检查改进后能否公平比较：同一装置、只变角度、重复测量、相同起点和释放方式，才形成有效对照。", "Check the improved comparison: same apparatus, only angle varied, repeated measurements, same start point and release method."),
    ],
    conclusion: b("正确选项为 A、B、C。", "The correct selections are A, B and C."),
    transfer: b("若理论预测 a∝sinθ，你会直接画 a–θ 图，还是画 a–sinθ 图来检验线性？为什么？", "If theory predicts a∝sinθ, would you plot a against θ or against sinθ to test linearity, and why?"),
  },
  {
    id: "physics-2-difficulty-03",
    courseId: "physics",
    topicId: "physics-2",
    kind: "data",
    question: b(
      "传感器记录同一条件下小车加速度：1.82、1.77、1.85、1.80、1.76 m/s²。若用平均值和半极差作课前预测，应采用哪一项？",
      "A sensor records cart acceleration under identical conditions: 1.82, 1.77, 1.85, 1.80 and 1.76 m/s². Using the mean and half-range for a pre-lab prediction, which result should be used?",
    ),
    options: [
      b("(1.80±0.05) m/s²", "(1.80±0.05) m/s²"),
      b("(1.800±0.018) m/s²", "(1.800±0.018) m/s²"),
      b("(9.00±0.09) m/s²", "(9.00±0.09) m/s²"),
      b("(1.76±1.85) m/s²", "(1.76±1.85) m/s²"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator"],
    visual: {
      kind: "table",
      title: b("重复加速度", "Repeated accelerations"),
      columns: [b("试次", "Trial"), b("a (m/s²)", "a (m/s²)")],
      rows: [["1", "1.82"], ["2", "1.77"], ["3", "1.85"], ["4", "1.80"], ["5", "1.76"]],
    },
    steps: [
      b("先确认这些读数是在相同条件下的重复值，所以平均值描述中心，散布描述可重复性；不能把五个数相加后当成一次加速度。", "These are repeats under one condition, so the mean describes the centre and spread describes repeatability; their sum is not an acceleration measurement."),
      b("平均值为 (1.82+1.77+1.85+1.80+1.76)/5=9.00/5=1.80 m/s²。", "The mean is (1.82+1.77+1.85+1.80+1.76)/5=1.80 m/s²."),
      b("极差为 1.85−1.76=0.09 m/s²，半极差为 0.045 m/s²。按一位有效数字保守取 0.05 m/s²。", "The range is 1.85−1.76=0.09 m/s², so half-range is 0.045 m/s², conservatively rounded to 0.05 m/s²."),
      b("中心值的小数位与不确定度对齐，报告 1.80±0.05 m/s²。B 的 0.018 是把某种统计量凭空当不确定度，题目未指定那种规则。", "Align decimal places and report 1.80±0.05 m/s². Option B invents a different uncertainty statistic not specified in the question."),
      b("检查所有读数均落在 1.80±0.05，即 1.75–1.85 m/s² 内；边界覆盖数据。", "Check that all readings lie within 1.80±0.05, namely 1.75–1.85 m/s²; the range is covered."),
    ],
    conclusion: b("课前预测采用 (1.80±0.05) m/s²，选 A。", "Use (1.80±0.05) m/s² for the pre-lab prediction, so A is correct."),
    transfer: b("正式报告若要求标准误而非半极差，你还需要计算什么量并说明什么统计假设？", "If the formal report requires standard error rather than half-range, what quantity and statistical assumption must be added?"),
  },
  {
    id: "physics-3-difficulty-01",
    courseId: "physics",
    topicId: "physics-3",
    kind: "calculation",
    question: b(
      "5.0 kg 物块正沿 30° 斜面向上滑。沿斜面向上有 20 N 拉力，μₖ=0.20，取 g=9.8 m/s²。若规定斜面向上为正，加速度是多少？",
      "A 5.0 kg block is sliding up a 30° incline. A 20 N pull acts up the slope, μₖ=0.20 and g=9.8 m/s². Taking up the slope as positive, what is its acceleration?",
    ),
    options: [b("+0.90 m/s²", "+0.90 m/s²"), b("−0.90 m/s²", "−0.90 m/s²"), b("+2.60 m/s²", "+2.60 m/s²"), b("−2.60 m/s²", "−2.60 m/s²")],
    answer: 3,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "diagram-board", "unit-conversion"],
    learningVisual: {
      id: "free-body",
      bodyLabel: "5.0 kg",
      forces: [
        { label: "pull 20 N", vector: [20, 0], color: "#2f6fed" },
        { label: "friction", vector: [-8.49, 0], color: "#c44949" },
        { label: "normal", vector: [0, 42.4], color: "#2f8f66" },
        { label: "weight", vector: [-24.5, -42.4], color: "#7c4ac7" },
      ],
      alt: b("斜面坐标中拉力向上，重力分量和滑动摩擦力向下，支持力垂直斜面。", "In slope coordinates the pull is uphill, while gravity's component and kinetic friction are downhill; the normal is perpendicular."),
      caption: b("摩擦方向反对当前向上运动，而不是自动反对你选的正方向。", "Friction opposes the current uphill motion, not automatically the chosen positive direction."),
    },
    steps: [
      b("先隔离物块并选轴：x 沿斜面向上为正，y 垂直斜面。物块正向上滑，所以滑动摩擦沿斜面向下。", "Isolate the block and choose x uphill and y normal to the slope. Because the block is sliding uphill, kinetic friction acts downhill."),
      b("垂直斜面无加速度：N=mg cos30°=5×9.8×0.866≈42.44 N。", "There is no normal acceleration, so N=mg cos30°≈42.44 N."),
      b("滑动摩擦 fₖ=μₖN=0.20×42.44≈8.49 N，重力沿斜面分量 mg sin30°=24.5 N；二者都取负号。", "Kinetic friction is fₖ=0.20×42.44≈8.49 N, and gravity's slope component is 24.5 N; both are negative."),
      b("沿斜面列牛顿第二定律：ΣF=20−24.5−8.49=−12.99 N，a=ΣF/m=−12.99/5≈−2.60 m/s²。", "Along the slope, ΣF=20−24.5−8.49=−12.99 N, so a=ΣF/m≈−2.60 m/s²."),
      b("负加速度表示方向沿斜面向下；物块此刻仍可向上运动，只是速度正在减小。加速度方向不等于速度方向。", "Negative acceleration points downhill. The block can still be moving uphill while slowing; acceleration direction need not equal velocity direction."),
    ],
    conclusion: b("a≈−2.60 m/s²，选 D。", "a≈−2.60 m/s², so D is correct."),
    transfer: b("若物块改为沿斜面向下滑，摩擦力方向和加速度数值会怎样改变？", "If the block were sliding downhill, how would friction direction and acceleration change?"),
  },
  {
    id: "physics-3-difficulty-02",
    courseId: "physics",
    topicId: "physics-3",
    kind: "data",
    question: b(
      "质量 70 kg 的乘客站在电梯秤上，读数为 770 N，取 g=9.8 m/s²、向上为正。电梯加速度是多少？仅凭该读数能否判断电梯速度方向？",
      "A 70 kg passenger stands on a lift scale reading 770 N. Take g=9.8 m/s² and upward as positive. What is the lift acceleration, and can the direction of velocity be determined from this reading alone?",
    ),
    options: [
      b("1.20 m/s² 向上；不能判断速度方向", "1.20 m/s² upward; velocity direction cannot be determined"),
      b("1.20 m/s² 向上；一定向上运动", "1.20 m/s² upward; it must be moving upward"),
      b("1.20 m/s² 向下；一定向下运动", "1.20 m/s² downward; it must be moving downward"),
      b("11.0 m/s² 向上；不能判断速度方向", "11.0 m/s² upward; velocity direction cannot be determined"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board"],
    visual: {
      kind: "table",
      title: b("乘客受力数据", "Passenger force data"),
      columns: [b("量", "Quantity"), b("数值/方向", "Value/direction")],
      rows: [["N", "770 N up"], ["mg", "70×9.8=686 N down"], ["m", "70 kg"]],
    },
    steps: [
      b("秤读数是支持力 N，不是“质量变大”也不是合力。乘客只受向上的 N 和向下的 mg。", "The scale reads normal force N, not increased mass or net force. The passenger has upward N and downward mg."),
      b("取向上为正：ΣF=N−mg=ma。重力 mg=70×9.8=686 N。", "Taking upward positive, ΣF=N−mg=ma, with mg=686 N."),
      b("合力 770−686=84 N 向上，因此 a=84/70=1.20 m/s² 向上。", "The net force is 84 N upward, so a=84/70=1.20 m/s² upward."),
      b("加速度向上不等于速度向上：电梯可能向上加速，也可能向下运动但正在减速。单个秤读数没有速度历史。", "Upward acceleration does not imply upward velocity. The lift could accelerate upward or move downward while slowing; one scale reading contains no velocity history."),
      b("检查：N>mg，合力应向上且加速度远小于 g；1.20 m/s² 符合，11.0 m/s² 不合理。", "Check: N>mg requires upward net force and acceleration much smaller than g; 1.20 m/s² fits."),
    ],
    conclusion: b("加速度 1.20 m/s² 向上，但不能判断速度方向，选 A。", "Acceleration is 1.20 m/s² upward, but velocity direction is undetermined, so A is correct."),
    transfer: b("秤读数小于 mg 时，列出“向上运动”和“向下运动”各一种可能状态。", "When the scale reads below mg, give one possible upward-motion state and one downward-motion state."),
  },
  {
    id: "physics-3-difficulty-03",
    courseId: "physics",
    topicId: "physics-3",
    kind: "multiple",
    question: b(
      "3.0 kg 木块被 100 N 水平力压在竖直墙上，μₛ=0.40，g=9.8 m/s²，木块静止。选出所有正确结论。",
      "A 3.0 kg block is held at rest against a vertical wall by a 100 N horizontal push. μₛ=0.40 and g=9.8 m/s². Select every correct conclusion.",
    ),
    options: [
      b("墙的支持力大小为 100 N", "The wall's normal force has magnitude 100 N"),
      b("最大静摩擦力为 40 N", "Maximum static friction is 40 N"),
      b("实际静摩擦力为 40 N 向上", "The actual static friction is 40 N upward"),
      b("实际静摩擦力为 29.4 N 向上", "The actual static friction is 29.4 N upward"),
    ],
    answer: [0, 1, 3],
    responseMode: "multi-select",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board"],
    steps: [
      b("水平方向静止，墙的支持力平衡外推力，所以 N=100 N。A 正确。", "Horizontal equilibrium gives N=100 N to balance the push, so A is correct."),
      b("μₛN 给的是静摩擦上限，不是每次的实际值：fₛ,max=0.40×100=40 N。B 正确。", "μₛN is the maximum static friction, not always the actual value: fₛ,max=40 N. B is correct."),
      b("竖直方向若静止，摩擦必须平衡重力 mg=3×9.8=29.4 N，因此实际 fₛ=29.4 N 向上。D 正确。", "Vertical equilibrium requires friction to balance mg=29.4 N, so actual fₛ=29.4 N upward. D is correct."),
      b("因为所需 29.4 N 小于最大 40 N，静止状态自洽；C 把上限误当实际值，会造成竖直合力不为零。", "Because 29.4 N is below the 40 N maximum, rest is self-consistent. C mistakes the limit for the actual value and would create non-zero vertical net force."),
      b("检查极限：若推力降到 70 N，则最大静摩擦只有 28 N，小于重力，木块将下滑。", "Limit check: if the push fell to 70 N, maximum friction would be only 28 N, below weight, so the block would slide."),
    ],
    conclusion: b("正确选项是 A、B、D。", "The correct selections are A, B and D."),
    transfer: b("求刚好不下滑所需的最小水平推力，并说明此时为什么可以用 fₛ=μₛN。", "Find the minimum horizontal push that just prevents slipping and explain why fₛ=μₛN applies at that threshold."),
  },
  {
    id: "physics-4-difficulty-01",
    courseId: "physics",
    topicId: "physics-4",
    kind: "data",
    question: b(
      "无空气阻力模型预测水平抛射物在 t=0.5、1.0、1.5、2.0 s 的水平位置分别为 10、20、30、40 m；实测为 9.9、19.3、28.0、35.8 m。最合理的模型诊断是什么？",
      "A no-drag model predicts horizontal positions 10, 20, 30 and 40 m at t=0.5, 1.0, 1.5 and 2.0 s; measurements are 9.9, 19.3, 28.0 and 35.8 m. What is the best model diagnosis?",
    ),
    options: [
      b("残差随机，模型完全充分", "Residuals are random, so the model is fully adequate"),
      b("负残差随时间增大，水平阻力的遗漏越来越重要", "Negative residuals grow with time, suggesting omitted horizontal drag becomes increasingly important"),
      b("应把重力加速度改成负数来修正水平位置", "Make gravitational acceleration negative to correct horizontal position"),
      b("只删除 t=2.0 s 的数据即可证明模型", "Delete only the t=2.0 s point to prove the model"),
    ],
    answer: 1,
    responseMode: "error-analysis",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    visual: {
      kind: "table",
      title: b("水平位置：模型与数据", "Horizontal position: model and data"),
      columns: [b("t (s)", "t (s)"), b("模型 x (m)", "Model x (m)"), b("实测 x (m)", "Measured x (m)")],
      rows: [["0.5", "10.0", "9.9"], ["1.0", "20.0", "19.3"], ["1.5", "30.0", "28.0"], ["2.0", "40.0", "35.8"]],
    },
    steps: [
      b("先定义残差 r=x_data−x_model，依次为 −0.1、−0.7、−2.0、−4.2 m。", "Define residual r=x_data−x_model: −0.1, −0.7, −2.0 and −4.2 m."),
      b("残差并非在零附近随机散布，而是持续为负且绝对值随时间增加，说明模型系统性高估水平位移。", "Residuals are not random around zero; they stay negative and grow in magnitude, so the model systematically overpredicts horizontal displacement."),
      b("无阻力模型假设水平速度恒定。真实空气阻力使水平速度逐渐降低，正好产生越来越负的水平位置残差。", "The no-drag model assumes constant horizontal velocity. Real drag progressively reduces it, matching the increasingly negative position residuals."),
      b("重力符号影响竖直运动，不应拿来修补水平残差；任意删除不合模型的数据也不是模型检验。", "Gravity's sign affects vertical motion and cannot repair horizontal residuals; deleting inconvenient data is not model validation."),
      b("检查诊断是否能解释整个趋势而非单一点。空气阻力同时解释方向与随时间增强的幅度，因此 B 最有证据。", "Check whether the diagnosis explains the entire trend rather than one point. Drag explains both sign and growth, so B has the strongest evidence."),
    ],
    conclusion: b("最合理诊断是遗漏空气阻力，选 B。", "The best diagnosis is omitted air drag, so B is correct."),
    transfer: b("加入线性阻力后，你预期水平速度—时间图与无阻力水平线相比会怎样弯曲？", "With linear drag added, how should the horizontal velocity–time graph differ from the no-drag horizontal line?"),
  },
  {
    id: "physics-4-difficulty-02",
    courseId: "physics",
    topicId: "physics-4",
    kind: "calculation",
    question: b(
      "弹簧—质量系统周期假设为 T=Cmᵃkᵇ，其中 C 无量纲、[k]=M T⁻²。由量纲分析可得 a、b 为？",
      "Suppose a mass–spring period has form T=Cmᵃkᵇ, where C is dimensionless and [k]=M T⁻². What do dimensional analysis give for a and b?",
    ),
    options: [b("a=1，b=−1", "a=1, b=−1"), b("a=1/2，b=−1/2", "a=1/2, b=−1/2"), b("a=−1/2，b=1/2", "a=−1/2, b=1/2"), b("a=0，b=1/2", "a=0, b=1/2")],
    answer: 1,
    responseMode: "proof",
    cognitiveRole: "proof",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator"],
    steps: [
      b("量纲分析只比较基本量纲。左边 [T]=T¹；右边 [mᵃkᵇ]=Mᵃ(MT⁻²)ᵇ=Mᵃ⁺ᵇT⁻²ᵇ。", "Compare base dimensions: left side is T¹; right side is Mᵃ(MT⁻²)ᵇ=Mᵃ⁺ᵇT⁻²ᵇ."),
      b("质量指数必须相等：左边没有 M，所以 a+b=0。", "Mass exponents must match. The left has no M, so a+b=0."),
      b("时间指数必须相等：−2b=1，因此 b=−1/2。", "Time exponents must match: −2b=1, giving b=−1/2."),
      b("代回 a+b=0，得 a=1/2。因此 T=C√(m/k)。", "Substitute into a+b=0 to get a=1/2, hence T=C√(m/k)."),
      b("检查物理趋势：质量越大周期应更长，k 越大系统越硬、周期更短；正的 a 与负的 b 符合。量纲分析不能确定 C=2π。", "Physical check: more mass lengthens the period and a stiffer spring shortens it, matching the signs. Dimensional analysis cannot determine C=2π."),
    ],
    conclusion: b("a=1/2、b=−1/2，选 B。", "a=1/2 and b=−1/2, so B is correct."),
    transfer: b("为什么量纲正确只能排除错误模型，却不能单独证明模型正确？", "Why can dimensional consistency reject a model but not by itself prove that the model is correct?"),
  },
  {
    id: "physics-4-difficulty-03",
    courseId: "physics",
    topicId: "physics-4",
    kind: "combination",
    question: b(
      "测得阻力 F 与速度 v：v=2,4,6 m/s 时 F=1.2,4.8,10.8 N。判断最合适模型，并预测 v=8 m/s 时的 F。",
      "Measured drag data are F=1.2, 4.8 and 10.8 N at v=2, 4 and 6 m/s. Identify the better model and predict F at 8 m/s.",
    ),
    options: [
      b("F=0.60v，预测 4.8 N", "F=0.60v, predicting 4.8 N"),
      b("F=0.30v²，预测 19.2 N", "F=0.30v², predicting 19.2 N"),
      b("F=1.20+v，预测 9.2 N", "F=1.20+v, predicting 9.2 N"),
      b("数据不足，任何模型都不能比较", "There are too few data to compare any model"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator"],
    visual: {
      kind: "table",
      title: b("速度—阻力数据", "Speed–drag data"),
      columns: [b("v (m/s)", "v (m/s)"), b("F (N)", "F (N)"), b("F/v²", "F/v²")],
      rows: [["2", "1.2", "0.30"], ["4", "4.8", "0.30"], ["6", "10.8", "0.30"]],
    },
    steps: [
      b("比较候选模型要检验比例是否恒定。若 F∝v，则 F/v 应恒定；若 F∝v²，则 F/v² 应恒定。", "Compare models by testing a constant ratio. F/v should be constant for linear drag; F/v² for quadratic drag."),
      b("计算 F/v 得 0.60、1.20、1.80，并不恒定；线性模型不符合整组数据。", "F/v gives 0.60, 1.20 and 1.80, which is not constant, rejecting the linear model."),
      b("计算 F/v²：1.2/4=4.8/16=10.8/36=0.30，因此数据精确支持 F=0.30v²。", "F/v² equals 0.30 for all three points, so the data support F=0.30v²."),
      b("外推到 8 m/s：F=0.30×8²=0.30×64=19.2 N。", "At 8 m/s, F=0.30×8²=19.2 N."),
      b("检查数量级：速度从 4 加倍到 8，平方模型使阻力从 4.8 变为四倍 19.2 N；与计算一致。但外推仍假设流动状态未改变。", "Check: doubling speed from 4 to 8 should quadruple quadratic drag from 4.8 to 19.2 N. Extrapolation still assumes the flow regime is unchanged."),
    ],
    conclusion: b("最佳模型为 F=0.30v²，预测 19.2 N，选 B。", "The best model is F=0.30v², predicting 19.2 N, so B is correct."),
    transfer: b("若 8 m/s 实测仅 15 N，你会先怀疑计算，还是模型适用范围？列出一种可能的物理原因。", "If the measured force at 8 m/s were only 15 N, would you first question arithmetic or model validity? Give one physical reason."),
  },
  {
    id: "physics-5-difficulty-01",
    courseId: "physics",
    topicId: "physics-5",
    kind: "data",
    question: b(
      "弹簧实验拟合点为 (x,F)：(0.01,0.35)、(0.03,0.75)、(0.05,1.15)、(0.07,1.55)，单位分别为 m、N。直线模型的斜率与截距，以及最合理解释是？",
      "Spring data (x,F) are (0.01,0.35), (0.03,0.75), (0.05,1.15) and (0.07,1.55), in m and N. What are the line's slope and intercept, and the best interpretation?",
    ),
    options: [
      b("k=20 N/m，截距 0.15 N；存在零点偏置或预载", "k=20 N/m, intercept 0.15 N; a zero offset or preload is present"),
      b("k=25 N/m，截距 0；完全理想", "k=25 N/m, intercept 0; perfectly ideal"),
      b("k=0.20 N/m，截距 1.5 N；单位无关", "k=0.20 N/m, intercept 1.5 N; units do not matter"),
      b("k=60 N/m，截距 −0.25 N；必定是随机误差", "k=60 N/m, intercept −0.25 N; necessarily random error"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "coordinate-board", "unit-conversion"],
    visual: {
      kind: "table",
      title: b("F–x 数据", "F–x data"),
      columns: [b("x (m)", "x (m)"), b("F (N)", "F (N)")],
      rows: [["0.01", "0.35"], ["0.03", "0.75"], ["0.05", "1.15"], ["0.07", "1.55"]],
    },
    steps: [
      b("胡克定律图取 F 为纵轴、x 为横轴，斜率单位 N/m，代表弹簧常量 k。", "For Hooke's law plot F vertically against x; the slope in N/m is spring constant k."),
      b("用相距较远的点求斜率：k=(1.55−0.35)/(0.07−0.01)=1.20/0.06=20 N/m。", "Using widely separated points, k=(1.55−0.35)/(0.07−0.01)=20 N/m."),
      b("写 F=kx+c，用首点求 c=0.35−20×0.01=0.15 N；其他点代回也得到相同截距。", "Write F=kx+c. The first point gives c=0.35−20×0.01=0.15 N, confirmed by the others."),
      b("理想、正确归零且无预载的弹簧应近似过原点。稳定的非零截距更像力传感器零偏或预加载，而不是随机散布。", "An ideal correctly zeroed, unloaded spring should pass near the origin. A stable non-zero intercept suggests sensor offset or preload rather than random scatter."),
      b("检查斜率正且各相邻点 ΔF/Δx=0.40/0.02=20 N/m，一致；模型为 F≈20x+0.15。", "Check: every adjacent slope is 0.40/0.02=20 N/m, so F≈20x+0.15 consistently."),
    ],
    conclusion: b("k=20 N/m、截距 0.15 N，提示零偏或预载，选 A。", "k=20 N/m with 0.15 N intercept suggests offset or preload, so A is correct."),
    transfer: b("重新归零后若截距消失但斜率不变，哪一个参数属于装置性质、哪一个属于测量系统偏差？", "If re-zeroing removes the intercept but leaves slope unchanged, which parameter belongs to the spring and which to measurement bias?"),
  },
  {
    id: "physics-5-difficulty-02",
    courseId: "physics",
    topicId: "physics-5",
    kind: "multiple",
    question: b(
      "某线性拟合的残差随 x 为：(+0.20, 0.00, −0.20, 0.00, +0.20) 单位，且 R²=0.995。选出所有有证据支持的结论。",
      "Residuals from a linear fit, in increasing x, are (+0.20, 0.00, −0.20, 0.00, +0.20), with R²=0.995. Select every conclusion supported by the evidence.",
    ),
    options: [
      b("残差呈弯曲结构，线性模型可能漏掉二次项", "The curved residual pattern suggests a missing quadratic term"),
      b("R² 很高，所以无需再看残差", "A high R² makes residual inspection unnecessary"),
      b("应检查测量范围内是否存在系统非线性", "Systematic nonlinearity over the measured range should be investigated"),
      b("把正残差删除后模型一定正确", "Deleting positive residuals will make the model correct"),
    ],
    answer: [0, 2],
    responseMode: "multi-select",
    cognitiveRole: "error-analysis",
    estimatedMinutes: 7,
    answerTools: ["coordinate-board"],
    steps: [
      b("残差定义为 data−model。适合的随机误差应在零附近无结构散布，而不是按 x 有规律变化。", "Residual is data−model. Random error around a suitable model should scatter without structure around zero."),
      b("这里两端为正、中间为负，形成 U 形模式；这正是直线未捕捉曲率的信号，所以 A 有证据。", "Positive ends and negative middle form a U-shape, signalling curvature missed by a straight line, so A is supported."),
      b("R² 衡量解释的总体变异比例，但不能证明残差随机，也不能证明因果或模型形式正确；B 错。", "R² measures overall explained variation but cannot establish random residuals, causation or correct model form, so B is false."),
      b("系统形状应促使检查传感器非线性、理论二次项或量程效应，因此 C 正确。按符号删点会人为制造结果，D 错。", "The structure warrants checking sensor nonlinearity, a theoretical quadratic term or range effects, so C is correct. Deleting points by sign fabricates agreement, so D is false."),
      b("检查逻辑：高 R² 与结构残差可以同时存在；一个回答拟合强度，另一个回答模型是否遗漏模式。", "Check the logic: high R² and structured residuals can coexist; one measures fit strength, the other exposes missed pattern."),
    ],
    conclusion: b("正确选项为 A、C。", "The correct selections are A and C."),
    transfer: b("加入 x² 项后，怎样的残差图才会支持新模型，而不是只因为参数更多？", "After adding x², what residual pattern would support the new model beyond merely having more parameters?"),
  },
  {
    id: "physics-5-difficulty-03",
    courseId: "physics",
    topicId: "physics-5",
    kind: "calculation",
    question: b(
      "实验量满足 y=Axⁿ。观察到 x 从 1 加倍到 2 时 y 从 3 变为 12；x 从 2 加倍到 4 时 y 从 12 变为 48。n 与 A 为？",
      "An experiment follows y=Axⁿ. When x doubles from 1 to 2, y changes from 3 to 12; when x doubles from 2 to 4, y changes from 12 to 48. What are n and A?",
    ),
    options: [b("n=1，A=3", "n=1, A=3"), b("n=2，A=3", "n=2, A=3"), b("n=3，A=1.5", "n=3, A=1.5"), b("n=4，A=0.75", "n=4, A=0.75")],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "coordinate-board"],
    steps: [
      b("幂律中把 x 乘以因子 r，会把 y 乘以 rⁿ。这里 x 每次乘 2，y 每次乘 4。", "In a power law, multiplying x by r multiplies y by rⁿ. Here x doubles while y quadruples."),
      b("因此 2ⁿ=4=2²，得到 n=2。两段数据给出同一倍率，支持这个指数不是偶然。", "Thus 2ⁿ=4=2², giving n=2. Both intervals show the same factor."),
      b("代入 x=1、y=3：3=A×1²，所以 A=3。模型是 y=3x²。", "Substitute x=1, y=3: 3=A×1², so A=3 and y=3x²."),
      b("用其他点复核：x=2 给 y=3×4=12；x=4 给 y=3×16=48，全部吻合。", "Check the other points: x=2 gives 12 and x=4 gives 48, matching all data."),
      b("若用 log y=log A+n log x 作图，斜率为 n=2、截距为 log3；这提供适用于不等倍率数据的通用方法。", "On a log y versus log x plot, slope is n=2 and intercept is log3, a general method for unevenly spaced data."),
    ],
    conclusion: b("n=2、A=3，选 B。", "n=2 and A=3, so B is correct."),
    transfer: b("若 x 加倍时 y 变为原来的 1/2，n 应为多少？用 2ⁿ=1/2 推出。", "If doubling x halves y, what is n? Derive it from 2ⁿ=1/2."),
  },
  {
    id: "physics-6-difficulty-01",
    courseId: "physics",
    topicId: "physics-6",
    kind: "calculation",
    question: b(
      "绝热容器中把 0.20 kg、80°C 的水与 0.30 kg、20°C 的水混合。忽略容器热容和散热，两者比热相同，平衡温度是多少？",
      "In an insulated container, 0.20 kg of water at 80°C is mixed with 0.30 kg at 20°C. Neglect container heat capacity and losses; both have the same specific heat. What is the equilibrium temperature?",
    ),
    options: [b("32°C", "32°C"), b("44°C", "44°C"), b("50°C", "50°C"), b("60°C", "60°C")],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "unit-conversion"],
    steps: [
      b("先圈定系统：两份水在绝热容器内交换能量，外界净热量为零；热水放出的热量等于冷水吸收的热量。", "Define the system: the two water samples exchange energy in an insulated container, so heat lost by the hot water equals heat gained by the cold water."),
      b("设平衡温度 T_f。因为没有相变且比热相同，m_h c(80−T_f)=m_c c(T_f−20)，c 可约去。", "Let equilibrium temperature be T_f. With no phase change and equal c, m_hc(80−T_f)=m_cc(T_f−20), and c cancels."),
      b("代入质量：0.20(80−T_f)=0.30(T_f−20)。展开得 16−0.20T_f=0.30T_f−6。", "Substitute masses: 0.20(80−T_f)=0.30(T_f−20), giving 16−0.20T_f=0.30T_f−6."),
      b("整理：22=0.50T_f，所以 T_f=44°C。", "Rearrange: 22=0.50T_f, so T_f=44°C."),
      b("检查：44°C 位于 20 与 80 之间，并且更接近质量较大的冷水 20°C；这与能量加权一致。简单平均 50°C 会忽略质量不同。", "Check: 44°C lies between 20 and 80 and is closer to the larger cold-water mass. The simple average 50°C ignores unequal masses."),
    ],
    conclusion: b("平衡温度为 44°C，选 B。", "The equilibrium temperature is 44°C, so B is correct."),
    transfer: b("若容器也会吸热且初温 20°C，最终温度相对 44°C 会升高还是降低？先判断能量去向。", "If the container also absorbs heat and starts at 20°C, would the final temperature be above or below 44°C? Track the energy."),
  },
  {
    id: "physics-6-difficulty-02",
    courseId: "physics",
    topicId: "physics-6",
    kind: "combination",
    question: b(
      "把 0.10 kg、0°C 的冰投入 0.50 kg、30°C 的水中。绝热，c水=4180 J/(kg·K)，L_f=334 kJ/kg，忽略冰的比热。最终状态与温度约为？",
      "Place 0.10 kg of ice at 0°C into 0.50 kg of water at 30°C. The system is insulated; c_water=4180 J/(kg·K), L_f=334 kJ/kg, and ice heat capacity is neglected. What is the final state and temperature?",
    ),
    options: [
      b("仍有冰，0°C", "Some ice remains at 0°C"),
      b("冰恰好熔完，0°C", "Ice just melts, final 0°C"),
      b("冰全部熔化，约 11.7°C", "All ice melts, about 11.7°C"),
      b("冰全部熔化，30°C", "All ice melts, 30°C"),
    ],
    answer: 2,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 11,
    answerTools: ["scientific-calculator", "unit-conversion"],
    steps: [
      b("相变题先做“能否熔完”的门槛检查，不能一开始就假设所有物质共享某个非零终温。", "For a phase change, first test whether all ice can melt; do not assume a non-zero common final temperature from the start."),
      b("温水若降到 0°C 最多释放 Q_available=0.50×4180×30=62,700 J。", "Cooling the warm water to 0°C can release Q_available=0.50×4180×30=62,700 J."),
      b("熔化全部冰需要 Q_melt=0.10×334,000=33,400 J。因为 62,700>33,400 J，冰能全部熔化，且剩余 29,300 J。", "Melting all ice needs 33,400 J. Since 62,700>33,400 J, all ice melts and 29,300 J remains."),
      b("熔化后总水质量 0.60 kg，剩余能量把它从 0°C 加热：ΔT=29,300/(0.60×4180)≈11.68°C。", "After melting, 0.60 kg of water is warmed by the remaining energy: ΔT=29,300/(0.60×4180)≈11.68°C."),
      b("检查终温低于原热水 30°C 且高于相变温度 0°C；能量分阶段使用，没有把潜热和显热混在同一步。", "Check: the final temperature lies between 0°C and 30°C, and latent then sensible heating were handled in separate stages."),
    ],
    conclusion: b("冰全部熔化，终温约 11.7°C，选 C。", "All ice melts and the final temperature is about 11.7°C, so C is correct."),
    transfer: b("若冰质量增至 0.25 kg，先只做门槛比较，不必完整计算，就能判断最终是否仍有冰吗？", "If ice mass rises to 0.25 kg, can the threshold comparison alone determine whether ice remains?"),
  },
  {
    id: "physics-6-difficulty-03",
    courseId: "physics",
    topicId: "physics-6",
    kind: "multiple",
    question: b(
      "课程采用 ΔU=Q+W_on。某气体吸收 500 J 热量，同时对外做功 180 J。选出所有正确结论。",
      "The course uses ΔU=Q+W_on. A gas absorbs 500 J of heat while doing 180 J of work on the surroundings. Select every correct conclusion.",
    ),
    options: [
      b("Q=+500 J", "Q=+500 J"),
      b("W_on=+180 J", "W_on=+180 J"),
      b("ΔU=+320 J", "ΔU=+320 J"),
      b("系统内能增加", "The system's internal energy increases"),
    ],
    answer: [0, 2, 3],
    responseMode: "multi-select",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator"],
    steps: [
      b("先固定正号约定：进入系统的热量 Q 为正；外界对系统做功 W_on 为正。题目明确采用 ΔU=Q+W_on。", "Fix the sign convention: heat into the system is positive, and work done on the system is positive in ΔU=Q+W_on."),
      b("气体吸热 500 J，所以 Q=+500 J，A 正确。", "The gas absorbs 500 J, so Q=+500 J and A is correct."),
      b("气体对外做功 180 J，能量通过功离开系统，因此 W_on=−180 J；B 把“对外做功”当成“对系统做功”。", "The gas does 180 J of work on the surroundings, so work-on is −180 J; B reverses the actor."),
      b("ΔU=500+(−180)=+320 J，因此 C 正确；正号表示内能增加，所以 D 也正确。", "ΔU=500−180=+320 J, so C is correct, and the positive sign means internal energy increases, making D correct."),
      b("能量账检查：进入 500 J，其中 180 J 离开做功，余下 320 J 留作内能，收支平衡。", "Energy-account check: 500 J enters, 180 J leaves as work, and 320 J remains as internal energy."),
    ],
    conclusion: b("正确选项为 A、C、D。", "The correct selections are A, C and D."),
    transfer: b("若另一教材使用 ΔU=Q−W_by，数值结果为何不变？说明 W_by 与 W_on 的关系。", "Why is the numerical result unchanged under ΔU=Q−W_by? State the relation between W_by and W_on."),
  },
  {
    id: "physics-7-difficulty-01",
    courseId: "physics",
    topicId: "physics-7",
    kind: "calculation",
    question: b(
      "12 V 理想电源连接 4 Ω 电阻，再串联一个由 6 Ω 与 3 Ω 并联组成的网络。电源电流、3 Ω 支路电流和电源功率分别为？",
      "A 12 V ideal source feeds a 4 Ω resistor in series with a parallel combination of 6 Ω and 3 Ω. What are source current, current in the 3 Ω branch and source power?",
    ),
    options: [
      b("2.0 A；1.33 A；24 W", "2.0 A; 1.33 A; 24 W"),
      b("3.0 A；2.0 A；36 W", "3.0 A; 2.0 A; 36 W"),
      b("1.0 A；0.67 A；12 W", "1.0 A; 0.67 A; 12 W"),
      b("2.0 A；2.0 A；8 W", "2.0 A; 2.0 A; 8 W"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    steps: [
      b("先识别拓扑，不可把三个电阻全部相加。6 Ω 与 3 Ω 两端连接同一对节点，所以并联；该等效再与 4 Ω 串联。", "Identify topology before arithmetic. The 6 Ω and 3 Ω resistors share both nodes and are parallel; their equivalent is then in series with 4 Ω."),
      b("并联等效 R_p=(6×3)/(6+3)=18/9=2 Ω；总电阻 R_T=4+2=6 Ω。", "Parallel equivalent is R_p=(6×3)/(6+3)=2 Ω, and total resistance is 6 Ω."),
      b("电源电流 I=V/R_T=12/6=2.0 A。并联网络电压 V_p=IR_p=2×2=4 V。", "Source current is I=12/6=2.0 A. Voltage across the parallel section is V_p=IR_p=4 V."),
      b("3 Ω 支路电流 I₃=V_p/3=4/3≈1.33 A。电源提供功率 P=VI=12×2=24 W。", "Current in the 3 Ω branch is 4/3≈1.33 A. Source power is P=VI=24 W."),
      b("检查：6 Ω 支路电流 4/6≈0.67 A，两个支路相加 2.00 A，满足 KCL；电阻总耗散也应为 24 W。", "Check: the 6 Ω branch current is about 0.67 A; branch currents sum to 2.00 A by KCL, and resistor powers sum to 24 W."),
    ],
    conclusion: b("2.0 A、1.33 A、24 W，选 A。", "2.0 A, 1.33 A and 24 W, so A is correct."),
    transfer: b("若 3 Ω 支路断路，总电阻和电源电流分别如何变化？先重画拓扑。", "If the 3 Ω branch opens, how do total resistance and source current change? Redraw the topology first."),
  },
  {
    id: "physics-7-difficulty-02",
    courseId: "physics",
    topicId: "physics-7",
    kind: "scenario",
    question: b(
      "在一个节点，i₁=3.0 A 的参考箭头流入，i₂=1.2 A 的参考箭头流出，未知 i₃ 的参考箭头也流入。按这些参考方向，i₃ 等于多少，负号表示什么？",
      "At a node, reference current i₁=3.0 A enters, i₂=1.2 A leaves, and unknown reference current i₃ also enters. With those references, what is i₃ and what does a negative sign mean?",
    ),
    options: [
      b("+1.8 A；真实方向流入", "+1.8 A; actual direction is entering"),
      b("−1.8 A；真实方向流出", "−1.8 A; actual direction is leaving"),
      b("+4.2 A；节点积累电荷", "+4.2 A; charge accumulates at the node"),
      b("−4.2 A；电流不存在", "−4.2 A; the current does not exist"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "definition-boundary",
    estimatedMinutes: 7,
    answerTools: ["scientific-calculator", "circuit-sketch"],
    steps: [
      b("KCL 来自电荷守恒。选“流入为正、流出为负”，则节点方程为 i₁+i₃−i₂=0。", "KCL follows charge conservation. Taking entering currents positive gives i₁+i₃−i₂=0."),
      b("代入参考数值：3.0+i₃−1.2=0。", "Substitute the referenced values: 3.0+i₃−1.2=0."),
      b("解得 i₃=1.2−3.0=−1.8 A。", "Solve to get i₃=1.2−3.0=−1.8 A."),
      b("负号不是“电流错误或不存在”，而是实际方向与事先画的 i₃ 流入箭头相反，即真实有 1.8 A 流出。", "The negative sign does not mean an invalid current; it means actual direction opposes the chosen entering arrow, so 1.8 A leaves."),
      b("检查真实流量：3.0 A 流入，1.2+1.8=3.0 A 流出，节点不持续积累电荷。", "Check actual flow: 3.0 A enters and 1.2+1.8=3.0 A leaves, so charge does not accumulate."),
    ],
    conclusion: b("i₃=−1.8 A，表示真实 1.8 A 流出，选 B。", "i₃=−1.8 A, meaning 1.8 A actually leaves, so B is correct."),
    transfer: b("若你一开始把 i₃ 箭头画成流出，最终数值会变成多少？物理电流是否改变？", "If i₃ were initially drawn leaving, what numerical sign would result, and would the physical current change?"),
  },
  {
    id: "physics-7-difficulty-03",
    courseId: "physics",
    topicId: "physics-7",
    kind: "data",
    question: b(
      "未充电的 100 μF 电容通过 2.0 kΩ 电阻接到 10 V 直流源。开关闭合 0.40 s 后，电容电压和电流约为？",
      "An initially uncharged 100 μF capacitor is connected to a 10 V DC source through 2.0 kΩ. After 0.40 s, what are the capacitor voltage and current approximately?",
    ),
    options: [
      b("6.32 V；1.84 mA", "6.32 V; 1.84 mA"),
      b("8.65 V；0.677 mA", "8.65 V; 0.677 mA"),
      b("10.0 V；5.00 mA", "10.0 V; 5.00 mA"),
      b("1.35 V；4.32 mA", "1.35 V; 4.32 mA"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "circuit-sketch", "unit-conversion"],
    steps: [
      b("先统一单位：R=2000 Ω，C=100×10⁻⁶ F。时间常数 τ=RC=0.20 s，所以 0.40 s=2τ。", "Convert units: R=2000 Ω and C=100×10⁻⁶ F. The time constant τ=RC=0.20 s, so 0.40 s=2τ."),
      b("充电电压 v_C(t)=V(1−e⁻ᵗ/τ)=10(1−e⁻²)。", "Charging voltage is v_C(t)=V(1−e⁻ᵗ/τ)=10(1−e⁻²)."),
      b("e⁻²≈0.1353，所以 v_C≈10×0.8647=8.65 V。", "Since e⁻²≈0.1353, v_C≈8.65 V."),
      b("电流 i(t)=(V/R)e⁻ᵗ/τ=(10/2000)e⁻²=5.00 mA×0.1353≈0.677 mA。", "Current is i(t)=(V/R)e⁻ᵗ/τ=5.00 mA×e⁻²≈0.677 mA."),
      b("检查极限：充电过程中 v_C 应从 0 上升到 10 V，电流从 5 mA 降到 0；2τ 时两数均在正确区间。", "Limit check: during charging, v_C rises from 0 to 10 V while current falls from 5 mA to 0; both values are in range at 2τ."),
    ],
    conclusion: b("v_C≈8.65 V、i≈0.677 mA，选 B。", "v_C≈8.65 V and i≈0.677 mA, so B is correct."),
    transfer: b("若电容加倍而 R 不变，同样 0.40 s 对应多少个时间常数，电压会更高还是更低？", "If C doubles with R fixed, how many time constants is 0.40 s, and is the voltage higher or lower?"),
  },
  {
    id: "physics-8-difficulty-01",
    courseId: "physics",
    topicId: "physics-8",
    kind: "combination",
    question: b(
      "行波 y(x,t)=0.030 sin(4πt−0.5πx)，x、y 用 m，t 用 s。振幅、频率、波长、波速和传播方向分别为？",
      "For travelling wave y(x,t)=0.030 sin(4πt−0.5πx), with x,y in m and t in s, what are amplitude, frequency, wavelength, speed and direction?",
    ),
    options: [
      b("0.030 m，2 Hz，4 m，8 m/s，+x", "0.030 m, 2 Hz, 4 m, 8 m/s, +x"),
      b("0.030 m，4 Hz，0.5 m，2 m/s，−x", "0.030 m, 4 Hz, 0.5 m, 2 m/s, −x"),
      b("4π m，0.5π Hz，8 m，2 m/s，+x", "4π m, 0.5π Hz, 8 m, 2 m/s, +x"),
      b("0.030 m，2 Hz，4 m，8 m/s，−x", "0.030 m, 2 Hz, 4 m, 8 m/s, −x"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "coordinate-board", "unit-conversion"],
    steps: [
      b("与标准形式 y=A sin(ωt−kx+φ) 比较：A=0.030 m、ω=4π rad/s、k=0.5π rad/m。", "Compare with y=A sin(ωt−kx+φ): A=0.030 m, ω=4π rad/s and k=0.5π rad/m."),
      b("频率 f=ω/(2π)=4π/(2π)=2 Hz。角频率与普通频率不能直接混用。", "Frequency is f=ω/(2π)=2 Hz; angular and ordinary frequency are not interchangeable."),
      b("波长 λ=2π/k=2π/(0.5π)=4 m。", "Wavelength is λ=2π/k=4 m."),
      b("波速 v=fλ=2×4=8 m/s；也可用 ω/k 得到同值。", "Wave speed is v=fλ=8 m/s, also equal to ω/k."),
      b("保持相位 ωt−kx 不变时 x=(ω/k)t+常数，随 t 增大向 +x 移动；负号对应 +x 传播。", "Holding phase ωt−kx constant gives x=(ω/k)t+constant, which moves toward +x."),
    ],
    conclusion: b("0.030 m、2 Hz、4 m、8 m/s、+x，选 A。", "0.030 m, 2 Hz, 4 m, 8 m/s and +x, so A is correct."),
    transfer: b("若相位改为 ωt+kx，传播方向为何反转？用恒相位法而不是死记符号。", "If the phase becomes ωt+kx, why does direction reverse? Use constant-phase reasoning."),
  },
  {
    id: "physics-8-difficulty-02",
    courseId: "physics",
    topicId: "physics-8",
    kind: "calculation",
    question: b(
      "简谐运动 x(t)=0.080 cos(5t+π/3) m。t=0 时的速度与加速度分别约为？",
      "For SHM x(t)=0.080 cos(5t+π/3) m, what are velocity and acceleration at t=0?",
    ),
    options: [
      b("+0.346 m/s；−1.00 m/s²", "+0.346 m/s; −1.00 m/s²"),
      b("−0.346 m/s；−1.00 m/s²", "−0.346 m/s; −1.00 m/s²"),
      b("−0.200 m/s；+2.00 m/s²", "−0.200 m/s; +2.00 m/s²"),
      b("+0.400 m/s；+1.00 m/s²", "+0.400 m/s; +1.00 m/s²"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "coordinate-board"],
    steps: [
      b("先识别 A=0.080 m、ω=5 rad/s、相位 φ=π/3。t=0 的位置 x₀=A cosφ=0.080×0.5=0.040 m。", "Identify A=0.080 m, ω=5 rad/s and φ=π/3. At t=0, x₀=A cosφ=0.040 m."),
      b("速度是导数：v(t)=−Aω sin(ωt+φ)，负号来自 cos 的导数。", "Velocity is v(t)=−Aω sin(ωt+φ); the minus sign comes from differentiating cosine."),
      b("v₀=−0.080×5×sin(π/3)=−0.4×0.866≈−0.346 m/s。", "v₀=−0.080×5×sin(π/3)≈−0.346 m/s."),
      b("加速度可再求导，或用 SHM 关系 a=−ω²x：a₀=−25×0.040=−1.00 m/s²。", "Acceleration follows a=−ω²x, giving a₀=−25×0.040=−1.00 m/s²."),
      b("检查方向：t=0 时 x>0，回复加速度必须指向平衡点，即为负；速度也为负，说明正向端点后正在向中心运动。", "Direction check: x>0 requires negative restoring acceleration. Negative velocity means it is moving back toward equilibrium."),
    ],
    conclusion: b("v₀≈−0.346 m/s、a₀=−1.00 m/s²，选 B。", "v₀≈−0.346 m/s and a₀=−1.00 m/s², so B is correct."),
    transfer: b("在 x=0 的时刻，加速度与速度各有什么特征？用 a=−ω²x 和能量解释。", "At x=0, what are the acceleration and speed characteristics? Use a=−ω²x and energy."),
  },
  {
    id: "physics-8-difficulty-03",
    courseId: "physics",
    topicId: "physics-8",
    kind: "data",
    question: b(
      "一根两端固定、长 0.75 m 的弦上传播速度为 120 m/s。第三谐波的频率及包含端点在内的节点数是多少？",
      "A string fixed at both ends has length 0.75 m and wave speed 120 m/s. What are the third-harmonic frequency and the number of nodes including both ends?",
    ),
    options: [b("80 Hz；2 个", "80 Hz; 2"), b("160 Hz；3 个", "160 Hz; 3"), b("240 Hz；4 个", "240 Hz; 4"), b("360 Hz；6 个", "360 Hz; 6")],
    answer: 2,
    responseMode: "worked-response",
    cognitiveRole: "representation",
    estimatedMinutes: 8,
    answerTools: ["scientific-calculator", "diagram-board", "unit-conversion"],
    steps: [
      b("两端固定要求端点为节点。第 n 谐波满足 L=nλ_n/2，因此 λ_n=2L/n。", "Fixed ends are nodes. The nth harmonic satisfies L=nλ_n/2, so λ_n=2L/n."),
      b("第三谐波 λ₃=2×0.75/3=0.50 m。", "For the third harmonic, λ₃=2×0.75/3=0.50 m."),
      b("频率 f₃=v/λ₃=120/0.50=240 Hz；等价地 f₁=v/(2L)=80 Hz，再乘 3。", "Frequency is f₃=120/0.50=240 Hz; equivalently f₁=80 Hz and f₃=3f₁."),
      b("第 n 谐波有 n 个半波段和 n+1 个节点（包括两端），所以第三谐波有 4 个节点。", "The nth harmonic has n half-wave segments and n+1 nodes including the ends, so the third has 4 nodes."),
      b("检查图形：三个“波腹区间”由四个节点分隔；不要把波腹数 3 误当节点数。", "Visual check: three antinode regions are separated by four nodes; do not confuse three antinodes with nodes."),
    ],
    conclusion: b("第三谐波 240 Hz、4 个节点，选 C。", "The third harmonic is 240 Hz with 4 nodes, so C is correct."),
    transfer: b("若一端固定一端自由，允许的谐波序列为什么会改变？先写两端边界条件。", "Why does the harmonic sequence change for one fixed and one free end? State both boundary conditions first."),
  },
  {
    id: "physics-9-difficulty-01",
    courseId: "physics",
    topicId: "physics-9",
    kind: "calculation",
    question: b(
      "理想液压机小活塞面积 4.0 cm²，大活塞面积 200 cm²。小活塞施力 160 N 并下移 0.50 m。大活塞输出力和上移距离分别为？",
      "An ideal hydraulic press has piston areas 4.0 cm² and 200 cm². A 160 N force moves the small piston down 0.50 m. What are the output force and upward displacement of the large piston?",
    ),
    options: [
      b("8000 N；0.010 m", "8000 N; 0.010 m"),
      b("3200 N；0.025 m", "3200 N; 0.025 m"),
      b("8000 N；25 m", "8000 N; 25 m"),
      b("160 N；0.50 m", "160 N; 0.50 m"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "diagram-board", "unit-conversion"],
    steps: [
      b("帕斯卡原理给同一静止液体中传递压强相同：F₁/A₁=F₂/A₂。面积比可直接用 cm²，因为单位会约掉。", "Pascal's principle gives F₁/A₁=F₂/A₂. The area ratio may use cm² directly because units cancel."),
      b("F₂=F₁(A₂/A₁)=160×(200/4)=160×50=8000 N。", "F₂=160×(200/4)=8000 N."),
      b("不可压缩流体守恒体积：A₁d₁=A₂d₂，所以 d₂=d₁(A₁/A₂)=0.50×4/200=0.010 m。", "Volume conservation gives A₁d₁=A₂d₂, so d₂=0.50×4/200=0.010 m."),
      b("力放大 50 倍，距离缩小 50 倍；理想做功 F₁d₁=160×0.50=80 J，F₂d₂=8000×0.010=80 J。", "Force rises by 50 while distance falls by 50; ideal work is 80 J on both sides."),
      b("检查机械优势不是免费能量：输出力大但移动短。C 同时把力和距离放大，违反能量守恒。", "Check that mechanical advantage is not free energy: larger output force comes with shorter travel. C violates energy conservation."),
    ],
    conclusion: b("输出 8000 N，上移 0.010 m，选 A。", "The output is 8000 N over 0.010 m, so A is correct."),
    transfer: b("若效率只有 80%，在同一输入功下实际输出功是多少？哪一个量需要根据装置定义修正？", "At 80% efficiency, what is actual output work for the same input, and which output quantity must be adjusted by the device specification?"),
  },
  {
    id: "physics-9-difficulty-02",
    courseId: "physics",
    topicId: "physics-9",
    kind: "combination",
    question: b(
      "水平水管从截面积 A₁ 收缩到 A₂=A₁/4。入口 v₁=2.0 m/s、p₁=220 kPa，水密度 1000 kg/m³，忽略黏性。出口速度与压强为？",
      "A horizontal water pipe contracts to A₂=A₁/4. At the inlet v₁=2.0 m/s and p₁=220 kPa. Water density is 1000 kg/m³ and viscosity is neglected. What are outlet speed and pressure?",
    ),
    options: [
      b("v₂=0.50 m/s，p₂=221.9 kPa", "v₂=0.50 m/s, p₂=221.9 kPa"),
      b("v₂=8.0 m/s，p₂=190 kPa", "v₂=8.0 m/s, p₂=190 kPa"),
      b("v₂=8.0 m/s，p₂=250 kPa", "v₂=8.0 m/s, p₂=250 kPa"),
      b("v₂=4.0 m/s，p₂=214 kPa", "v₂=4.0 m/s, p₂=214 kPa"),
    ],
    answer: 1,
    responseMode: "worked-response",
    cognitiveRole: "multi-step-calculation",
    estimatedMinutes: 10,
    answerTools: ["scientific-calculator", "diagram-board", "unit-conversion"],
    steps: [
      b("先检查条件：稳态、不可压缩、水平、同一流线、忽略黏性，允许连续性方程与伯努利方程联用。", "Check assumptions: steady, incompressible, horizontal flow on a streamline with negligible viscosity, allowing continuity and Bernoulli."),
      b("连续性 A₁v₁=A₂v₂。因 A₂=A₁/4，v₂=(A₁/A₂)v₁=4×2=8.0 m/s。", "Continuity gives A₁v₁=A₂v₂, so v₂=4v₁=8.0 m/s."),
      b("水平伯努利：p₁+½ρv₁²=p₂+½ρv₂²，因此 p₂=p₁+½ρ(v₁²−v₂²)。", "Horizontal Bernoulli gives p₂=p₁+½ρ(v₁²−v₂²)."),
      b("动压差 ½×1000×(4−64)=−30,000 Pa=−30 kPa，所以 p₂=220−30=190 kPa。", "The dynamic-pressure difference is −30,000 Pa=−30 kPa, so p₂=190 kPa."),
      b("检查：窄处速度增大，在同高理想流中静压应下降；8 m/s 与 190 kPa 符合。若有黏性损失，简单伯努利需加入损失项。", "Check: the narrow section is faster and at equal height should have lower static pressure, matching 8 m/s and 190 kPa. Viscous loss would require a loss term."),
    ],
    conclusion: b("v₂=8.0 m/s、p₂=190 kPa，选 B。", "v₂=8.0 m/s and p₂=190 kPa, so B is correct."),
    transfer: b("若出口比入口高 2 m，压力还会比 190 kPa 更高还是更低？先判断重力势能项。", "If the outlet is 2 m higher, would pressure be above or below 190 kPa? Track the gravitational term."),
  },
  {
    id: "physics-9-difficulty-03",
    courseId: "physics",
    topicId: "physics-9",
    kind: "scenario",
    question: b(
      "体积 0.0080 m³、质量 6.0 kg 的密闭物体完全浸没在水中并由细绳向下拉住，ρ水=1000 kg/m³、g=9.8 m/s²。绳张力及剪断瞬间物体加速度约为？",
      "A sealed object of volume 0.0080 m³ and mass 6.0 kg is fully submerged in water and held by a downward tether. With ρ=1000 kg/m³ and g=9.8 m/s², what are tether tension and the object's acceleration immediately after cutting it?",
    ),
    options: [
      b("19.6 N 向下；3.27 m/s² 向上", "19.6 N downward; 3.27 m/s² upward"),
      b("78.4 N 向下；9.8 m/s² 向上", "78.4 N downward; 9.8 m/s² upward"),
      b("58.8 N 向上；3.27 m/s² 向下", "58.8 N upward; 3.27 m/s² downward"),
      b("137.2 N 向下；0 m/s²", "137.2 N downward; 0 m/s²"),
    ],
    answer: 0,
    responseMode: "worked-response",
    cognitiveRole: "transfer",
    estimatedMinutes: 9,
    answerTools: ["scientific-calculator", "diagram-board", "unit-conversion"],
    steps: [
      b("完全浸没时排水体积等于物体体积。浮力 F_B=ρVg=1000×0.0080×9.8=78.4 N 向上。", "When fully submerged, displaced volume equals object volume. Buoyancy is F_B=ρVg=78.4 N upward."),
      b("重力 mg=6.0×9.8=58.8 N 向下。物体若无绳会有 19.6 N 净向上力。", "Weight is 58.8 N downward, leaving 19.6 N net upward without the tether."),
      b("拉住静止时 ΣF=0，所以绳必须提供 T=78.4−58.8=19.6 N 向下。", "For equilibrium, the tether must provide T=78.4−58.8=19.6 N downward."),
      b("剪断瞬间速度仍为零，但绳力消失；浮力与重力暂未改变。净力 19.6 N 向上，a=19.6/6.0≈3.27 m/s² 向上。", "Immediately after cutting, speed is still zero but tension vanishes; buoyancy and weight are initially unchanged. Thus a=19.6/6.0≈3.27 m/s² upward."),
      b("检查加速度小于 g，因为浮力只比重力大约三分之一；不能把浮力直接除质量而忽略重力。随后若体积或阻力变化，加速度不会一直保持该值。", "Check: acceleration is below g because buoyancy exceeds weight by only about one-third. Later drag or volume changes mean this acceleration need not remain constant."),
    ],
    conclusion: b("张力 19.6 N 向下；剪断瞬间加速度 3.27 m/s² 向上，选 A。", "Tension is 19.6 N downward and initial acceleration is 3.27 m/s² upward, so A is correct."),
    transfer: b("若物体只部分浸没漂浮，为什么不能仍用完整 0.0080 m³ 计算排水体积？", "If the object floats partially submerged, why can the full 0.0080 m³ no longer be used as displaced volume?"),
  },
];

export const physicsDifficultyQuestionBank: InstructorQuestion[] = seeds.map(buildQuestion);
